# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_service_edge_group" "this" {
  for_each = var.items

  latitude                          = each.value.latitude
  location                          = each.value.location
  longitude                         = each.value.longitude
  name                              = each.value.name
  city                              = each.value.city
  city_country                      = each.value.city_country
  country_code                      = each.value.country_code
  description                       = each.value.description
  enabled                           = each.value.enabled
  enrollment_cert_id                = each.value.enrollment_cert_id
  exclusive_for_business_continuity = each.value.exclusive_for_business_continuity
  grace_distance_enabled            = each.value.grace_distance_enabled
  grace_distance_value              = each.value.grace_distance_value
  grace_distance_value_unit         = each.value.grace_distance_value_unit
  is_public                         = each.value.is_public
  microtenant_id                    = each.value.microtenant_id
  override_version_profile          = each.value.override_version_profile
  upgrade_day                       = each.value.upgrade_day
  upgrade_time_in_secs              = each.value.upgrade_time_in_secs
  use_in_dr_mode                    = each.value.use_in_dr_mode
  user_codes                        = each.value.user_codes
  version_profile_id                = each.value.version_profile_id
  version_profile_name              = each.value.version_profile_name
  version_profile_visibility_scope  = each.value.version_profile_visibility_scope

  dynamic "service_edges" {
    for_each = each.value.service_edges == null ? [] : [each.value.service_edges]
    content {
      id = service_edges.value.id
    }
  }

  dynamic "trusted_networks" {
    for_each = each.value.trusted_networks == null ? [] : each.value.trusted_networks
    content {
      id = trusted_networks.value.id
    }
  }
}
