# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_service_edge_group instances, keyed by a stable identifier."
  type = map(object({
    latitude                          = string
    location                          = string
    longitude                         = string
    name                              = string
    city                              = optional(string)
    city_country                      = optional(string)
    country_code                      = optional(string)
    description                       = optional(string)
    enabled                           = optional(bool)
    enrollment_cert_id                = optional(string)
    exclusive_for_business_continuity = optional(bool)
    grace_distance_enabled            = optional(bool)
    grace_distance_value              = optional(string)
    grace_distance_value_unit         = optional(string)
    is_public                         = optional(bool)
    microtenant_id                    = optional(string)
    override_version_profile          = optional(bool)
    upgrade_day                       = optional(string)
    upgrade_time_in_secs              = optional(string)
    use_in_dr_mode                    = optional(bool)
    user_codes                        = optional(set(string))
    version_profile_id                = optional(string)
    version_profile_name              = optional(string)
    version_profile_visibility_scope  = optional(string)
    service_edges = optional(object({
      id = optional(set(string))
    }))
    trusted_networks = optional(list(object({
      id = optional(set(string))
    })))
  }))
}
