# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

output "items" {
  description = "All managed zpa_tag_namespace resources, keyed as in var.items."
  value       = zpa_tag_namespace.this
}

output "name_to_id" {
  description = "Map of resource name to provider-assigned id."
  value       = { for k, v in zpa_tag_namespace.this : v.name => v.id }
}
