# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_tag_namespace instances, keyed by a stable identifier."
  type = map(object({
    name           = string
    description    = optional(string)
    enabled        = optional(bool)
    microtenant_id = optional(string)
    origin         = optional(string)
    type           = optional(string)
  }))
}
