# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

output "items" {
  description = "All managed zpa_policy_access_rule resources (excludes deprecated: rule_order), keyed as in var.items."
  value = {
    for k, v in zpa_policy_access_rule.this : k => {
      action                    = v.action
      action_id                 = v.action_id
      bypass_default_rule       = v.bypass_default_rule
      custom_msg                = v.custom_msg
      default_rule              = v.default_rule
      description               = v.description
      id                        = v.id
      lss_default_rule          = v.lss_default_rule
      microtenant_id            = v.microtenant_id
      name                      = v.name
      operator                  = v.operator
      policy_set_id             = v.policy_set_id
      policy_type               = v.policy_type
      priority                  = v.priority
      reauth_default_rule       = v.reauth_default_rule
      reauth_idle_timeout       = v.reauth_idle_timeout
      reauth_timeout            = v.reauth_timeout
      zpn_cbi_profile_id        = v.zpn_cbi_profile_id
      zpn_inspection_profile_id = v.zpn_inspection_profile_id
      zpn_isolation_profile_id  = v.zpn_isolation_profile_id
      app_connector_groups      = v.app_connector_groups
      app_server_groups         = v.app_server_groups
      conditions                = v.conditions
    }
  }
}

output "name_to_id" {
  description = "Map of resource name to provider-assigned id."
  value       = { for k, v in zpa_policy_access_rule.this : v.name => v.id }
}
