# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_cloud_browser_isolation_certificate" "this" {
  for_each = var.items

  name = each.value.name
  pem  = each.value.pem
}
