# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

output "items" {
  description = "All managed zpa_cloud_browser_isolation_certificate resources, keyed as in var.items."
  value       = zpa_cloud_browser_isolation_certificate.this
}
