# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_cloud_browser_isolation_certificate instances, keyed by a stable identifier."
  type = map(object({
    name = optional(string)
    pem  = optional(string)
  }))
}
