# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_bandwidth_classes_web_conferencing" "this" {
  for_each = var.items

  applications = each.value.applications
  name         = each.value.name
  type         = each.value.type
}
