# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_bandwidth_classes_web_conferencing instances, keyed by a stable identifier."
  type = map(object({
    applications = optional(set(string))
    name         = optional(string)
    type         = optional(string)
  }))
}
