# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_pra_credential_controller" "this" {
  for_each = var.items

  credential_type = each.value.credential_type
  description     = each.value.description
  microtenant_id  = each.value.microtenant_id
  name            = each.value.name
  passphrase      = each.value.passphrase
  password        = each.value.password
  private_key     = each.value.private_key
  user_domain     = each.value.user_domain
  username        = each.value.username
}
