# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

output "items" {
  description = "All managed zpa_pra_credential_controller resources, keyed as in var.items."
  sensitive   = true
  value       = zpa_pra_credential_controller.this
}
