# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_pra_credential_controller instances, keyed by a stable identifier."
  type = map(object({
    credential_type = optional(string)
    description     = optional(string)
    microtenant_id  = optional(string)
    name            = optional(string)
    passphrase      = optional(string)
    password        = optional(string)
    private_key     = optional(string)
    user_domain     = optional(string)
    username        = optional(string)
  }))
}
