# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_user_portal_link" "this" {
  for_each = var.items

  name           = each.value.name
  application_id = each.value.application_id
  description    = each.value.description
  enabled        = each.value.enabled
  icon_text      = each.value.icon_text
  link           = each.value.link
  link_path      = each.value.link_path
  microtenant_id = each.value.microtenant_id
  protocol       = each.value.protocol

  dynamic "user_portals" {
    for_each = each.value.user_portals == null ? [] : each.value.user_portals
    content {
      id = user_portals.value.id
    }
  }
}
