# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_user_portal_link instances, keyed by a stable identifier."
  type = map(object({
    name           = string
    application_id = optional(string)
    description    = optional(string)
    enabled        = optional(bool)
    icon_text      = optional(string)
    link           = optional(string)
    link_path      = optional(string)
    microtenant_id = optional(string)
    protocol       = optional(string)
    user_portals = optional(list(object({
      id = optional(set(string))
    })))
  }))
}
