# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_dlp_engines" "this" {
  for_each = var.items

  name              = each.value.name
  custom_dlp_engine = each.value.custom_dlp_engine
  description       = each.value.description
  engine_expression = each.value.engine_expression
}
