# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_dlp_engines instances, keyed by a stable identifier."
  type = map(object({
    name              = string
    custom_dlp_engine = optional(bool)
    description       = optional(string)
    engine_expression = optional(string)
  }))
}
