# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_sandbox_behavioral_analysis_v2" "this" {
  for_each = var.items


  dynamic "md5_hash_value_list" {
    for_each = each.value.md5_hash_value_list == null ? [] : each.value.md5_hash_value_list
    content {
      type        = md5_hash_value_list.value.type
      url         = md5_hash_value_list.value.url
      url_comment = md5_hash_value_list.value.url_comment
    }
  }
}
