# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_sandbox_behavioral_analysis_v2 instances, keyed by a stable identifier."
  type = map(object({
    md5_hash_value_list = optional(set(object({
      type        = optional(string)
      url         = optional(string)
      url_comment = optional(string)
    })))
  }))
}
