# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_firewall_filtering_network_service" "this" {
  for_each = var.items

  name             = each.value.name
  description      = each.value.description
  is_name_l10n_tag = each.value.is_name_l10n_tag
  tag              = each.value.tag
  type             = each.value.type

  dynamic "dest_tcp_ports" {
    for_each = each.value.dest_tcp_ports == null ? [] : each.value.dest_tcp_ports
    content {
      end   = dest_tcp_ports.value.end
      start = dest_tcp_ports.value.start
    }
  }

  dynamic "dest_udp_ports" {
    for_each = each.value.dest_udp_ports == null ? [] : each.value.dest_udp_ports
    content {
      end   = dest_udp_ports.value.end
      start = dest_udp_ports.value.start
    }
  }

  dynamic "src_tcp_ports" {
    for_each = each.value.src_tcp_ports == null ? [] : each.value.src_tcp_ports
    content {
      end   = src_tcp_ports.value.end
      start = src_tcp_ports.value.start
    }
  }

  dynamic "src_udp_ports" {
    for_each = each.value.src_udp_ports == null ? [] : each.value.src_udp_ports
    content {
      end   = src_udp_ports.value.end
      start = src_udp_ports.value.start
    }
  }
}
