# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_firewall_filtering_network_service instances, keyed by a stable identifier."
  type = map(object({
    name             = string
    description      = optional(string)
    is_name_l10n_tag = optional(bool)
    tag              = optional(string)
    type             = optional(string)
    dest_tcp_ports = optional(set(object({
      end   = optional(number)
      start = optional(number)
    })))
    dest_udp_ports = optional(set(object({
      end   = optional(number)
      start = optional(number)
    })))
    src_tcp_ports = optional(set(object({
      end   = optional(number)
      start = optional(number)
    })))
    src_udp_ports = optional(set(object({
      end   = optional(number)
      start = optional(number)
    })))
  }))
}
