# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_url_filtering_and_cloud_app_settings" "this" {
  for_each = var.items

  consider_embedded_sites                 = each.value.consider_embedded_sites
  enable_block_override_for_non_auth_user = each.value.enable_block_override_for_non_auth_user
  enable_chatgpt_prompt                   = each.value.enable_chatgpt_prompt
  enable_cipa_compliance                  = each.value.enable_cipa_compliance
  enable_claude_prompt                    = each.value.enable_claude_prompt
  enable_creative_commons_search_results  = each.value.enable_creative_commons_search_results
  enable_deep_seek_prompt                 = each.value.enable_deep_seek_prompt
  enable_dynamic_content_cat              = each.value.enable_dynamic_content_cat
  enable_gemini_prompt                    = each.value.enable_gemini_prompt
  enable_grammarly_prompt                 = each.value.enable_grammarly_prompt
  enable_grok_prompt                      = each.value.enable_grok_prompt
  enable_meta_prompt                      = each.value.enable_meta_prompt
  enable_microsoft_copilot_prompt         = each.value.enable_microsoft_copilot_prompt
  enable_mistral_ai_prompt                = each.value.enable_mistral_ai_prompt
  enable_msft_o365                        = each.value.enable_msft_o365
  enable_newly_registered_domains         = each.value.enable_newly_registered_domains
  enable_office365                        = each.value.enable_office365
  enable_per_plexity_prompt               = each.value.enable_per_plexity_prompt
  enable_poe_prompt                       = each.value.enable_poe_prompt
  enable_ucaas_logmein                    = each.value.enable_ucaas_logmein
  enable_ucaas_ring_central               = each.value.enable_ucaas_ring_central
  enable_ucaas_talkdesk                   = each.value.enable_ucaas_talkdesk
  enable_ucaas_webex                      = each.value.enable_ucaas_webex
  enable_ucaas_zoom                       = each.value.enable_ucaas_zoom
  enable_writer_prompt                    = each.value.enable_writer_prompt
  enforce_safe_search                     = each.value.enforce_safe_search
  safe_search_apps                        = each.value.safe_search_apps
  zvelo_db_lookup_disabled                = each.value.zvelo_db_lookup_disabled
}
