# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_url_filtering_and_cloud_app_settings instances, keyed by a stable identifier."
  type = map(object({
    consider_embedded_sites                 = optional(bool)
    enable_block_override_for_non_auth_user = optional(bool)
    enable_chatgpt_prompt                   = optional(bool)
    enable_cipa_compliance                  = optional(bool)
    enable_claude_prompt                    = optional(bool)
    enable_creative_commons_search_results  = optional(bool)
    enable_deep_seek_prompt                 = optional(bool)
    enable_dynamic_content_cat              = optional(bool)
    enable_gemini_prompt                    = optional(bool)
    enable_grammarly_prompt                 = optional(bool)
    enable_grok_prompt                      = optional(bool)
    enable_meta_prompt                      = optional(bool)
    enable_microsoft_copilot_prompt         = optional(bool)
    enable_mistral_ai_prompt                = optional(bool)
    enable_msft_o365                        = optional(bool)
    enable_newly_registered_domains         = optional(bool)
    enable_office365                        = optional(bool)
    enable_per_plexity_prompt               = optional(bool)
    enable_poe_prompt                       = optional(bool)
    enable_ucaas_logmein                    = optional(bool)
    enable_ucaas_ring_central               = optional(bool)
    enable_ucaas_talkdesk                   = optional(bool)
    enable_ucaas_webex                      = optional(bool)
    enable_ucaas_zoom                       = optional(bool)
    enable_writer_prompt                    = optional(bool)
    enforce_safe_search                     = optional(bool)
    safe_search_apps                        = optional(set(string))
    zvelo_db_lookup_disabled                = optional(bool)
  }))
}
