# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_dc_exclusions" "this" {
  for_each = var.items

  datacenter_id  = each.value.datacenter_id
  description    = each.value.description
  end_time       = each.value.end_time
  end_time_utc   = each.value.end_time_utc
  start_time     = each.value.start_time
  start_time_utc = each.value.start_time_utc
}
