# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_dc_exclusions instances, keyed by a stable identifier."
  type = map(object({
    datacenter_id  = optional(number)
    description    = optional(string)
    end_time       = optional(number)
    end_time_utc   = optional(string)
    start_time     = optional(number)
    start_time_utc = optional(string)
  }))
}
