# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_policy_timeout_rule" "this" {
  for_each = var.items

  name                      = each.value.name
  action                    = each.value.action
  action_id                 = each.value.action_id
  bypass_default_rule       = each.value.bypass_default_rule
  custom_msg                = each.value.custom_msg
  default_rule              = each.value.default_rule
  description               = each.value.description
  lss_default_rule          = each.value.lss_default_rule
  microtenant_id            = each.value.microtenant_id
  operator                  = each.value.operator
  policy_set_id             = each.value.policy_set_id
  policy_type               = each.value.policy_type
  priority                  = each.value.priority
  reauth_default_rule       = each.value.reauth_default_rule
  reauth_idle_timeout       = each.value.reauth_idle_timeout
  reauth_timeout            = each.value.reauth_timeout
  zpn_cbi_profile_id        = each.value.zpn_cbi_profile_id
  zpn_inspection_profile_id = each.value.zpn_inspection_profile_id
  zpn_isolation_profile_id  = each.value.zpn_isolation_profile_id

  dynamic "conditions" {
    for_each = each.value.conditions == null ? [] : each.value.conditions
    content {
      operator       = conditions.value.operator
      microtenant_id = conditions.value.microtenant_id

      dynamic "operands" {
        for_each = conditions.value.operands == null ? [] : conditions.value.operands
        content {
          lhs            = operands.value.lhs
          object_type    = operands.value.object_type
          idp_id         = operands.value.idp_id
          microtenant_id = operands.value.microtenant_id
          name           = operands.value.name
          rhs            = operands.value.rhs
          rhs_list       = operands.value.rhs_list
        }
      }
    }
  }
}
