# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_emergency_access_user" "this" {
  for_each = var.items

  email_id   = each.value.email_id
  first_name = each.value.first_name
  last_name  = each.value.last_name
  user_id    = each.value.user_id
}
