# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_emergency_access_user instances, keyed by a stable identifier."
  type = map(object({
    email_id   = optional(string)
    first_name = optional(string)
    last_name  = optional(string)
    user_id    = optional(string)
  }))
}
