# GENERATED by tools/gen_module.py from schemas/provider/zcc.json — do not edit.
# Regenerate: make generate

resource "zcc_notification_template" "this" {
  for_each = var.items

  name                      = each.value.name
  duration_in_seconds       = each.value.duration_in_seconds
  enable_app_updates        = each.value.enable_app_updates
  enable_client             = each.value.enable_client
  enable_do_not_disturb     = each.value.enable_do_not_disturb
  enable_persistent         = each.value.enable_persistent
  enable_service_status     = each.value.enable_service_status
  enable_zia                = each.value.enable_zia
  is_default_template       = each.value.is_default_template
  zia_notification_template = each.value.zia_notification_template
  zpa_notification_template = each.value.zpa_notification_template
}
