# GENERATED by tools/gen_module.py from schemas/provider/zcc.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zcc_notification_template instances, keyed by a stable identifier."
  type = map(object({
    name                  = string
    duration_in_seconds   = optional(number)
    enable_app_updates    = optional(bool)
    enable_client         = optional(bool)
    enable_do_not_disturb = optional(bool)
    enable_persistent     = optional(bool)
    enable_service_status = optional(bool)
    enable_zia            = optional(bool)
    is_default_template   = optional(bool)
    zia_notification_template = optional(object({
      enable_zia_dns            = optional(bool)
      enable_zia_dns_popup      = optional(bool)
      enable_zia_firewall       = optional(bool)
      enable_zia_firewall_popup = optional(bool)
      enable_zia_ips            = optional(bool)
      enable_zia_ips_popup      = optional(bool)
      enable_zia_persistent     = optional(bool)
    }))
    zpa_notification_template = optional(object({
      delay_posture_failure_seconds  = optional(number)
      enable_device_posture_failure  = optional(bool)
      enable_zpa_reauth              = optional(bool)
      zpa_reauth_interval_in_minutes = optional(number)
    }))
  }))
}
