# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_dlp_dictionaries" "this" {
  for_each = var.items

  bin_numbers                             = each.value.bin_numbers
  confidence_level_for_predefined_dict    = each.value.confidence_level_for_predefined_dict
  confidence_threshold                    = each.value.confidence_threshold
  custom                                  = each.value.custom
  custom_phrase_match_type                = each.value.custom_phrase_match_type
  description                             = each.value.description
  dict_template_id                        = each.value.dict_template_id
  dictionary_type                         = each.value.dictionary_type
  hierarchical_identifiers                = each.value.hierarchical_identifiers
  ignore_exact_match_idm_dict             = each.value.ignore_exact_match_idm_dict
  include_bin_numbers                     = each.value.include_bin_numbers
  name                                    = each.value.name
  proximity                               = each.value.proximity
  proximity_enabled_for_custom_dictionary = each.value.proximity_enabled_for_custom_dictionary

  dynamic "exact_data_match_details" {
    for_each = each.value.exact_data_match_details == null ? [] : each.value.exact_data_match_details
    content {
      dictionary_edm_mapping_id = exact_data_match_details.value.dictionary_edm_mapping_id
      primary_fields            = exact_data_match_details.value.primary_fields
      schema_id                 = exact_data_match_details.value.schema_id
      secondary_field_match_on  = exact_data_match_details.value.secondary_field_match_on
      secondary_fields          = exact_data_match_details.value.secondary_fields
    }
  }

  dynamic "idm_profile_match_accuracy" {
    for_each = each.value.idm_profile_match_accuracy == null ? [] : each.value.idm_profile_match_accuracy
    content {
      match_accuracy = idm_profile_match_accuracy.value.match_accuracy

      dynamic "adp_idm_profile" {
        for_each = idm_profile_match_accuracy.value.adp_idm_profile == null ? [] : idm_profile_match_accuracy.value.adp_idm_profile
        content {
          extensions = adp_idm_profile.value.extensions
          id         = adp_idm_profile.value.id
        }
      }
    }
  }

  dynamic "patterns" {
    for_each = each.value.patterns == null ? [] : each.value.patterns
    content {
      action  = patterns.value.action
      pattern = patterns.value.pattern
    }
  }

  dynamic "phrases" {
    for_each = each.value.phrases == null ? [] : each.value.phrases
    content {
      action = phrases.value.action
      phrase = phrases.value.phrase
    }
  }
}
