# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_dlp_dictionaries instances, keyed by a stable identifier."
  type = map(object({
    bin_numbers                             = optional(list(number))
    confidence_level_for_predefined_dict    = optional(string)
    confidence_threshold                    = optional(string)
    custom                                  = optional(bool)
    custom_phrase_match_type                = optional(string)
    description                             = optional(string)
    dict_template_id                        = optional(number)
    dictionary_type                         = optional(string)
    hierarchical_identifiers                = optional(set(string))
    ignore_exact_match_idm_dict             = optional(bool)
    include_bin_numbers                     = optional(bool)
    name                                    = optional(string)
    proximity                               = optional(number)
    proximity_enabled_for_custom_dictionary = optional(bool)
    exact_data_match_details = optional(set(object({
      dictionary_edm_mapping_id = optional(number)
      primary_fields            = optional(list(number))
      schema_id                 = optional(number)
      secondary_field_match_on  = optional(string)
      secondary_fields          = optional(list(number))
    })))
    idm_profile_match_accuracy = optional(set(object({
      match_accuracy = optional(string)
      adp_idm_profile = optional(set(object({
        extensions = optional(map(string))
        id         = optional(number)
      })))
    })))
    patterns = optional(set(object({
      action  = optional(string)
      pattern = optional(string)
    })))
    phrases = optional(set(object({
      action = optional(string)
      phrase = optional(string)
    })))
  }))
}
