# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_forwarding_control_rule instances, keyed by a stable identifier."
  type = map(object({
    forward_method     = string
    order              = number
    description        = optional(string)
    dest_addresses     = optional(set(string))
    dest_countries     = optional(set(string))
    dest_ip_categories = optional(set(string))
    name               = optional(string)
    rank               = optional(number)
    res_categories     = optional(set(string))
    src_ips            = optional(set(string))
    state              = optional(string)
    type               = optional(string)
    app_service_groups = optional(object({
      id = optional(set(number))
    }))
    dedicated_ip_gateway = optional(object({
      id   = optional(number)
      name = optional(string)
    }))
    departments = optional(object({
      id = optional(set(number))
    }))
    dest_ip_groups = optional(object({
      id = optional(set(number))
    }))
    dest_ipv6_groups = optional(object({
      id = optional(set(number))
    }))
    device_groups = optional(object({
      id = optional(set(number))
    }))
    ec_groups = optional(object({
      id = optional(set(number))
    }))
    groups = optional(object({
      id = optional(set(number))
    }))
    labels = optional(object({
      id = optional(set(number))
    }))
    location_groups = optional(object({
      id = optional(set(number))
    }))
    locations = optional(object({
      id = optional(set(number))
    }))
    nw_application_groups = optional(object({
      id = optional(set(number))
    }))
    nw_service_groups = optional(object({
      id = optional(set(number))
    }))
    nw_services = optional(object({
      id = optional(set(number))
    }))
    proxy_gateway = optional(object({
      id   = optional(number)
      name = optional(string)
    }))
    src_ip_groups = optional(object({
      id = optional(set(number))
    }))
    src_ipv6_groups = optional(object({
      id = optional(set(number))
    }))
    timeouts = optional(object({
      create = optional(string)
      update = optional(string)
    }))
    users = optional(object({
      id = optional(set(number))
    }))
    zpa_app_segments = optional(set(object({
      external_id = optional(string)
      name        = optional(string)
    })))
    zpa_application_segment_groups = optional(object({
      id = optional(set(number))
    }))
    zpa_application_segments = optional(object({
      id = optional(set(number))
    }))
    zpa_gateway = optional(object({
      id   = optional(number)
      name = optional(string)
    }))
  }))
}
