# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_private_cloud_group" "this" {
  for_each = var.items

  name                     = each.value.name
  city_country             = each.value.city_country
  country_code             = each.value.country_code
  description              = each.value.description
  enabled                  = each.value.enabled
  is_public                = each.value.is_public
  latitude                 = each.value.latitude
  location                 = each.value.location
  longitude                = each.value.longitude
  microtenant_id           = each.value.microtenant_id
  override_version_profile = each.value.override_version_profile
  site_id                  = each.value.site_id
  upgrade_day              = each.value.upgrade_day
  upgrade_time_in_secs     = each.value.upgrade_time_in_secs
  version_profile_id       = each.value.version_profile_id
}
