# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_private_cloud_group instances, keyed by a stable identifier."
  type = map(object({
    name                     = string
    city_country             = optional(string)
    country_code             = optional(string)
    description              = optional(string)
    enabled                  = optional(bool)
    is_public                = optional(string)
    latitude                 = optional(string)
    location                 = optional(string)
    longitude                = optional(string)
    microtenant_id           = optional(string)
    override_version_profile = optional(bool)
    site_id                  = optional(string)
    upgrade_day              = optional(string)
    upgrade_time_in_secs     = optional(string)
    version_profile_id       = optional(string)
  }))
}
