# GENERATED by tools/gen_module.py from schemas/provider/zcc.json — do not edit.
# Regenerate: make generate

resource "zcc_web_privacy" "this" {
  for_each = var.items

  active                             = each.value.active
  collect_machine_hostname           = each.value.collect_machine_hostname
  collect_user_info                  = each.value.collect_user_info
  collect_zdx_location               = each.value.collect_zdx_location
  disable_crashlytics                = each.value.disable_crashlytics
  enable_auto_log_snippet            = each.value.enable_auto_log_snippet
  enable_fqdn_match_for_vpn_bypasses = each.value.enable_fqdn_match_for_vpn_bypasses
  enable_packet_capture              = each.value.enable_packet_capture
  enforce_secure_pac_urls            = each.value.enforce_secure_pac_urls
  export_logs_for_non_admin          = each.value.export_logs_for_non_admin
  grant_access_to_zscaler_log_folder = each.value.grant_access_to_zscaler_log_folder
  override_t2_protocol_setting       = each.value.override_t2_protocol_setting
  restrict_remote_packet_capture     = each.value.restrict_remote_packet_capture
}
