# GENERATED by tools/gen_module.py from schemas/provider/zcc.json — do not edit.
# Regenerate: make generate

output "items" {
  description = "All managed zcc_web_privacy resources, keyed as in var.items."
  value       = zcc_web_privacy.this
}
