# GENERATED by tools/gen_module.py from schemas/provider/zcc.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zcc_web_privacy instances, keyed by a stable identifier."
  type = map(object({
    active                             = optional(bool)
    collect_machine_hostname           = optional(bool)
    collect_user_info                  = optional(bool)
    collect_zdx_location               = optional(bool)
    disable_crashlytics                = optional(bool)
    enable_auto_log_snippet            = optional(bool)
    enable_fqdn_match_for_vpn_bypasses = optional(bool)
    enable_packet_capture              = optional(bool)
    enforce_secure_pac_urls            = optional(bool)
    export_logs_for_non_admin          = optional(bool)
    grant_access_to_zscaler_log_folder = optional(bool)
    override_t2_protocol_setting       = optional(bool)
    restrict_remote_packet_capture     = optional(bool)
  }))
}
