# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_url_categories_predefined" "this" {
  for_each = var.items

  name                                = each.value.name
  ip_ranges                           = each.value.ip_ranges
  ip_ranges_retaining_parent_category = each.value.ip_ranges_retaining_parent_category
  keywords                            = each.value.keywords
  keywords_retaining_parent_category  = each.value.keywords_retaining_parent_category
  urls                                = each.value.urls
  urls_retaining_parent_category      = each.value.urls_retaining_parent_category
}
