# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_url_categories_predefined instances, keyed by a stable identifier."
  type = map(object({
    name                                = string
    ip_ranges                           = optional(set(string))
    ip_ranges_retaining_parent_category = optional(set(string))
    keywords                            = optional(set(string))
    keywords_retaining_parent_category  = optional(set(string))
    urls                                = optional(set(string))
    urls_retaining_parent_category      = optional(set(string))
  }))
}
