# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_application_segment_multimatch_bulk" "this" {
  for_each = var.items

  application_ids = each.value.application_ids
  match_style     = each.value.match_style
}
