# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

output "items" {
  description = "All managed zpa_application_segment_multimatch_bulk resources, keyed as in var.items."
  value       = zpa_application_segment_multimatch_bulk.this
}
