# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_application_segment_multimatch_bulk instances, keyed by a stable identifier."
  type = map(object({
    application_ids = set(string)
    match_style     = string
  }))
}
