# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_cloud_browser_isolation_external_profile" "this" {
  for_each = var.items

  banner_id       = each.value.banner_id
  name            = each.value.name
  certificate_ids = each.value.certificate_ids
  description     = each.value.description
  region_ids      = each.value.region_ids

  dynamic "debug_mode" {
    for_each = each.value.debug_mode == null ? [] : [each.value.debug_mode]
    content {
      allowed       = debug_mode.value.allowed
      file_password = debug_mode.value.file_password
    }
  }

  dynamic "security_controls" {
    for_each = each.value.security_controls == null ? [] : [each.value.security_controls]
    content {
      allow_printing      = security_controls.value.allow_printing
      copy_paste          = security_controls.value.copy_paste
      document_viewer     = security_controls.value.document_viewer
      flattened_pdf       = security_controls.value.flattened_pdf
      local_render        = security_controls.value.local_render
      restrict_keystrokes = security_controls.value.restrict_keystrokes
      upload_download     = security_controls.value.upload_download

      dynamic "deep_link" {
        for_each = security_controls.value.deep_link == null ? [] : [security_controls.value.deep_link]
        content {
          applications = deep_link.value.applications
          enabled      = deep_link.value.enabled
        }
      }

      dynamic "watermark" {
        for_each = security_controls.value.watermark == null ? [] : [security_controls.value.watermark]
        content {
          enabled        = watermark.value.enabled
          message        = watermark.value.message
          show_message   = watermark.value.show_message
          show_timestamp = watermark.value.show_timestamp
          show_user_id   = watermark.value.show_user_id
        }
      }
    }
  }

  dynamic "user_experience" {
    for_each = each.value.user_experience == null ? [] : [each.value.user_experience]
    content {
      browser_in_browser    = user_experience.value.browser_in_browser
      persist_isolation_bar = user_experience.value.persist_isolation_bar
      session_persistence   = user_experience.value.session_persistence
      translate             = user_experience.value.translate
      zgpu                  = user_experience.value.zgpu

      dynamic "forward_to_zia" {
        for_each = user_experience.value.forward_to_zia == null ? [] : [user_experience.value.forward_to_zia]
        content {
          cloud_name      = forward_to_zia.value.cloud_name
          enabled         = forward_to_zia.value.enabled
          organization_id = forward_to_zia.value.organization_id
          pac_file_url    = forward_to_zia.value.pac_file_url
        }
      }
    }
  }
}
