# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_cloud_browser_isolation_external_profile instances, keyed by a stable identifier."
  type = map(object({
    banner_id       = string
    name            = string
    certificate_ids = optional(set(string))
    description     = optional(string)
    region_ids      = optional(set(string))
    debug_mode = optional(object({
      allowed       = optional(bool)
      file_password = optional(string)
    }))
    security_controls = optional(object({
      allow_printing      = optional(bool)
      copy_paste          = optional(string)
      document_viewer     = optional(bool)
      flattened_pdf       = optional(bool)
      local_render        = optional(bool)
      restrict_keystrokes = optional(bool)
      upload_download     = optional(string)
      deep_link = optional(object({
        applications = optional(set(string))
        enabled      = optional(bool)
      }))
      watermark = optional(object({
        enabled        = optional(bool)
        message        = optional(string)
        show_message   = optional(bool)
        show_timestamp = optional(bool)
        show_user_id   = optional(bool)
      }))
    }))
    user_experience = optional(object({
      browser_in_browser    = optional(bool)
      persist_isolation_bar = optional(bool)
      session_persistence   = optional(bool)
      translate             = optional(bool)
      zgpu                  = optional(bool)
      forward_to_zia = optional(object({
        cloud_name      = optional(string)
        enabled         = optional(bool)
        organization_id = optional(string)
        pac_file_url    = optional(string)
      }))
    }))
  }))
}
