# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_risk_profiles" "this" {
  for_each = var.items

  profile_name                 = each.value.profile_name
  admin_audit_logs             = each.value.admin_audit_logs
  certifications               = each.value.certifications
  data_breach                  = each.value.data_breach
  data_encryption_in_transit   = each.value.data_encryption_in_transit
  dns_caa_policy               = each.value.dns_caa_policy
  domain_based_message_auth    = each.value.domain_based_message_auth
  domain_keys_identified_mail  = each.value.domain_keys_identified_mail
  evasive                      = each.value.evasive
  exclude_certificates         = each.value.exclude_certificates
  file_sharing                 = each.value.file_sharing
  http_security_headers        = each.value.http_security_headers
  malware_scanning_for_content = each.value.malware_scanning_for_content
  mfa_support                  = each.value.mfa_support
  password_strength            = each.value.password_strength
  poor_items_of_service        = each.value.poor_items_of_service
  profile_type                 = each.value.profile_type
  remote_screen_sharing        = each.value.remote_screen_sharing
  risk_index                   = each.value.risk_index
  sender_policy_framework      = each.value.sender_policy_framework
  source_ip_restrictions       = each.value.source_ip_restrictions
  ssl_cert_key_size            = each.value.ssl_cert_key_size
  ssl_cert_validity            = each.value.ssl_cert_validity
  ssl_pinned                   = each.value.ssl_pinned
  status                       = each.value.status
  support_for_waf              = each.value.support_for_waf
  vulnerability                = each.value.vulnerability
  vulnerability_disclosure     = each.value.vulnerability_disclosure
  vulnerable_to_heart_bleed    = each.value.vulnerable_to_heart_bleed
  vulnerable_to_log_jam        = each.value.vulnerable_to_log_jam
  vulnerable_to_poodle         = each.value.vulnerable_to_poodle
  weak_cipher_support          = each.value.weak_cipher_support

  dynamic "custom_tags" {
    for_each = each.value.custom_tags == null ? [] : [each.value.custom_tags]
    content {
      id = custom_tags.value.id
    }
  }
}
