# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_risk_profiles instances, keyed by a stable identifier."
  type = map(object({
    profile_name                 = string
    admin_audit_logs             = optional(string)
    certifications               = optional(set(string))
    data_breach                  = optional(string)
    data_encryption_in_transit   = optional(set(string))
    dns_caa_policy               = optional(string)
    domain_based_message_auth    = optional(string)
    domain_keys_identified_mail  = optional(string)
    evasive                      = optional(string)
    exclude_certificates         = optional(number)
    file_sharing                 = optional(string)
    http_security_headers        = optional(string)
    malware_scanning_for_content = optional(string)
    mfa_support                  = optional(string)
    password_strength            = optional(string)
    poor_items_of_service        = optional(string)
    profile_type                 = optional(string)
    remote_screen_sharing        = optional(string)
    risk_index                   = optional(set(number))
    sender_policy_framework      = optional(string)
    source_ip_restrictions       = optional(string)
    ssl_cert_key_size            = optional(string)
    ssl_cert_validity            = optional(string)
    ssl_pinned                   = optional(string)
    status                       = optional(string)
    support_for_waf              = optional(string)
    vulnerability                = optional(string)
    vulnerability_disclosure     = optional(string)
    vulnerable_to_heart_bleed    = optional(string)
    vulnerable_to_log_jam        = optional(string)
    vulnerable_to_poodle         = optional(string)
    weak_cipher_support          = optional(string)
    custom_tags = optional(object({
      id = optional(list(number))
    }))
  }))
}
