# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_workload_groups" "this" {
  for_each = var.items

  description = each.value.description
  name        = each.value.name

  dynamic "expression_json" {
    for_each = each.value.expression_json == null ? [] : each.value.expression_json
    content {

      dynamic "expression_containers" {
        for_each = expression_json.value.expression_containers == null ? [] : expression_json.value.expression_containers
        content {
          operator = expression_containers.value.operator
          tag_type = expression_containers.value.tag_type

          dynamic "tag_container" {
            for_each = expression_containers.value.tag_container == null ? [] : expression_containers.value.tag_container
            content {
              operator = tag_container.value.operator

              dynamic "tags" {
                for_each = tag_container.value.tags == null ? [] : tag_container.value.tags
                content {
                  key   = tags.value.key
                  value = tags.value.value
                }
              }
            }
          }
        }
      }
    }
  }
}
