# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_workload_groups instances, keyed by a stable identifier."
  type = map(object({
    description = optional(string)
    name        = optional(string)
    expression_json = optional(list(object({
      expression_containers = optional(list(object({
        operator = optional(string)
        tag_type = optional(string)
        tag_container = optional(list(object({
          operator = optional(string)
          tags = optional(list(object({
            key   = optional(string)
            value = optional(string)
          })))
        })))
      })))
    })))
  }))
}
