# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_browser_access instances, keyed by a stable identifier."
  type = map(object({
    domain_names                  = set(string)
    name                          = string
    segment_group_id              = string
    bypass_type                   = optional(string)
    config_space                  = optional(string)
    description                   = optional(string)
    double_encrypt                = optional(bool)
    enabled                       = optional(bool)
    fqdn_dns_check                = optional(bool)
    health_check_type             = optional(string)
    health_reporting              = optional(string)
    icmp_access_type              = optional(string)
    ip_anchored                   = optional(bool)
    is_cname_enabled              = optional(bool)
    is_incomplete_dr_config       = optional(bool)
    microtenant_id                = optional(string)
    passive_health_enabled        = optional(bool)
    segment_group_name            = optional(string)
    select_connector_close_to_app = optional(bool)
    tcp_keep_alive                = optional(string)
    tcp_port_range = optional(list(object({
      from = optional(string)
      to   = optional(string)
    })))
    tcp_port_ranges = optional(list(string))
    udp_port_range = optional(list(object({
      from = optional(string)
      to   = optional(string)
    })))
    udp_port_ranges = optional(list(string))
    use_in_dr_mode  = optional(bool)
    clientless_apps = optional(list(object({
      application_port     = optional(string)
      application_protocol = optional(string)
      name                 = optional(string)
      allow_options        = optional(bool)
      certificate_id       = optional(string)
      description          = optional(string)
      domain               = optional(string)
      enabled              = optional(bool)
      ext_domain           = optional(string)
      ext_label            = optional(string)
      microtenant_id       = optional(string)
      trust_untrusted_cert = optional(bool)
    })))
    server_groups = optional(list(object({
      id = optional(set(string))
    })))
    zpn_er_id = optional(list(object({
      id = optional(set(string))
    })))
  }))
}
