# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_cloud_nss_feed" "this" {
  for_each = var.items

  action_filter                   = each.value.action_filter
  activity                        = each.value.activity
  adv_user_agents                 = each.value.adv_user_agents
  advanced_threats                = each.value.advanced_threats
  alerts                          = each.value.alerts
  audit_log_type                  = each.value.audit_log_type
  authentication_token            = each.value.authentication_token
  authentication_url              = each.value.authentication_url
  base64_encoded_certificate      = each.value.base64_encoded_certificate
  casb_action                     = each.value.casb_action
  casb_applications               = each.value.casb_applications
  casb_file_type                  = each.value.casb_file_type
  casb_file_type_super_categories = each.value.casb_file_type_super_categories
  casb_policy_types               = each.value.casb_policy_types
  casb_severity                   = each.value.casb_severity
  channel_name                    = each.value.channel_name
  client_destination_ips          = each.value.client_destination_ips
  client_destination_ports        = each.value.client_destination_ports
  client_id                       = each.value.client_id
  client_ips                      = each.value.client_ips
  client_secret                   = each.value.client_secret
  client_source_ips               = each.value.client_source_ips
  client_source_ports             = each.value.client_source_ports
  connection_headers              = each.value.connection_headers
  connection_url                  = each.value.connection_url
  countries                       = each.value.countries
  custom_escaped_character        = each.value.custom_escaped_character
  direction                       = each.value.direction
  dns_actions                     = each.value.dns_actions
  dns_request_types               = each.value.dns_request_types
  dns_response_types              = each.value.dns_response_types
  dns_responses                   = each.value.dns_responses
  domains                         = each.value.domains
  download_time                   = each.value.download_time
  durations                       = each.value.durations
  email_dlp_log_type              = each.value.email_dlp_log_type
  email_dlp_policy_action         = each.value.email_dlp_policy_action
  end_point_dlp_log_type          = each.value.end_point_dlp_log_type
  eps_rate_limit                  = each.value.eps_rate_limit
  event                           = each.value.event
  feed_output_format              = each.value.feed_output_format
  feed_status                     = each.value.feed_status
  file_name                       = each.value.file_name
  file_sizes                      = each.value.file_sizes
  file_source                     = each.value.file_source
  file_type_categories            = each.value.file_type_categories
  file_type_super_categories      = each.value.file_type_super_categories
  firewall_actions                = each.value.firewall_actions
  firewall_logging_mode           = each.value.firewall_logging_mode
  full_urls                       = each.value.full_urls
  grant_type                      = each.value.grant_type
  host_names                      = each.value.host_names
  in_bound_bytes                  = each.value.in_bound_bytes
  internal_ips                    = each.value.internal_ips
  json_array_toggle               = each.value.json_array_toggle
  malware_classes                 = each.value.malware_classes
  malware_names                   = each.value.malware_names
  max_batch_size                  = each.value.max_batch_size
  name                            = each.value.name
  nat_actions                     = each.value.nat_actions
  nss_feed_type                   = each.value.nss_feed_type
  nss_log_type                    = each.value.nss_log_type
  nss_type                        = each.value.nss_type
  nw_applications                 = each.value.nw_applications
  nw_applications_exclude         = each.value.nw_applications_exclude
  oauth_authentication            = each.value.oauth_authentication
  object_name                     = each.value.object_name
  object_type                     = each.value.object_type
  object_type1                    = each.value.object_type1
  object_type2                    = each.value.object_type2
  out_bound_bytes                 = each.value.out_bound_bytes
  page_risk_indexes               = each.value.page_risk_indexes
  policy_reasons                  = each.value.policy_reasons
  project_name                    = each.value.project_name
  protocol_types                  = each.value.protocol_types
  referer_urls                    = each.value.referer_urls
  repo_name                       = each.value.repo_name
  request_methods                 = each.value.request_methods
  request_sizes                   = each.value.request_sizes
  response_codes                  = each.value.response_codes
  response_sizes                  = each.value.response_sizes
  scan_time                       = each.value.scan_time
  scope                           = each.value.scope
  server_destination_ips          = each.value.server_destination_ips
  server_ips                      = each.value.server_ips
  server_source_ips               = each.value.server_source_ips
  server_source_ports             = each.value.server_source_ports
  session_counts                  = each.value.session_counts
  siem_type                       = each.value.siem_type
  threat_names                    = each.value.threat_names
  time_zone                       = each.value.time_zone
  traffic_forwards                = each.value.traffic_forwards
  transaction_sizes               = each.value.transaction_sizes
  tunnel_dest_ips                 = each.value.tunnel_dest_ips
  tunnel_ips                      = each.value.tunnel_ips
  tunnel_source_ips               = each.value.tunnel_source_ips
  tunnel_source_port              = each.value.tunnel_source_port
  tunnel_types                    = each.value.tunnel_types
  url_classes                     = each.value.url_classes
  url_super_categories            = each.value.url_super_categories
  user_agents                     = each.value.user_agents
  web_application_classes         = each.value.web_application_classes
  web_applications                = each.value.web_applications
  web_applications_exclude        = each.value.web_applications_exclude
  web_traffic_forwards            = each.value.web_traffic_forwards

  dynamic "buckets" {
    for_each = each.value.buckets == null ? [] : [each.value.buckets]
    content {
      id = buckets.value.id
    }
  }

  dynamic "casb_tenant" {
    for_each = each.value.casb_tenant == null ? [] : [each.value.casb_tenant]
    content {
      id = casb_tenant.value.id
    }
  }

  dynamic "departments" {
    for_each = each.value.departments == null ? [] : [each.value.departments]
    content {
      id = departments.value.id
    }
  }

  dynamic "dlp_dictionaries" {
    for_each = each.value.dlp_dictionaries == null ? [] : [each.value.dlp_dictionaries]
    content {
      id = dlp_dictionaries.value.id
    }
  }

  dynamic "dlp_engines" {
    for_each = each.value.dlp_engines == null ? [] : [each.value.dlp_engines]
    content {
      id = dlp_engines.value.id
    }
  }

  dynamic "external_collaborators" {
    for_each = each.value.external_collaborators == null ? [] : [each.value.external_collaborators]
    content {
      id = external_collaborators.value.id
    }
  }

  dynamic "external_owners" {
    for_each = each.value.external_owners == null ? [] : [each.value.external_owners]
    content {
      id = external_owners.value.id
    }
  }

  dynamic "internal_collaborators" {
    for_each = each.value.internal_collaborators == null ? [] : [each.value.internal_collaborators]
    content {
      id = internal_collaborators.value.id
    }
  }

  dynamic "itsm_object_type" {
    for_each = each.value.itsm_object_type == null ? [] : [each.value.itsm_object_type]
    content {
      id = itsm_object_type.value.id
    }
  }

  dynamic "location_groups" {
    for_each = each.value.location_groups == null ? [] : [each.value.location_groups]
    content {
      id = location_groups.value.id
    }
  }

  dynamic "locations" {
    for_each = each.value.locations == null ? [] : [each.value.locations]
    content {
      id = locations.value.id
    }
  }

  dynamic "nw_services" {
    for_each = each.value.nw_services == null ? [] : [each.value.nw_services]
    content {
      id = nw_services.value.id
    }
  }

  dynamic "rules" {
    for_each = each.value.rules == null ? [] : [each.value.rules]
    content {
      id = rules.value.id
    }
  }

  dynamic "sender_name" {
    for_each = each.value.sender_name == null ? [] : [each.value.sender_name]
    content {
      id = sender_name.value.id
    }
  }

  dynamic "url_categories" {
    for_each = each.value.url_categories == null ? [] : [each.value.url_categories]
    content {
      id = url_categories.value.id
    }
  }

  dynamic "users" {
    for_each = each.value.users == null ? [] : [each.value.users]
    content {
      id = users.value.id
    }
  }

  dynamic "vpn_credentials" {
    for_each = each.value.vpn_credentials == null ? [] : [each.value.vpn_credentials]
    content {
      id = vpn_credentials.value.id
    }
  }
}
