# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_tenant_restriction_profile" "this" {
  for_each = var.items

  name                           = each.value.name
  allow_gcp_cloud_storage_read   = each.value.allow_gcp_cloud_storage_read
  allow_google_consumers         = each.value.allow_google_consumers
  allow_google_visitors          = each.value.allow_google_visitors
  app_type                       = each.value.app_type
  description                    = each.value.description
  item_data_primary              = each.value.item_data_primary
  item_data_secondary            = each.value.item_data_secondary
  item_type_primary              = each.value.item_type_primary
  item_type_secondary            = each.value.item_type_secondary
  item_value                     = each.value.item_value
  ms_login_services_tr_v2        = each.value.ms_login_services_tr_v2
  restrict_personal_o365_domains = each.value.restrict_personal_o365_domains

  dynamic "timeouts" {
    for_each = each.value.timeouts == null ? [] : [each.value.timeouts]
    content {
      create = timeouts.value.create
      update = timeouts.value.update
    }
  }
}
