# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_tenant_restriction_profile instances, keyed by a stable identifier."
  type = map(object({
    name                           = string
    allow_gcp_cloud_storage_read   = optional(bool)
    allow_google_consumers         = optional(bool)
    allow_google_visitors          = optional(bool)
    app_type                       = optional(string)
    description                    = optional(string)
    item_data_primary              = optional(set(string))
    item_data_secondary            = optional(set(string))
    item_type_primary              = optional(string)
    item_type_secondary            = optional(string)
    item_value                     = optional(set(string))
    ms_login_services_tr_v2        = optional(bool)
    restrict_personal_o365_domains = optional(bool)
    timeouts = optional(object({
      create = optional(string)
      update = optional(string)
    }))
  }))
}
