# GENERATED by tools/gen_env.py for tenant 'demo' — do not edit.
# Regenerate: make gen-env TENANT=demo

terraform {
  required_version = ">= 1.5"
  required_providers {
    zia = {
      source = "zscaler/zia"
    }
  }
  # backend configured per environment (Plan 5 / operator)
}

provider "zia" {
  # credentials via env (ZSCALER_*/ZIA_*/ZPA_*); see tools/FETCH.md
}

variable "items" {
  # opaque at the root; the module enforces the strict type.
  type = any
}

module "zia_cloud_app_control_rule" {
  source = "../../../modules/zia_cloud_app_control_rule"
  items  = var.items
}
