# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_pra_portal_controller" "this" {
  for_each = var.items

  approval_reviewers        = each.value.approval_reviewers
  certificate_id            = each.value.certificate_id
  description               = each.value.description
  domain                    = each.value.domain
  enabled                   = each.value.enabled
  ext_domain                = each.value.ext_domain
  ext_domain_name           = each.value.ext_domain_name
  ext_domain_translation    = each.value.ext_domain_translation
  ext_label                 = each.value.ext_label
  microtenant_id            = each.value.microtenant_id
  name                      = each.value.name
  user_notification         = each.value.user_notification
  user_notification_enabled = each.value.user_notification_enabled
  user_portal_gid           = each.value.user_portal_gid
}
