# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_pra_portal_controller instances, keyed by a stable identifier."
  type = map(object({
    approval_reviewers        = optional(set(string))
    certificate_id            = optional(string)
    description               = optional(string)
    domain                    = optional(string)
    enabled                   = optional(bool)
    ext_domain                = optional(string)
    ext_domain_name           = optional(string)
    ext_domain_translation    = optional(string)
    ext_label                 = optional(string)
    microtenant_id            = optional(string)
    name                      = optional(string)
    user_notification         = optional(string)
    user_notification_enabled = optional(bool)
    user_portal_gid           = optional(string)
  }))
}
