# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_dlp_notification_templates" "this" {
  for_each = var.items

  html_message       = each.value.html_message
  name               = each.value.name
  plain_text_message = each.value.plain_text_message
  subject            = each.value.subject
  attach_content     = each.value.attach_content
  tls_enabled        = each.value.tls_enabled
}
