# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_dlp_notification_templates instances, keyed by a stable identifier."
  type = map(object({
    html_message       = string
    name               = string
    plain_text_message = string
    subject            = string
    attach_content     = optional(bool)
    tls_enabled        = optional(bool)
  }))
}
