# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_firewall_filtering_destination_groups" "this" {
  for_each = var.items

  name          = each.value.name
  addresses     = each.value.addresses
  countries     = each.value.countries
  description   = each.value.description
  ip_categories = each.value.ip_categories
  type          = each.value.type
}
