# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_firewall_filtering_destination_groups instances, keyed by a stable identifier."
  type = map(object({
    name          = string
    addresses     = optional(set(string))
    countries     = optional(set(string))
    description   = optional(string)
    ip_categories = optional(set(string))
    type          = optional(string)
  }))
}
