# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_firewall_filtering_network_service_groups" "this" {
  for_each = var.items

  name        = each.value.name
  description = each.value.description

  dynamic "services" {
    for_each = each.value.services == null ? [] : each.value.services
    content {
      id = services.value.id
    }
  }
}
