# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_firewall_filtering_network_service_groups instances, keyed by a stable identifier."
  type = map(object({
    name        = string
    description = optional(string)
    services = optional(set(object({
      id = optional(set(number))
    })))
  }))
}
