# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_application_segment_weightedlb_config" "this" {
  for_each = var.items

  application_id          = each.value.application_id
  application_name        = each.value.application_name
  microtenant_id          = each.value.microtenant_id
  weighted_load_balancing = each.value.weighted_load_balancing

  dynamic "application_to_server_group_mappings" {
    for_each = each.value.application_to_server_group_mappings == null ? [] : each.value.application_to_server_group_mappings
    content {
      id      = application_to_server_group_mappings.value.id
      name    = application_to_server_group_mappings.value.name
      passive = application_to_server_group_mappings.value.passive
      weight  = application_to_server_group_mappings.value.weight
    }
  }
}
