# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_application_segment_weightedlb_config instances, keyed by a stable identifier."
  type = map(object({
    application_id          = optional(string)
    application_name        = optional(string)
    microtenant_id          = optional(string)
    weighted_load_balancing = optional(bool)
    application_to_server_group_mappings = optional(list(object({
      id      = optional(string)
      name    = optional(string)
      passive = optional(bool)
      weight  = optional(string)
    })))
  }))
}
