# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_firewall_filtering_rule" "this" {
  for_each = var.items

  name                  = each.value.name
  order                 = each.value.order
  action                = each.value.action
  default_rule          = each.value.default_rule
  description           = each.value.description
  dest_addresses        = each.value.dest_addresses
  dest_countries        = each.value.dest_countries
  dest_ip_categories    = each.value.dest_ip_categories
  device_trust_levels   = each.value.device_trust_levels
  enable_full_logging   = each.value.enable_full_logging
  exclude_src_countries = each.value.exclude_src_countries
  nw_applications       = each.value.nw_applications
  predefined            = each.value.predefined
  rank                  = each.value.rank
  source_countries      = each.value.source_countries
  src_ips               = each.value.src_ips
  state                 = each.value.state

  dynamic "app_service_groups" {
    for_each = each.value.app_service_groups == null ? [] : [each.value.app_service_groups]
    content {
      id = app_service_groups.value.id
    }
  }

  dynamic "app_services" {
    for_each = each.value.app_services == null ? [] : [each.value.app_services]
    content {
      id = app_services.value.id
    }
  }

  dynamic "departments" {
    for_each = each.value.departments == null ? [] : [each.value.departments]
    content {
      id = departments.value.id
    }
  }

  dynamic "dest_ip_groups" {
    for_each = each.value.dest_ip_groups == null ? [] : [each.value.dest_ip_groups]
    content {
      id = dest_ip_groups.value.id
    }
  }

  dynamic "device_groups" {
    for_each = each.value.device_groups == null ? [] : [each.value.device_groups]
    content {
      id = device_groups.value.id
    }
  }

  dynamic "devices" {
    for_each = each.value.devices == null ? [] : [each.value.devices]
    content {
      id = devices.value.id
    }
  }

  dynamic "groups" {
    for_each = each.value.groups == null ? [] : [each.value.groups]
    content {
      id = groups.value.id
    }
  }

  dynamic "labels" {
    for_each = each.value.labels == null ? [] : [each.value.labels]
    content {
      id = labels.value.id
    }
  }

  dynamic "location_groups" {
    for_each = each.value.location_groups == null ? [] : [each.value.location_groups]
    content {
      id = location_groups.value.id
    }
  }

  dynamic "locations" {
    for_each = each.value.locations == null ? [] : [each.value.locations]
    content {
      id = locations.value.id
    }
  }

  dynamic "nw_application_groups" {
    for_each = each.value.nw_application_groups == null ? [] : [each.value.nw_application_groups]
    content {
      id = nw_application_groups.value.id
    }
  }

  dynamic "nw_service_groups" {
    for_each = each.value.nw_service_groups == null ? [] : [each.value.nw_service_groups]
    content {
      id = nw_service_groups.value.id
    }
  }

  dynamic "nw_services" {
    for_each = each.value.nw_services == null ? [] : [each.value.nw_services]
    content {
      id = nw_services.value.id
    }
  }

  dynamic "src_ip_groups" {
    for_each = each.value.src_ip_groups == null ? [] : [each.value.src_ip_groups]
    content {
      id = src_ip_groups.value.id
    }
  }

  dynamic "time_windows" {
    for_each = each.value.time_windows == null ? [] : [each.value.time_windows]
    content {
      id = time_windows.value.id
    }
  }

  dynamic "timeouts" {
    for_each = each.value.timeouts == null ? [] : [each.value.timeouts]
    content {
      create = timeouts.value.create
      update = timeouts.value.update
    }
  }

  dynamic "users" {
    for_each = each.value.users == null ? [] : [each.value.users]
    content {
      id = users.value.id
    }
  }

  dynamic "workload_groups" {
    for_each = each.value.workload_groups == null ? [] : each.value.workload_groups
    content {
      id   = workload_groups.value.id
      name = workload_groups.value.name
    }
  }

  dynamic "zpa_app_segments" {
    for_each = each.value.zpa_app_segments == null ? [] : each.value.zpa_app_segments
    content {
      external_id = zpa_app_segments.value.external_id
      name        = zpa_app_segments.value.name
    }
  }
}
