# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_security_settings" "this" {
  for_each = var.items

  blacklist_urls = each.value.blacklist_urls
  whitelist_urls = each.value.whitelist_urls
}
