# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_security_settings instances, keyed by a stable identifier."
  type = map(object({
    blacklist_urls = optional(set(string))
    whitelist_urls = optional(set(string))
  }))
}
