# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_firewall_filtering_ip_source_groups" "this" {
  for_each = var.items

  ip_addresses = each.value.ip_addresses
  name         = each.value.name
  description  = each.value.description
}
