# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_firewall_filtering_ip_source_groups instances, keyed by a stable identifier."
  type = map(object({
    ip_addresses = set(string)
    name         = string
    description  = optional(string)
  }))
}
