# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_sandbox_file_submission" "this" {
  for_each = var.items

  file_path         = each.value.file_path
  submission_method = each.value.submission_method
  force             = each.value.force
}
