# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_sandbox_file_submission instances, keyed by a stable identifier."
  type = map(object({
    file_path         = string
    submission_method = string
    force             = optional(bool)
  }))
}
