# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_app_connector_assistant_schedule" "this" {
  for_each = var.items

  customer_id        = each.value.customer_id
  delete_disabled    = each.value.delete_disabled
  enabled            = each.value.enabled
  frequency          = each.value.frequency
  frequency_interval = each.value.frequency_interval
}
