# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_file_type_control_rules" "this" {
  for_each = var.items

  name                    = each.value.name
  order                   = each.value.order
  protocols               = each.value.protocols
  active_content          = each.value.active_content
  browser_eun_template_id = each.value.browser_eun_template_id
  capture_pcap            = each.value.capture_pcap
  cloud_applications      = each.value.cloud_applications
  description             = each.value.description
  device_trust_levels     = each.value.device_trust_levels
  file_types              = each.value.file_types
  filtering_action        = each.value.filtering_action
  max_size                = each.value.max_size
  min_size                = each.value.min_size
  operation               = each.value.operation
  rank                    = each.value.rank
  state                   = each.value.state
  unscannable             = each.value.unscannable
  url_categories          = each.value.url_categories

  dynamic "departments" {
    for_each = each.value.departments == null ? [] : [each.value.departments]
    content {
      id = departments.value.id
    }
  }

  dynamic "device_groups" {
    for_each = each.value.device_groups == null ? [] : [each.value.device_groups]
    content {
      id = device_groups.value.id
    }
  }

  dynamic "devices" {
    for_each = each.value.devices == null ? [] : [each.value.devices]
    content {
      id = devices.value.id
    }
  }

  dynamic "groups" {
    for_each = each.value.groups == null ? [] : [each.value.groups]
    content {
      id = groups.value.id
    }
  }

  dynamic "labels" {
    for_each = each.value.labels == null ? [] : [each.value.labels]
    content {
      id = labels.value.id
    }
  }

  dynamic "location_groups" {
    for_each = each.value.location_groups == null ? [] : [each.value.location_groups]
    content {
      id = location_groups.value.id
    }
  }

  dynamic "locations" {
    for_each = each.value.locations == null ? [] : [each.value.locations]
    content {
      id = locations.value.id
    }
  }

  dynamic "time_windows" {
    for_each = each.value.time_windows == null ? [] : [each.value.time_windows]
    content {
      id = time_windows.value.id
    }
  }

  dynamic "timeouts" {
    for_each = each.value.timeouts == null ? [] : [each.value.timeouts]
    content {
      create = timeouts.value.create
      update = timeouts.value.update
    }
  }

  dynamic "users" {
    for_each = each.value.users == null ? [] : [each.value.users]
    content {
      id = users.value.id
    }
  }

  dynamic "zpa_app_segments" {
    for_each = each.value.zpa_app_segments == null ? [] : each.value.zpa_app_segments
    content {
      external_id = zpa_app_segments.value.external_id
      name        = zpa_app_segments.value.name
    }
  }
}
