# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_file_type_control_rules instances, keyed by a stable identifier."
  type = map(object({
    name                    = string
    order                   = number
    protocols               = set(string)
    active_content          = optional(bool)
    browser_eun_template_id = optional(number)
    capture_pcap            = optional(bool)
    cloud_applications      = optional(set(string))
    description             = optional(string)
    device_trust_levels     = optional(set(string))
    file_types              = optional(set(string))
    filtering_action        = optional(string)
    max_size                = optional(number)
    min_size                = optional(number)
    operation               = optional(string)
    rank                    = optional(number)
    state                   = optional(string)
    unscannable             = optional(bool)
    url_categories          = optional(set(string))
    departments = optional(object({
      id = optional(set(number))
    }))
    device_groups = optional(object({
      id = optional(set(number))
    }))
    devices = optional(object({
      id = optional(set(number))
    }))
    groups = optional(object({
      id = optional(set(number))
    }))
    labels = optional(object({
      id = optional(set(number))
    }))
    location_groups = optional(object({
      id = optional(set(number))
    }))
    locations = optional(object({
      id = optional(set(number))
    }))
    time_windows = optional(object({
      id = optional(set(number))
    }))
    timeouts = optional(object({
      create = optional(string)
      update = optional(string)
    }))
    users = optional(object({
      id = optional(set(number))
    }))
    zpa_app_segments = optional(set(object({
      external_id = optional(string)
      name        = optional(string)
    })))
  }))
}
