# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_advanced_threat_settings" "this" {
  for_each = var.items

  activex_blocked                         = each.value.activex_blocked
  activex_capture                         = each.value.activex_capture
  ad_spyware_sites_blocked                = each.value.ad_spyware_sites_blocked
  ad_spyware_sites_capture                = each.value.ad_spyware_sites_capture
  alert_for_unknown_suspicious_c2_traffic = each.value.alert_for_unknown_suspicious_c2_traffic
  anonymizer_blocked                      = each.value.anonymizer_blocked
  anonymizer_capture                      = each.value.anonymizer_capture
  bit_torrent_blocked                     = each.value.bit_torrent_blocked
  bit_torrent_capture                     = each.value.bit_torrent_capture
  block_countries_capture                 = each.value.block_countries_capture
  blocked_countries                       = each.value.blocked_countries
  browser_exploits_blocked                = each.value.browser_exploits_blocked
  browser_exploits_capture                = each.value.browser_exploits_capture
  cmd_ctl_server_blocked                  = each.value.cmd_ctl_server_blocked
  cmd_ctl_server_capture                  = each.value.cmd_ctl_server_capture
  cmd_ctl_traffic_blocked                 = each.value.cmd_ctl_traffic_blocked
  cmd_ctl_traffic_capture                 = each.value.cmd_ctl_traffic_capture
  cookie_stealing_blocked                 = each.value.cookie_stealing_blocked
  cookie_stealing_pcap_enabled            = each.value.cookie_stealing_pcap_enabled
  crypto_mining_blocked                   = each.value.crypto_mining_blocked
  crypto_mining_capture                   = each.value.crypto_mining_capture
  dga_domains_blocked                     = each.value.dga_domains_blocked
  dga_domains_capture                     = each.value.dga_domains_capture
  file_format_vunerabilites_blocked       = each.value.file_format_vunerabilites_blocked
  file_format_vunerabilites_capture       = each.value.file_format_vunerabilites_capture
  google_talk_blocked                     = each.value.google_talk_blocked
  google_talk_capture                     = each.value.google_talk_capture
  irc_tunnelling_blocked                  = each.value.irc_tunnelling_blocked
  irc_tunnelling_capture                  = each.value.irc_tunnelling_capture
  known_phishing_sites_blocked            = each.value.known_phishing_sites_blocked
  known_phishing_sites_capture            = each.value.known_phishing_sites_capture
  malicious_urls_capture                  = each.value.malicious_urls_capture
  malware_sites_blocked                   = each.value.malware_sites_blocked
  malware_sites_capture                   = each.value.malware_sites_capture
  potential_malicious_requests_blocked    = each.value.potential_malicious_requests_blocked
  potential_malicious_requests_capture    = each.value.potential_malicious_requests_capture
  risk_tolerance                          = each.value.risk_tolerance
  risk_tolerance_capture                  = each.value.risk_tolerance_capture
  ssh_tunnelling_blocked                  = each.value.ssh_tunnelling_blocked
  ssh_tunnelling_capture                  = each.value.ssh_tunnelling_capture
  suspect_adware_spyware_sites_blocked    = each.value.suspect_adware_spyware_sites_blocked
  suspect_adware_spyware_sites_capture    = each.value.suspect_adware_spyware_sites_capture
  suspected_phishing_sites_blocked        = each.value.suspected_phishing_sites_blocked
  suspected_phishing_sites_capture        = each.value.suspected_phishing_sites_capture
  tor_blocked                             = each.value.tor_blocked
  tor_capture                             = each.value.tor_capture
  web_spam_blocked                        = each.value.web_spam_blocked
  web_spam_capture                        = each.value.web_spam_capture
}
