# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_admin_users" "this" {
  for_each = var.items

  email                           = each.value.email
  login_name                      = each.value.login_name
  username                        = each.value.username
  admin_scope_type                = each.value.admin_scope_type
  comments                        = each.value.comments
  disabled                        = each.value.disabled
  is_auditor                      = each.value.is_auditor
  is_exec_mobile_app_enabled      = each.value.is_exec_mobile_app_enabled
  is_non_editable                 = each.value.is_non_editable
  is_password_expired             = each.value.is_password_expired
  is_password_login_allowed       = each.value.is_password_login_allowed
  is_product_update_comm_enabled  = each.value.is_product_update_comm_enabled
  is_security_report_comm_enabled = each.value.is_security_report_comm_enabled
  is_service_update_comm_enabled  = each.value.is_service_update_comm_enabled
  password                        = each.value.password

  dynamic "admin_scope_entities" {
    for_each = each.value.admin_scope_entities == null ? [] : [each.value.admin_scope_entities]
    content {
      id = admin_scope_entities.value.id
    }
  }

  dynamic "role" {
    for_each = each.value.role == null ? [] : each.value.role
    content {
      id = role.value.id
    }
  }
}
