# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

output "items" {
  description = "All managed zia_admin_users resources, keyed as in var.items."
  sensitive   = true
  value       = zia_admin_users.this
}
