# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_admin_users instances, keyed by a stable identifier."
  type = map(object({
    email                           = string
    login_name                      = string
    username                        = string
    admin_scope_type                = optional(string)
    comments                        = optional(string)
    disabled                        = optional(bool)
    is_auditor                      = optional(bool)
    is_exec_mobile_app_enabled      = optional(bool)
    is_non_editable                 = optional(bool)
    is_password_expired             = optional(bool)
    is_password_login_allowed       = optional(bool)
    is_product_update_comm_enabled  = optional(bool)
    is_security_report_comm_enabled = optional(bool)
    is_service_update_comm_enabled  = optional(bool)
    password                        = optional(string)
    admin_scope_entities = optional(object({
      id = optional(set(number))
    }))
    role = optional(set(object({
      id = optional(number)
    })))
  }))
}
