# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_firewall_ips_rule instances, keyed by a stable identifier."
  type = map(object({
    name                = string
    order               = number
    action              = optional(string)
    capture_pcap        = optional(bool)
    default_rule        = optional(bool)
    description         = optional(string)
    dest_addresses      = optional(set(string))
    dest_countries      = optional(set(string))
    dest_ip_categories  = optional(set(string))
    enable_full_logging = optional(bool)
    eun_template_id     = optional(number)
    is_eun_enabled      = optional(bool)
    predefined          = optional(bool)
    rank                = optional(number)
    res_categories      = optional(set(string))
    source_countries    = optional(set(string))
    src_ips             = optional(set(string))
    state               = optional(string)
    departments = optional(object({
      id = optional(set(number))
    }))
    dest_ip_groups = optional(object({
      id = optional(set(number))
    }))
    dest_ipv6_groups = optional(object({
      id = optional(set(number))
    }))
    device_groups = optional(object({
      id = optional(set(number))
    }))
    devices = optional(object({
      id = optional(set(number))
    }))
    groups = optional(object({
      id = optional(set(number))
    }))
    labels = optional(object({
      id = optional(set(number))
    }))
    location_groups = optional(object({
      id = optional(set(number))
    }))
    locations = optional(object({
      id = optional(set(number))
    }))
    nw_service_groups = optional(object({
      id = optional(set(number))
    }))
    nw_services = optional(object({
      id = optional(set(number))
    }))
    src_ip_groups = optional(object({
      id = optional(set(number))
    }))
    src_ipv6_groups = optional(object({
      id = optional(set(number))
    }))
    threat_categories = optional(object({
      id = optional(set(number))
    }))
    time_windows = optional(object({
      id = optional(set(number))
    }))
    timeouts = optional(object({
      create = optional(string)
      update = optional(string)
    }))
    users = optional(object({
      id = optional(set(number))
    }))
    zpa_app_segments = optional(set(object({
      external_id = optional(string)
      name        = optional(string)
    })))
  }))
}
