# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

terraform {
  required_providers {
    zia = {
      source  = "zscaler/zia"
      version = "4.7.24"
    }
  }
}
