# GENERATED by tools/gen_module.py from schemas/provider/zcc.json — do not edit.
# Regenerate: make generate

resource "zcc_device_cleanup" "this" {
  for_each = var.items

  active              = each.value.active
  auto_purge_days     = each.value.auto_purge_days
  auto_removal_days   = each.value.auto_removal_days
  device_exceed_limit = each.value.device_exceed_limit
  force_remove_type   = each.value.force_remove_type
}
