# GENERATED by tools/gen_module.py from schemas/provider/zcc.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zcc_device_cleanup instances, keyed by a stable identifier."
  type = map(object({
    active              = optional(bool)
    auto_purge_days     = optional(number)
    auto_removal_days   = optional(number)
    device_exceed_limit = optional(number)
    force_remove_type   = optional(string)
  }))
}
