# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_atp_security_exceptions" "this" {
  for_each = var.items

  bypass_urls = each.value.bypass_urls
}
