# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_atp_security_exceptions instances, keyed by a stable identifier."
  type = map(object({
    bypass_urls = optional(set(string))
  }))
}
