"""Tests for tools/gen_module.py renderers, pinned to the committed dumps."""
import unittest

from tools.gen_module import render_variables
from tools.tfschema import load_resource

EXPECTED_SEGMENT_GROUP_VARIABLES = '''\
# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_segment_group instances, keyed by a stable identifier."
  type = map(object({
    name = string
    description = optional(string)
    enabled = optional(bool)
    microtenant_id = optional(string)
    applications = optional(list(object({
      id = optional(string)
    })))
  }))
}
'''


class RenderVariablesTest(unittest.TestCase):
    def test_segment_group_exact(self):
        rs = load_resource("zpa_segment_group")
        self.assertEqual(
            render_variables("zpa_segment_group", rs), EXPECTED_SEGMENT_GROUP_VARIABLES
        )

    def test_url_categories_properties(self):
        rs = load_resource("zia_url_categories")
        out = render_variables("zia_url_categories", rs)
        self.assertNotIn("category_id", out)   # computed-only excluded
        self.assertNotIn("\n    val ", out)
        self.assertIn("configured_name = optional(string)", out)
        self.assertIn("urls = optional(list(string))", out)
        self.assertIn("scopes = optional(set(object({", out)
        self.assertIn("url_keyword_counts = optional(list(object({", out)


if __name__ == "__main__":
    unittest.main()
