"""Tests for tools/gen_module.py renderers, pinned to the committed dumps."""
import os
import shutil
import tempfile
import unittest

from tools.gen_module import render_main, render_variables, render_outputs, render_readme, render_test, render_sample, render_versions, generate_module
from tools.tfschema import load_resource

EXPECTED_SEGMENT_GROUP_VARIABLES = '''\
# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_segment_group instances, keyed by a stable identifier."
  type = map(object({
    name = string
    description = optional(string)
    enabled = optional(bool)
    microtenant_id = optional(string)
    applications = optional(list(object({
      id = optional(string)
    })))
  }))
}
'''


class RenderVariablesTest(unittest.TestCase):
    def test_segment_group_exact(self):
        rs = load_resource("zpa_segment_group")
        self.assertEqual(
            render_variables("zpa_segment_group", rs), EXPECTED_SEGMENT_GROUP_VARIABLES
        )

    def test_url_categories_properties(self):
        rs = load_resource("zia_url_categories")
        out = render_variables("zia_url_categories", rs)
        self.assertNotIn("category_id", out)   # computed-only excluded
        self.assertNotIn("\n    val ", out)
        self.assertIn("configured_name = optional(string)", out)
        self.assertIn("urls = optional(list(string))", out)
        self.assertIn("scopes = optional(set(object({", out)
        # max_items=1 list block: typed as ONE object, not list(object)
        self.assertIn("url_keyword_counts = optional(object({", out)
        # nested max_items=1 set block inside scopes: also an object
        self.assertIn("scope_entities = optional(object({", out)


EXPECTED_SEGMENT_GROUP_MAIN = '''\
# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_segment_group" "this" {
  for_each = var.items

  name = each.value.name
  description = each.value.description
  enabled = each.value.enabled
  microtenant_id = each.value.microtenant_id

  dynamic "applications" {
    for_each = each.value.applications == null ? [] : each.value.applications
    content {
      id = applications.value.id
    }
  }
}
'''


class RenderMainTest(unittest.TestCase):
    def test_segment_group_exact(self):
        rs = load_resource("zpa_segment_group")
        self.assertEqual(
            render_main("zpa_segment_group", rs), EXPECTED_SEGMENT_GROUP_MAIN
        )

    def test_url_categories_properties(self):
        rs = load_resource("zia_url_categories")
        out = render_main("zia_url_categories", rs)
        self.assertIn('resource "zia_url_categories" "this"', out)
        self.assertIn('dynamic "scopes"', out)
        self.assertIn('dynamic "url_keyword_counts"', out)
        self.assertNotIn("category_id", out)  # computed-only never assigned

    def test_single_mode_block_wraps_in_list(self):
        fake = {
            "block": {
                "attributes": {"name": {"type": "string", "required": True}},
                "block_types": {
                    "settings": {
                        "nesting_mode": "single",
                        "block": {
                            "attributes": {"on": {"type": "bool", "optional": True}}
                        },
                    }
                },
            }
        }
        out = render_main("zia_fake", fake)
        self.assertIn(
            "for_each = each.value.settings == null ? [] : [each.value.settings]", out
        )


class RenderRestTest(unittest.TestCase):
    def test_outputs_exact(self):
        rs = load_resource("zpa_segment_group")
        out = render_outputs("zpa_segment_group", rs)
        self.assertIn('output "items" {', out)
        self.assertIn("value = zpa_segment_group.this", out)
        self.assertIn('output "name_to_id" {', out)
        self.assertIn(
            "value = { for k, v in zpa_segment_group.this : v.name => v.id }", out
        )

    def test_outputs_omits_name_map_without_name(self):
        fake = {"block": {"attributes": {"id": {"type": "string", "computed": True}}}}
        out = render_outputs("zia_fake", fake)
        self.assertNotIn("name_to_id", out)

    def test_outputs_omits_name_map_for_optional_name(self):
        # An optional name can be null at plan time; a null for-expression
        # key fails the plan, so name_to_id requires a REQUIRED name.
        # Real case: zia_cloud_app_control_rule.
        fake = {
            "block": {
                "attributes": {
                    "id": {"type": "string", "computed": True},
                    "name": {"type": "string", "optional": True},
                }
            }
        }
        out = render_outputs("zia_fake", fake)
        self.assertNotIn("name_to_id", out)

    def test_readme_mentions_regeneration(self):
        rs = load_resource("zpa_segment_group")
        out = render_readme("zpa_segment_group", rs)
        self.assertIn("make generate", out)
        self.assertIn("zpa_segment_group", out)

    def test_sample_has_required_attrs_only(self):
        rs = load_resource("zpa_segment_group")
        sample = render_sample("zpa_segment_group", rs)
        self.assertEqual(sample, '{\n  "items": {\n    "example": {\n      "name": "example"\n    }\n  }\n}\n')

    def test_sample_collections_get_example_members(self):
        # required set(string) must sample as ["example"], not [] — an empty
        # collection can hide provider plan-time validation in module tests.
        rs = load_resource("zpa_application_segment")
        sample = render_sample("zpa_application_segment", rs)
        import json as _json
        item = _json.loads(sample)["items"]["example"]
        self.assertEqual(item["domain_names"], ["example"])

    def test_sample_override_wins(self):
        # enum-constrained required attrs need real values (e.g. protocols);
        # the override map's "sample" key supplies them.
        rs = load_resource("zia_url_filtering_rules")
        sample = render_sample(
            "zia_url_filtering_rules", rs, sample_override={"protocols": ["ANY_RULE"]}
        )
        import json as _json
        item = _json.loads(sample)["items"]["example"]
        self.assertEqual(item["protocols"], ["ANY_RULE"])
        self.assertEqual(item["name"], "example")

    def test_headroom_enum_samples_are_overridden(self):
        from tools.transform import load_override
        import json as _json

        activation = render_sample(
            "zia_activation_status",
            load_resource("zia_activation_status"),
            sample_override=load_override("zia_activation_status").get("sample"),
        )
        self.assertEqual(
            _json.loads(activation)["items"]["example"]["status"], "ACTIVE")

        bandwidth = render_sample(
            "zia_bandwidth_control_rule",
            load_resource("zia_bandwidth_control_rule"),
            sample_override=load_override("zia_bandwidth_control_rule").get("sample"),
        )
        self.assertEqual(
            _json.loads(bandwidth)["items"]["example"]["protocols"], ["ANY_RULE"])

    def test_headroom_sample_override_files_are_applied(self):
        from tools.transform import load_override
        import json as _json

        expected = {
            "zcc_zia_posture": {"platform": "windows"},
            "zia_file_type_control_rules": {"protocols": ["ANY_RULE"]},
            "zia_forwarding_control_rule": {"forward_method": "DIRECT"},
            "zia_sandbox_file_submission": {"submission_method": "submit"},
            "zia_sandbox_rules": {"protocols": ["ANY_RULE"]},
            "zia_traffic_forwarding_gre_tunnel": {"source_ip": "192.0.2.10"},
            "zia_traffic_forwarding_static_ip": {"ip_address": "192.0.2.20"},
            "zpa_application_segment_browser_access": {
                "clientless_apps": [{
                    "application_port": "443",
                    "application_protocol": "HTTPS",
                    "name": "example",
                }],
            },
            "zpa_application_segment_multimatch_bulk": {"match_style": "EXCLUSIVE"},
            "zpa_application_segment_weightedlb_config": {
                "application_id": "example"
            },
            "zpa_browser_access": {
                "clientless_apps": [{
                    "application_port": "443",
                    "application_protocol": "HTTPS",
                    "name": "example",
                }],
            },
            "zpa_inspection_custom_controls": {
                "severity": "INFO",
                "type": "REQUEST",
            },
            "zpa_policy_credential_rule": {
                "credential": [{"id": "example"}],
            },
            "zpa_provisioning_key": {"association_type": "CONNECTOR_GRP"},
            "zpa_zia_cloud_config": {"zia_cloud_domain": "zscaler"},
        }

        for resource_type, fields in sorted(expected.items()):
            sample = render_sample(
                resource_type,
                load_resource(resource_type),
                sample_override=load_override(resource_type).get("sample"),
            )
            item = _json.loads(sample)["items"]["example"]
            for field, value in sorted(fields.items()):
                self.assertEqual(item[field], value, resource_type)

    def test_test_skeleton_uses_mock_provider(self):
        rs = load_resource("zpa_segment_group")
        out = render_test("zpa_segment_group", rs)
        self.assertIn('mock_provider "zpa" {}', out)
        self.assertIn("command = plan", out)
        self.assertIn("length(var.items) == 1", out)

    def test_versions_contains_provider_source(self):
        rs = load_resource("zpa_segment_group")
        out = render_versions("zpa_segment_group", rs)
        self.assertIn('source = "zscaler/zpa"', out)
        self.assertIn("required_providers", out)

    def test_versions_zia_source(self):
        rs = load_resource("zia_url_categories")
        out = render_versions("zia_url_categories", rs)
        self.assertIn('source = "zscaler/zia"', out)

    def test_every_generated_versions_pins_its_provider(self):
        # Regression: an unpinned zia/zpa lets deploy-time `terraform init`
        # resolve a newer (pre-1.0, churn-expected) provider than the schema
        # dumps were built from, breaking plan or splitting a cross-runner
        # plan->apply. Every generated module MUST carry a version line.
        from tools.registry import generated_types
        for resource_type in generated_types():
            out = render_versions(resource_type, load_resource(resource_type))
            self.assertIn(
                "      version = ", out,
                "%s/versions.tf has no provider version pin — extend "
                "_PROVIDER_VERSION_CONSTRAINTS (sourced from "
                "tools/schema-extract/main.tf)" % resource_type,
            )

    def test_versions_pins_match_schema_extract(self):
        # The pins the modules emit must equal the ones the schema dumps were
        # extracted under, so variables.tf types and the installed provider
        # can never silently diverge.
        from tools.gen_module import _load_provider_pins
        pins = _load_provider_pins()
        self.assertEqual(pins.get("zia"), "4.7.24")
        self.assertEqual(pins.get("zpa"), "4.4.4")
        out_zia = render_versions("zia_url_categories", load_resource("zia_url_categories"))
        self.assertIn('version = "4.7.24"', out_zia)
        out_zpa = render_versions("zpa_segment_group", load_resource("zpa_segment_group"))
        self.assertIn('version = "4.4.4"', out_zpa)

    def test_load_provider_pins_fails_loud_on_missing_file(self):
        # A silent {} would regenerate unpinned modules, reintroducing the bug;
        # the parser must raise with remediation instead.
        from tools.gen_module import _load_provider_pins
        with self.assertRaises(ValueError) as ctx:
            _load_provider_pins(os.path.join("tools", "schema-extract", "nope.tf"))
        self.assertIn("provider pins not found", str(ctx.exception))


class GenerateModuleTest(unittest.TestCase):
    def test_writes_all_files(self):
        with tempfile.TemporaryDirectory() as td:
            generate_module("zpa_segment_group", out_root=td, overrides_root=os.path.join(td, "none"), fmt=False)
            base = os.path.join(td, "zpa_segment_group")
            for fname in ("variables.tf", "versions.tf", "main.tf", "outputs.tf", "README.md"):
                self.assertTrue(os.path.exists(os.path.join(base, fname)), fname)
            self.assertTrue(os.path.exists(os.path.join(base, "tests", "defaults.tftest.hcl")))
            self.assertTrue(os.path.exists(os.path.join(base, "tests", "sample.auto.tfvars.json")))

    def test_override_replaces_main(self):
        with tempfile.TemporaryDirectory() as td:
            ov = os.path.join(td, "ov", "zpa_segment_group")
            os.makedirs(ov)
            with open(os.path.join(ov, "main.tf"), "w", encoding="utf-8") as f:
                f.write("# OVERRIDE\n")
            generate_module("zpa_segment_group", out_root=os.path.join(td, "mod"), overrides_root=os.path.join(td, "ov"), fmt=False)
            with open(os.path.join(td, "mod", "zpa_segment_group", "main.tf"), encoding="utf-8") as f:
                self.assertEqual(f.read(), "# OVERRIDE\n")

class GoldenTest(unittest.TestCase):
    GOLDENS = [
        ("zia_cloud_app_control_rule", "variables.tf", "render_variables"),
        ("zia_cloud_app_control_rule", "main.tf", "render_main"),
        ("zia_cloud_app_control_rule", "outputs.tf", "render_outputs"),
        ("zia_cloud_app_control_rule", "versions.tf", "render_versions"),
        ("zia_location_management", "variables.tf", "render_variables"),
        ("zia_location_management", "main.tf", "render_main"),
        ("zia_location_management", "outputs.tf", "render_outputs"),
        ("zia_location_management", "versions.tf", "render_versions"),
        ("zia_rule_labels", "variables.tf", "render_variables"),
        ("zia_rule_labels", "main.tf", "render_main"),
        ("zia_rule_labels", "outputs.tf", "render_outputs"),
        ("zia_rule_labels", "versions.tf", "render_versions"),
        ("zia_ssl_inspection_rules", "variables.tf", "render_variables"),
        ("zia_ssl_inspection_rules", "main.tf", "render_main"),
        ("zia_ssl_inspection_rules", "outputs.tf", "render_outputs"),
        ("zia_ssl_inspection_rules", "versions.tf", "render_versions"),
        ("zia_url_categories", "variables.tf", "render_variables"),
        ("zia_url_categories", "main.tf", "render_main"),
        ("zia_url_categories", "outputs.tf", "render_outputs"),
        ("zia_url_categories", "versions.tf", "render_versions"),
        ("zia_url_filtering_rules", "variables.tf", "render_variables"),
        ("zia_url_filtering_rules", "main.tf", "render_main"),
        ("zia_url_filtering_rules", "outputs.tf", "render_outputs"),
        ("zia_url_filtering_rules", "versions.tf", "render_versions"),
        ("zpa_app_connector_group", "variables.tf", "render_variables"),
        ("zpa_app_connector_group", "main.tf", "render_main"),
        ("zpa_app_connector_group", "outputs.tf", "render_outputs"),
        ("zpa_app_connector_group", "versions.tf", "render_versions"),
        ("zpa_application_segment", "variables.tf", "render_variables"),
        ("zpa_application_segment", "main.tf", "render_main"),
        ("zpa_application_segment", "outputs.tf", "render_outputs"),
        ("zpa_application_segment", "versions.tf", "render_versions"),
        ("zpa_application_server", "variables.tf", "render_variables"),
        ("zpa_application_server", "main.tf", "render_main"),
        ("zpa_application_server", "outputs.tf", "render_outputs"),
        ("zpa_application_server", "versions.tf", "render_versions"),
        ("zpa_policy_access_rule", "variables.tf", "render_variables"),
        ("zpa_policy_access_rule", "main.tf", "render_main"),
        ("zpa_policy_access_rule", "outputs.tf", "render_outputs"),
        ("zpa_policy_access_rule", "versions.tf", "render_versions"),
        ("zpa_segment_group", "variables.tf", "render_variables"),
        ("zpa_segment_group", "main.tf", "render_main"),
        ("zpa_segment_group", "outputs.tf", "render_outputs"),
        ("zpa_segment_group", "versions.tf", "render_versions"),
        ("zpa_server_group", "variables.tf", "render_variables"),
        ("zpa_server_group", "main.tf", "render_main"),
        ("zpa_server_group", "outputs.tf", "render_outputs"),
        ("zpa_server_group", "versions.tf", "render_versions"),
    ]

    def test_rendered_output_matches_blessed_goldens(self):
        if shutil.which("terraform") is None:
            self.skipTest("terraform not on PATH — generator goldens are authoring-side")
        import tools.gen_module as g
        for resource_type, fname, renderer in self.GOLDENS:
            path = os.path.join("tools", "tests", "fixtures", "gen", resource_type, fname)
            with open(path, encoding="utf-8") as f:
                expected = f.read()
            rendered = g._fmt(getattr(g, renderer)(resource_type, load_resource(resource_type)))
            self.assertEqual(rendered, expected, "%s/%s drifted — make update-goldens after intentional changes" % (resource_type, fname))


class AllComputedBlockTest(unittest.TestCase):
    FAKE = {
        "block": {
            "attributes": {"name": {"type": "string", "required": True}},
            "block_types": {
                "user": {
                    "nesting_mode": "set",
                    "block": {
                        "attributes": {
                            "username": {"type": "string", "computed": True}
                        }
                    },
                }
            },
        }
    }

    def test_render_main_skips_all_computed_block(self):
        from tools.gen_module import render_main
        out = render_main("zpa_fake", self.FAKE)
        self.assertNotIn('dynamic "user"', out)

    def test_render_variables_skips_all_computed_block(self):
        from tools.gen_module import render_variables
        out = render_variables("zpa_fake", self.FAKE)
        self.assertNotIn("user =", out)


class NestedTypeRenderTest(unittest.TestCase):
    def test_nested_type_attribute_renders_as_object_input(self):
        rs = load_resource("zcc_zia_posture")
        out = render_variables("zcc_zia_posture", rs)
        self.assertIn("high_trust_criteria = optional(object({", out)
        self.assertIn("cs = optional(list(object({", out)



class SampleValueObjectTest(unittest.TestCase):
    def test_list_of_object_samples_object_members_not_nested_list(self):
        # the [[]] shape failed `terraform test` with a cryptic type error
        from tools.gen_module import _sample_value
        self.assertEqual(
            _sample_value(["list", ["object", {"key": "string",
                                               "value": "string"}]]),
            [{"key": "example", "value": "example"}])
        self.assertEqual(
            _sample_value(["set", ["object", {"name": "string"}]]),
            [{"name": "example"}])


class PinsNoVersionTest(unittest.TestCase):
    def test_pins_file_without_version_lines_fails_loud(self):
        import tempfile
        from tools.gen_module import _load_provider_pins
        with tempfile.NamedTemporaryFile("w", suffix=".tf", delete=False,
                                         encoding="utf-8") as f:
            f.write('zia = { source = "zscaler/zia" }')
            path = f.name
        try:
            with self.assertRaises(ValueError) as ctx:
                _load_provider_pins(path)
            self.assertIn("no versioned providers", str(ctx.exception))
        finally:
            os.unlink(path)


class UnknownNestingModeTest(unittest.TestCase):
    def test_unknown_nesting_mode_fails_loud(self):
        from tools.gen_module import _block_input_type
        with self.assertRaises(ValueError) as ctx:
            _block_input_type({"nesting_mode": "group", "block": {
                "attributes": {"id": {"type": "string",
                                      "optional": True}}}}, 2)
        self.assertIn("unsupported nesting_mode", str(ctx.exception))


class SampleGoldenTest(unittest.TestCase):
    """render_sample output must match the COMMITTED module fixtures for
    every generated type — the modules tree is already CHECK-gated, so
    this pins sample generation without new fixture machinery (and runs
    everywhere: samples are JSON, no terraform fmt involved)."""

    def test_samples_match_committed_modules(self):
        from tools.gen_module import render_sample
        from tools.registry import generated_types
        from tools.tfschema import load_resource
        from tools.transform import load_override
        for rt in generated_types():
            committed = os.path.join("modules", rt, "tests",
                                     "sample.auto.tfvars.json")
            self.assertTrue(os.path.exists(committed), committed)
            with open(committed, encoding="utf-8") as f:
                want = f.read()
            got = render_sample(rt, load_resource(rt),
                                load_override(rt).get("sample"))
            self.assertEqual(got, want, rt)


if __name__ == "__main__":
    unittest.main()
