"""Tests for tools/gen_module.py renderers, pinned to the committed dumps."""
import unittest

from tools.gen_module import render_main, render_variables
from tools.tfschema import load_resource

EXPECTED_SEGMENT_GROUP_VARIABLES = '''\
# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_segment_group instances, keyed by a stable identifier."
  type = map(object({
    name = string
    description = optional(string)
    enabled = optional(bool)
    microtenant_id = optional(string)
    applications = optional(list(object({
      id = optional(string)
    })))
  }))
}
'''


class RenderVariablesTest(unittest.TestCase):
    def test_segment_group_exact(self):
        rs = load_resource("zpa_segment_group")
        self.assertEqual(
            render_variables("zpa_segment_group", rs), EXPECTED_SEGMENT_GROUP_VARIABLES
        )

    def test_url_categories_properties(self):
        rs = load_resource("zia_url_categories")
        out = render_variables("zia_url_categories", rs)
        self.assertNotIn("category_id", out)   # computed-only excluded
        self.assertNotIn("\n    val ", out)
        self.assertIn("configured_name = optional(string)", out)
        self.assertIn("urls = optional(list(string))", out)
        self.assertIn("scopes = optional(set(object({", out)
        self.assertIn("url_keyword_counts = optional(list(object({", out)


EXPECTED_SEGMENT_GROUP_MAIN = '''\
# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_segment_group" "this" {
  for_each = var.items

  name = each.value.name
  description = each.value.description
  enabled = each.value.enabled
  microtenant_id = each.value.microtenant_id

  dynamic "applications" {
    for_each = each.value.applications == null ? [] : each.value.applications
    content {
      id = applications.value.id
    }
  }
}
'''


class RenderMainTest(unittest.TestCase):
    def test_segment_group_exact(self):
        rs = load_resource("zpa_segment_group")
        self.assertEqual(
            render_main("zpa_segment_group", rs), EXPECTED_SEGMENT_GROUP_MAIN
        )

    def test_url_categories_properties(self):
        rs = load_resource("zia_url_categories")
        out = render_main("zia_url_categories", rs)
        self.assertIn('resource "zia_url_categories" "this"', out)
        self.assertIn('dynamic "scopes"', out)
        self.assertIn('dynamic "url_keyword_counts"', out)
        self.assertNotIn("category_id", out)  # computed-only never assigned

    def test_single_mode_block_wraps_in_list(self):
        fake = {
            "block": {
                "attributes": {"name": {"type": "string", "required": True}},
                "block_types": {
                    "settings": {
                        "nesting_mode": "single",
                        "block": {
                            "attributes": {"on": {"type": "bool", "optional": True}}
                        },
                    }
                },
            }
        }
        out = render_main("zia_fake", fake)
        self.assertIn(
            "for_each = each.value.settings == null ? [] : [each.value.settings]", out
        )


if __name__ == "__main__":
    unittest.main()
