# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_traffic_forwarding_static_ip" "this" {
  for_each = var.items

  ip_address   = each.value.ip_address
  comment      = each.value.comment
  geo_override = each.value.geo_override
  latitude     = each.value.latitude
  longitude    = each.value.longitude
  routable_ip  = each.value.routable_ip
}
