# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_traffic_forwarding_static_ip instances, keyed by a stable identifier."
  type = map(object({
    ip_address   = string
    comment      = optional(string)
    geo_override = optional(bool)
    latitude     = optional(number)
    longitude    = optional(number)
    routable_ip  = optional(bool)
  }))
}
