# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_atp_malicious_urls" "this" {
  for_each = var.items

  malicious_urls = each.value.malicious_urls
}
