# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_ips_signature_rules" "this" {
  for_each = var.items

  name        = each.value.name
  rule_text   = each.value.rule_text
  description = each.value.description
  enabled     = each.value.enabled

  dynamic "category" {
    for_each = each.value.category == null ? [] : [each.value.category]
    content {
      id               = category.value.id
      is_name_l10n_tag = category.value.is_name_l10n_tag
      name             = category.value.name
    }
  }
}
