# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_ips_signature_rules instances, keyed by a stable identifier."
  type = map(object({
    name        = string
    rule_text   = string
    description = optional(string)
    enabled     = optional(bool)
    category = optional(object({
      id               = optional(number)
      is_name_l10n_tag = optional(bool)
      name             = optional(string)
    }))
  }))
}
