# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_dlp_web_rules" "this" {
  for_each = var.items

  name                       = each.value.name
  order                      = each.value.order
  action                     = each.value.action
  cloud_applications         = each.value.cloud_applications
  description                = each.value.description
  dlp_download_scan_enabled  = each.value.dlp_download_scan_enabled
  eun_template_id            = each.value.eun_template_id
  external_auditor_email     = each.value.external_auditor_email
  file_types                 = each.value.file_types
  inspect_http_get_enabled   = each.value.inspect_http_get_enabled
  match_only                 = each.value.match_only
  min_size                   = each.value.min_size
  parent_rule                = each.value.parent_rule
  protocols                  = each.value.protocols
  rank                       = each.value.rank
  severity                   = each.value.severity
  state                      = each.value.state
  sub_rules                  = each.value.sub_rules
  user_risk_score_levels     = each.value.user_risk_score_levels
  without_content_inspection = each.value.without_content_inspection
  zcc_notifications_enabled  = each.value.zcc_notifications_enabled
  zscaler_incident_receiver  = each.value.zscaler_incident_receiver

  dynamic "auditor" {
    for_each = each.value.auditor == null ? [] : each.value.auditor
    content {
      id = auditor.value.id
    }
  }

  dynamic "departments" {
    for_each = each.value.departments == null ? [] : [each.value.departments]
    content {
      id = departments.value.id
    }
  }

  dynamic "dlp_engines" {
    for_each = each.value.dlp_engines == null ? [] : [each.value.dlp_engines]
    content {
      id = dlp_engines.value.id
    }
  }

  dynamic "excluded_departments" {
    for_each = each.value.excluded_departments == null ? [] : [each.value.excluded_departments]
    content {
      id = excluded_departments.value.id
    }
  }

  dynamic "excluded_domain_profiles" {
    for_each = each.value.excluded_domain_profiles == null ? [] : [each.value.excluded_domain_profiles]
    content {
      id = excluded_domain_profiles.value.id
    }
  }

  dynamic "excluded_groups" {
    for_each = each.value.excluded_groups == null ? [] : [each.value.excluded_groups]
    content {
      id = excluded_groups.value.id
    }
  }

  dynamic "excluded_users" {
    for_each = each.value.excluded_users == null ? [] : [each.value.excluded_users]
    content {
      id = excluded_users.value.id
    }
  }

  dynamic "file_type_categories" {
    for_each = each.value.file_type_categories == null ? [] : [each.value.file_type_categories]
    content {
      id = file_type_categories.value.id
    }
  }

  dynamic "groups" {
    for_each = each.value.groups == null ? [] : [each.value.groups]
    content {
      id = groups.value.id
    }
  }

  dynamic "icap_server" {
    for_each = each.value.icap_server == null ? [] : each.value.icap_server
    content {
      id = icap_server.value.id
    }
  }

  dynamic "included_domain_profiles" {
    for_each = each.value.included_domain_profiles == null ? [] : [each.value.included_domain_profiles]
    content {
      id = included_domain_profiles.value.id
    }
  }

  dynamic "labels" {
    for_each = each.value.labels == null ? [] : [each.value.labels]
    content {
      id = labels.value.id
    }
  }

  dynamic "location_groups" {
    for_each = each.value.location_groups == null ? [] : [each.value.location_groups]
    content {
      id = location_groups.value.id
    }
  }

  dynamic "locations" {
    for_each = each.value.locations == null ? [] : [each.value.locations]
    content {
      id = locations.value.id
    }
  }

  dynamic "notification_template" {
    for_each = each.value.notification_template == null ? [] : each.value.notification_template
    content {
      id = notification_template.value.id
    }
  }

  dynamic "receiver" {
    for_each = each.value.receiver == null ? [] : [each.value.receiver]
    content {
      id   = receiver.value.id
      name = receiver.value.name
      type = receiver.value.type

      dynamic "tenant" {
        for_each = receiver.value.tenant == null ? [] : [receiver.value.tenant]
        content {
          id   = tenant.value.id
          name = tenant.value.name
        }
      }
    }
  }

  dynamic "source_ip_groups" {
    for_each = each.value.source_ip_groups == null ? [] : [each.value.source_ip_groups]
    content {
      id = source_ip_groups.value.id
    }
  }

  dynamic "time_windows" {
    for_each = each.value.time_windows == null ? [] : [each.value.time_windows]
    content {
      id = time_windows.value.id
    }
  }

  dynamic "timeouts" {
    for_each = each.value.timeouts == null ? [] : [each.value.timeouts]
    content {
      create = timeouts.value.create
      update = timeouts.value.update
    }
  }

  dynamic "url_categories" {
    for_each = each.value.url_categories == null ? [] : [each.value.url_categories]
    content {
      id = url_categories.value.id
    }
  }

  dynamic "users" {
    for_each = each.value.users == null ? [] : [each.value.users]
    content {
      id = users.value.id
    }
  }

  dynamic "workload_groups" {
    for_each = each.value.workload_groups == null ? [] : each.value.workload_groups
    content {
      id   = workload_groups.value.id
      name = workload_groups.value.name
    }
  }
}
