# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_dlp_web_rules instances, keyed by a stable identifier."
  type = map(object({
    name                       = string
    order                      = number
    action                     = optional(string)
    cloud_applications         = optional(set(string))
    description                = optional(string)
    dlp_download_scan_enabled  = optional(bool)
    eun_template_id            = optional(number)
    external_auditor_email     = optional(string)
    file_types                 = optional(set(string))
    inspect_http_get_enabled   = optional(bool)
    match_only                 = optional(bool)
    min_size                   = optional(number)
    parent_rule                = optional(number)
    protocols                  = optional(set(string))
    rank                       = optional(number)
    severity                   = optional(string)
    state                      = optional(string)
    sub_rules                  = optional(set(string))
    user_risk_score_levels     = optional(set(string))
    without_content_inspection = optional(bool)
    zcc_notifications_enabled  = optional(bool)
    zscaler_incident_receiver  = optional(bool)
    auditor = optional(set(object({
      id = optional(number)
    })))
    departments = optional(object({
      id = optional(set(number))
    }))
    dlp_engines = optional(object({
      id = optional(set(number))
    }))
    excluded_departments = optional(object({
      id = optional(set(number))
    }))
    excluded_domain_profiles = optional(object({
      id = optional(set(number))
    }))
    excluded_groups = optional(object({
      id = optional(set(number))
    }))
    excluded_users = optional(object({
      id = optional(set(number))
    }))
    file_type_categories = optional(object({
      id = optional(set(number))
    }))
    groups = optional(object({
      id = optional(set(number))
    }))
    icap_server = optional(set(object({
      id = optional(number)
    })))
    included_domain_profiles = optional(object({
      id = optional(set(number))
    }))
    labels = optional(object({
      id = optional(set(number))
    }))
    location_groups = optional(object({
      id = optional(set(number))
    }))
    locations = optional(object({
      id = optional(set(number))
    }))
    notification_template = optional(set(object({
      id = optional(number)
    })))
    receiver = optional(object({
      id   = optional(string)
      name = optional(string)
      type = optional(string)
      tenant = optional(object({
        id   = optional(string)
        name = optional(string)
      }))
    }))
    source_ip_groups = optional(object({
      id = optional(set(number))
    }))
    time_windows = optional(object({
      id = optional(set(number))
    }))
    timeouts = optional(object({
      create = optional(string)
      update = optional(string)
    }))
    url_categories = optional(object({
      id = optional(set(number))
    }))
    users = optional(object({
      id = optional(set(number))
    }))
    workload_groups = optional(set(object({
      id   = optional(number)
      name = optional(string)
    })))
  }))
}
