# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_policy_inspection_rule instances, keyed by a stable identifier."
  type = map(object({
    name                      = string
    action                    = optional(string)
    description               = optional(string)
    microtenant_id            = optional(string)
    operator                  = optional(string)
    policy_set_id             = optional(string)
    zpn_inspection_profile_id = optional(string)
    conditions = optional(list(object({
      operator       = optional(string)
      microtenant_id = optional(string)
      operands = optional(list(object({
        lhs            = optional(string)
        object_type    = optional(string)
        idp_id         = optional(string)
        microtenant_id = optional(string)
        name           = optional(string)
        rhs            = optional(string)
        rhs_list       = optional(set(string))
      })))
    })))
  }))
}
