# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_c2c_ip_ranges" "this" {
  for_each = var.items

  name            = each.value.name
  country_code    = each.value.country_code
  description     = each.value.description
  enabled         = each.value.enabled
  ip_range_begin  = each.value.ip_range_begin
  ip_range_end    = each.value.ip_range_end
  latitude_in_db  = each.value.latitude_in_db
  location        = each.value.location
  location_hint   = each.value.location_hint
  longitude_in_db = each.value.longitude_in_db
  sccm_flag       = each.value.sccm_flag
  subnet_cidr     = each.value.subnet_cidr
}
