# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_c2c_ip_ranges instances, keyed by a stable identifier."
  type = map(object({
    name            = string
    country_code    = optional(string)
    description     = optional(string)
    enabled         = optional(bool)
    ip_range_begin  = optional(string)
    ip_range_end    = optional(string)
    latitude_in_db  = optional(string)
    location        = optional(string)
    location_hint   = optional(string)
    longitude_in_db = optional(string)
    sccm_flag       = optional(bool)
    subnet_cidr     = optional(string)
  }))
}
