# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_pra_console_controller" "this" {
  for_each = var.items

  description    = each.value.description
  enabled        = each.value.enabled
  icon_text      = each.value.icon_text
  microtenant_id = each.value.microtenant_id
  name           = each.value.name

  dynamic "pra_application" {
    for_each = each.value.pra_application == null ? [] : each.value.pra_application
    content {
      id = pra_application.value.id
    }
  }

  dynamic "pra_portals" {
    for_each = each.value.pra_portals == null ? [] : each.value.pra_portals
    content {
      id = pra_portals.value.id
    }
  }
}
