# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_pra_console_controller instances, keyed by a stable identifier."
  type = map(object({
    description    = optional(string)
    enabled        = optional(bool)
    icon_text      = optional(string)
    microtenant_id = optional(string)
    name           = optional(string)
    pra_application = optional(list(object({
      id = optional(string)
    })))
    pra_portals = optional(set(object({
      id = optional(set(string))
    })))
  }))
}
