# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_policy_browser_protection_rule instances, keyed by a stable identifier."
  type = map(object({
    name           = string
    action         = optional(string)
    description    = optional(string)
    microtenant_id = optional(string)
    conditions = optional(set(object({
      operator = optional(string)
      operands = optional(set(object({
        object_type = optional(string)
        values      = optional(set(string))
        entry_values = optional(set(object({
          lhs = optional(string)
          rhs = optional(string)
        })))
      })))
    })))
  }))
}
