# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_auth_settings_urls" "this" {
  for_each = var.items

  urls = each.value.urls
}
