# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_auth_settings_urls instances, keyed by a stable identifier."
  type = map(object({
    urls = optional(set(string))
  }))
}
