# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_sandbox_rules" "this" {
  for_each = var.items

  name                 = each.value.name
  order                = each.value.order
  protocols            = each.value.protocols
  ba_policy_categories = each.value.ba_policy_categories
  ba_rule_action       = each.value.ba_rule_action
  by_threat_score      = each.value.by_threat_score
  description          = each.value.description
  file_types           = each.value.file_types
  first_time_enable    = each.value.first_time_enable
  first_time_operation = each.value.first_time_operation
  ml_action_enabled    = each.value.ml_action_enabled
  rank                 = each.value.rank
  state                = each.value.state
  url_categories       = each.value.url_categories

  dynamic "departments" {
    for_each = each.value.departments == null ? [] : [each.value.departments]
    content {
      id = departments.value.id
    }
  }

  dynamic "groups" {
    for_each = each.value.groups == null ? [] : [each.value.groups]
    content {
      id = groups.value.id
    }
  }

  dynamic "labels" {
    for_each = each.value.labels == null ? [] : [each.value.labels]
    content {
      id = labels.value.id
    }
  }

  dynamic "location_groups" {
    for_each = each.value.location_groups == null ? [] : [each.value.location_groups]
    content {
      id = location_groups.value.id
    }
  }

  dynamic "locations" {
    for_each = each.value.locations == null ? [] : [each.value.locations]
    content {
      id = locations.value.id
    }
  }

  dynamic "timeouts" {
    for_each = each.value.timeouts == null ? [] : [each.value.timeouts]
    content {
      create = timeouts.value.create
      update = timeouts.value.update
    }
  }

  dynamic "users" {
    for_each = each.value.users == null ? [] : [each.value.users]
    content {
      id = users.value.id
    }
  }

  dynamic "zpa_app_segments" {
    for_each = each.value.zpa_app_segments == null ? [] : each.value.zpa_app_segments
    content {
      external_id = zpa_app_segments.value.external_id
      name        = zpa_app_segments.value.name
    }
  }
}
