# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_sandbox_rules instances, keyed by a stable identifier."
  type = map(object({
    name                 = string
    order                = number
    protocols            = set(string)
    ba_policy_categories = optional(set(string))
    ba_rule_action       = optional(string)
    by_threat_score      = optional(number)
    description          = optional(string)
    file_types           = optional(set(string))
    first_time_enable    = optional(bool)
    first_time_operation = optional(string)
    ml_action_enabled    = optional(bool)
    rank                 = optional(number)
    state                = optional(string)
    url_categories       = optional(set(string))
    departments = optional(object({
      id = optional(set(number))
    }))
    groups = optional(object({
      id = optional(set(number))
    }))
    labels = optional(object({
      id = optional(set(number))
    }))
    location_groups = optional(object({
      id = optional(set(number))
    }))
    locations = optional(object({
      id = optional(set(number))
    }))
    timeouts = optional(object({
      create = optional(string)
      update = optional(string)
    }))
    users = optional(object({
      id = optional(set(number))
    }))
    zpa_app_segments = optional(set(object({
      external_id = optional(string)
      name        = optional(string)
    })))
  }))
}
