# GENERATED by tools/gen_env.py for tenant 'zs3' — do not edit.
# Regenerate: make gen-env TENANT=zs3

terraform {
  required_version = ">= 1.5"
  required_providers {
    zcc = {
      source = "zscaler/zcc"
    }
  }
  # backend configured per environment (Plan 5 / operator)
}

provider "zcc" {
  # credentials via env (ZSCALER_*/ZIA_*/ZPA_*); see tools/FETCH.md
}

variable "items" {
  # opaque at the root; the module enforces the strict type.
  type = any
}

module "zcc_trusted_network" {
  source = "../../../modules/zcc_trusted_network"
  items  = var.items
}
