# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_firewall_filtering_network_application_groups" "this" {
  for_each = var.items

  name                 = each.value.name
  description          = each.value.description
  network_applications = each.value.network_applications
}
