# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_firewall_filtering_network_application_groups instances, keyed by a stable identifier."
  type = map(object({
    name                 = string
    description          = optional(string)
    network_applications = optional(set(string))
  }))
}
