# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_lss_config_controller" "this" {
  for_each = var.items


  dynamic "config" {
    for_each = each.value.config == null ? [] : [each.value.config]
    content {
      format          = config.value.format
      lss_host        = config.value.lss_host
      lss_port        = config.value.lss_port
      name            = config.value.name
      source_log_type = config.value.source_log_type
      audit_message   = config.value.audit_message
      description     = config.value.description
      enabled         = config.value.enabled
      filter          = config.value.filter
      use_tls         = config.value.use_tls
    }
  }

  dynamic "connector_groups" {
    for_each = each.value.connector_groups == null ? [] : each.value.connector_groups
    content {
      id = connector_groups.value.id
    }
  }

  dynamic "policy_rule_resource" {
    for_each = each.value.policy_rule_resource == null ? [] : [each.value.policy_rule_resource]
    content {
      name                      = policy_rule_resource.value.name
      action                    = policy_rule_resource.value.action
      action_id                 = policy_rule_resource.value.action_id
      bypass_default_rule       = policy_rule_resource.value.bypass_default_rule
      custom_msg                = policy_rule_resource.value.custom_msg
      default_rule              = policy_rule_resource.value.default_rule
      description               = policy_rule_resource.value.description
      lss_default_rule          = policy_rule_resource.value.lss_default_rule
      microtenant_id            = policy_rule_resource.value.microtenant_id
      operator                  = policy_rule_resource.value.operator
      policy_set_id             = policy_rule_resource.value.policy_set_id
      policy_type               = policy_rule_resource.value.policy_type
      priority                  = policy_rule_resource.value.priority
      reauth_default_rule       = policy_rule_resource.value.reauth_default_rule
      reauth_idle_timeout       = policy_rule_resource.value.reauth_idle_timeout
      reauth_timeout            = policy_rule_resource.value.reauth_timeout
      zpn_cbi_profile_id        = policy_rule_resource.value.zpn_cbi_profile_id
      zpn_inspection_profile_id = policy_rule_resource.value.zpn_inspection_profile_id
      zpn_isolation_profile_id  = policy_rule_resource.value.zpn_isolation_profile_id

      dynamic "conditions" {
        for_each = policy_rule_resource.value.conditions == null ? [] : policy_rule_resource.value.conditions
        content {
          operator = conditions.value.operator

          dynamic "operands" {
            for_each = conditions.value.operands == null ? [] : conditions.value.operands
            content {
              object_type = operands.value.object_type
              values      = operands.value.values

              dynamic "entry_values" {
                for_each = operands.value.entry_values == null ? [] : operands.value.entry_values
                content {
                  lhs = entry_values.value.lhs
                  rhs = entry_values.value.rhs
                }
              }
            }
          }
        }
      }
    }
  }
}
