# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_lss_config_controller instances, keyed by a stable identifier."
  type = map(object({
    config = optional(object({
      format          = optional(string)
      lss_host        = optional(string)
      lss_port        = optional(string)
      name            = optional(string)
      source_log_type = optional(string)
      audit_message   = optional(string)
      description     = optional(string)
      enabled         = optional(bool)
      filter          = optional(set(string))
      use_tls         = optional(bool)
    }))
    connector_groups = optional(set(object({
      id = optional(list(string))
    })))
    policy_rule_resource = optional(object({
      name                      = optional(string)
      action                    = optional(string)
      action_id                 = optional(string)
      bypass_default_rule       = optional(bool)
      custom_msg                = optional(string)
      default_rule              = optional(bool)
      description               = optional(string)
      lss_default_rule          = optional(bool)
      microtenant_id            = optional(string)
      operator                  = optional(string)
      policy_set_id             = optional(string)
      policy_type               = optional(string)
      priority                  = optional(string)
      reauth_default_rule       = optional(bool)
      reauth_idle_timeout       = optional(string)
      reauth_timeout            = optional(string)
      zpn_cbi_profile_id        = optional(string)
      zpn_inspection_profile_id = optional(string)
      zpn_isolation_profile_id  = optional(string)
      conditions = optional(list(object({
        operator = optional(string)
        operands = optional(list(object({
          object_type = optional(string)
          values      = optional(set(string))
          entry_values = optional(list(object({
            lhs = optional(string)
            rhs = optional(string)
          })))
        })))
      })))
    }))
  }))
}
