# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_application_server instances, keyed by a stable identifier."
  type = map(object({
    address              = string
    name                 = string
    app_server_group_ids = optional(set(string))
    config_space         = optional(string)
    description          = optional(string)
    enabled              = optional(bool)
    microtenant_id       = optional(string)
  }))
}
