# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

terraform {
  required_providers {
    zpa = {
      source  = "zscaler/zpa"
      version = "4.4.4"
    }
  }
}
