# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_cloud_application_instance" "this" {
  for_each = var.items

  instance_type = each.value.instance_type
  name          = each.value.name

  dynamic "instance_identifiers" {
    for_each = each.value.instance_identifiers == null ? [] : each.value.instance_identifiers
    content {
      identifier_type          = instance_identifiers.value.identifier_type
      instance_identifier      = instance_identifiers.value.instance_identifier
      instance_identifier_name = instance_identifiers.value.instance_identifier_name
    }
  }
}
