# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_cloud_application_instance instances, keyed by a stable identifier."
  type = map(object({
    instance_type = optional(string)
    name          = optional(string)
    instance_identifiers = optional(list(object({
      identifier_type          = optional(string)
      instance_identifier      = optional(string)
      instance_identifier_name = optional(string)
    })))
  }))
}
