# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_tag_key" "this" {
  for_each = var.items

  name           = each.value.name
  namespace_id   = each.value.namespace_id
  description    = each.value.description
  enabled        = each.value.enabled
  microtenant_id = each.value.microtenant_id
  origin         = each.value.origin
  type           = each.value.type

  dynamic "tag_values" {
    for_each = each.value.tag_values == null ? [] : each.value.tag_values
    content {
      name = tag_values.value.name
    }
  }
}
