# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_policy_portal_access_rule" "this" {
  for_each = var.items

  name           = each.value.name
  action         = each.value.action
  description    = each.value.description
  microtenant_id = each.value.microtenant_id

  dynamic "conditions" {
    for_each = each.value.conditions == null ? [] : each.value.conditions
    content {
      operator = conditions.value.operator

      dynamic "operands" {
        for_each = conditions.value.operands == null ? [] : conditions.value.operands
        content {
          object_type = operands.value.object_type
          values      = operands.value.values

          dynamic "entry_values" {
            for_each = operands.value.entry_values == null ? [] : operands.value.entry_values
            content {
              lhs = entry_values.value.lhs
              rhs = entry_values.value.rhs
            }
          }
        }
      }
    }
  }

  dynamic "privileged_portal_capabilities" {
    for_each = each.value.privileged_portal_capabilities == null ? [] : [each.value.privileged_portal_capabilities]
    content {
      access_uninspected_file = privileged_portal_capabilities.value.access_uninspected_file
      delete_file             = privileged_portal_capabilities.value.delete_file
      request_approvals       = privileged_portal_capabilities.value.request_approvals
      review_approvals        = privileged_portal_capabilities.value.review_approvals
    }
  }
}
