# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_casb_dlp_rules" "this" {
  for_each = var.items

  order                           = each.value.order
  action                          = each.value.action
  bucket_owner                    = each.value.bucket_owner
  collaboration_scope             = each.value.collaboration_scope
  components                      = each.value.components
  content_location                = each.value.content_location
  description                     = each.value.description
  domains                         = each.value.domains
  external_auditor_email          = each.value.external_auditor_email
  file_types                      = each.value.file_types
  include_criteria_domain_profile = each.value.include_criteria_domain_profile
  include_email_recipient_profile = each.value.include_email_recipient_profile
  include_entity_groups           = each.value.include_entity_groups
  name                            = each.value.name
  quarantine_location             = each.value.quarantine_location
  rank                            = each.value.rank
  recipient                       = each.value.recipient
  severity                        = each.value.severity
  state                           = each.value.state
  type                            = each.value.type
  watermark_delete_old_version    = each.value.watermark_delete_old_version
  without_content_inspection      = each.value.without_content_inspection

  dynamic "auditor_notification" {
    for_each = each.value.auditor_notification == null ? [] : each.value.auditor_notification
    content {
      id = auditor_notification.value.id
    }
  }

  dynamic "buckets" {
    for_each = each.value.buckets == null ? [] : [each.value.buckets]
    content {
      id = buckets.value.id
    }
  }

  dynamic "casb_email_label" {
    for_each = each.value.casb_email_label == null ? [] : each.value.casb_email_label
    content {
      id = casb_email_label.value.id
    }
  }

  dynamic "casb_tombstone_template" {
    for_each = each.value.casb_tombstone_template == null ? [] : each.value.casb_tombstone_template
    content {
      id = casb_tombstone_template.value.id
    }
  }

  dynamic "cloud_app_tenants" {
    for_each = each.value.cloud_app_tenants == null ? [] : [each.value.cloud_app_tenants]
    content {
      id = cloud_app_tenants.value.id
    }
  }

  dynamic "criteria_domain_profiles" {
    for_each = each.value.criteria_domain_profiles == null ? [] : [each.value.criteria_domain_profiles]
    content {
      id = criteria_domain_profiles.value.id
    }
  }

  dynamic "departments" {
    for_each = each.value.departments == null ? [] : [each.value.departments]
    content {
      id = departments.value.id
    }
  }

  dynamic "dlp_engines" {
    for_each = each.value.dlp_engines == null ? [] : [each.value.dlp_engines]
    content {
      id = dlp_engines.value.id
    }
  }

  dynamic "email_recipient_profiles" {
    for_each = each.value.email_recipient_profiles == null ? [] : [each.value.email_recipient_profiles]
    content {
      id = email_recipient_profiles.value.id
    }
  }

  dynamic "entity_groups" {
    for_each = each.value.entity_groups == null ? [] : [each.value.entity_groups]
    content {
      id = entity_groups.value.id
    }
  }

  dynamic "excluded_domain_profiles" {
    for_each = each.value.excluded_domain_profiles == null ? [] : [each.value.excluded_domain_profiles]
    content {
      id = excluded_domain_profiles.value.id
    }
  }

  dynamic "groups" {
    for_each = each.value.groups == null ? [] : [each.value.groups]
    content {
      id = groups.value.id
    }
  }

  dynamic "included_domain_profiles" {
    for_each = each.value.included_domain_profiles == null ? [] : [each.value.included_domain_profiles]
    content {
      id = included_domain_profiles.value.id
    }
  }

  dynamic "labels" {
    for_each = each.value.labels == null ? [] : [each.value.labels]
    content {
      id = labels.value.id
    }
  }

  dynamic "object_types" {
    for_each = each.value.object_types == null ? [] : [each.value.object_types]
    content {
      id = object_types.value.id
    }
  }

  dynamic "receiver" {
    for_each = each.value.receiver == null ? [] : [each.value.receiver]
    content {
      id   = receiver.value.id
      name = receiver.value.name
      type = receiver.value.type

      dynamic "tenant" {
        for_each = receiver.value.tenant == null ? [] : [receiver.value.tenant]
        content {
          id   = tenant.value.id
          name = tenant.value.name
        }
      }
    }
  }

  dynamic "redaction_profile" {
    for_each = each.value.redaction_profile == null ? [] : each.value.redaction_profile
    content {
      id = redaction_profile.value.id
    }
  }

  dynamic "tag" {
    for_each = each.value.tag == null ? [] : each.value.tag
    content {
      id = tag.value.id
    }
  }

  dynamic "timeouts" {
    for_each = each.value.timeouts == null ? [] : [each.value.timeouts]
    content {
      create = timeouts.value.create
      update = timeouts.value.update
    }
  }

  dynamic "users" {
    for_each = each.value.users == null ? [] : [each.value.users]
    content {
      id = users.value.id
    }
  }

  dynamic "watermark_profile" {
    for_each = each.value.watermark_profile == null ? [] : each.value.watermark_profile
    content {
      id = watermark_profile.value.id
    }
  }

  dynamic "zscaler_incident_receiver" {
    for_each = each.value.zscaler_incident_receiver == null ? [] : each.value.zscaler_incident_receiver
    content {
      id = zscaler_incident_receiver.value.id
    }
  }
}
