# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_casb_dlp_rules instances, keyed by a stable identifier."
  type = map(object({
    order                           = number
    action                          = optional(string)
    bucket_owner                    = optional(string)
    collaboration_scope             = optional(set(string))
    components                      = optional(set(string))
    content_location                = optional(string)
    description                     = optional(string)
    domains                         = optional(set(string))
    external_auditor_email          = optional(string)
    file_types                      = optional(set(string))
    include_criteria_domain_profile = optional(bool)
    include_email_recipient_profile = optional(bool)
    include_entity_groups           = optional(bool)
    name                            = optional(string)
    quarantine_location             = optional(string)
    rank                            = optional(number)
    recipient                       = optional(string)
    severity                        = optional(string)
    state                           = optional(string)
    type                            = optional(string)
    watermark_delete_old_version    = optional(bool)
    without_content_inspection      = optional(bool)
    auditor_notification = optional(set(object({
      id = optional(number)
    })))
    buckets = optional(object({
      id = optional(set(number))
    }))
    casb_email_label = optional(set(object({
      id = optional(number)
    })))
    casb_tombstone_template = optional(set(object({
      id = optional(number)
    })))
    cloud_app_tenants = optional(object({
      id = optional(set(number))
    }))
    criteria_domain_profiles = optional(object({
      id = optional(set(number))
    }))
    departments = optional(object({
      id = optional(set(number))
    }))
    dlp_engines = optional(object({
      id = optional(set(number))
    }))
    email_recipient_profiles = optional(object({
      id = optional(set(number))
    }))
    entity_groups = optional(object({
      id = optional(set(number))
    }))
    excluded_domain_profiles = optional(object({
      id = optional(set(number))
    }))
    groups = optional(object({
      id = optional(set(number))
    }))
    included_domain_profiles = optional(object({
      id = optional(set(number))
    }))
    labels = optional(object({
      id = optional(set(number))
    }))
    object_types = optional(object({
      id = optional(set(number))
    }))
    receiver = optional(object({
      id   = optional(string)
      name = optional(string)
      type = optional(string)
      tenant = optional(object({
        id   = optional(string)
        name = optional(string)
      }))
    }))
    redaction_profile = optional(set(object({
      id = optional(number)
    })))
    tag = optional(set(object({
      id = optional(number)
    })))
    timeouts = optional(object({
      create = optional(string)
      update = optional(string)
    }))
    users = optional(object({
      id = optional(set(number))
    }))
    watermark_profile = optional(set(object({
      id = optional(number)
    })))
    zscaler_incident_receiver = optional(set(object({
      id = optional(number)
    })))
  }))
}
