# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_traffic_forwarding_vpn_credentials" "this" {
  for_each = var.items

  comments       = each.value.comments
  fqdn           = each.value.fqdn
  ip_address     = each.value.ip_address
  pre_shared_key = each.value.pre_shared_key
  type           = each.value.type
}
