# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_traffic_forwarding_vpn_credentials instances, keyed by a stable identifier."
  type = map(object({
    comments       = optional(string)
    fqdn           = optional(string)
    ip_address     = optional(string)
    pre_shared_key = optional(string)
    type           = optional(string)
  }))
}
