# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_microtenant_controller" "this" {
  for_each = var.items

  name                         = each.value.name
  criteria_attribute           = each.value.criteria_attribute
  criteria_attribute_values    = each.value.criteria_attribute_values
  description                  = each.value.description
  enabled                      = each.value.enabled
  privileged_approvals_enabled = each.value.privileged_approvals_enabled
}
