# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_microtenant_controller instances, keyed by a stable identifier."
  type = map(object({
    name                         = string
    criteria_attribute           = optional(string)
    criteria_attribute_values    = optional(set(string))
    description                  = optional(string)
    enabled                      = optional(bool)
    privileged_approvals_enabled = optional(bool)
  }))
}
