# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_cloud_browser_isolation_banner" "this" {
  for_each = var.items

  banner             = each.value.banner
  logo               = each.value.logo
  name               = each.value.name
  notification_text  = each.value.notification_text
  notification_title = each.value.notification_title
  persist            = each.value.persist
  primary_color      = each.value.primary_color
  text_color         = each.value.text_color
}
