# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_cloud_browser_isolation_banner instances, keyed by a stable identifier."
  type = map(object({
    banner             = optional(bool)
    logo               = optional(string)
    name               = optional(string)
    notification_text  = optional(string)
    notification_title = optional(string)
    persist            = optional(bool)
    primary_color      = optional(string)
    text_color         = optional(string)
  }))
}
