# GENERATED by tools/gen_module.py from schemas/provider/zcc.json — do not edit.
# Regenerate: make generate

resource "zcc_zia_posture" "this" {
  for_each = var.items

  name                  = each.value.name
  platform              = each.value.platform
  high_trust_criteria   = each.value.high_trust_criteria
  low_trust_criteria    = each.value.low_trust_criteria
  medium_trust_criteria = each.value.medium_trust_criteria
}
