# GENERATED by tools/gen_module.py from schemas/provider/zcc.json — do not edit.
# Regenerate: make generate

output "items" {
  description = "All managed zcc_zia_posture resources, keyed as in var.items."
  value       = zcc_zia_posture.this
}

output "name_to_id" {
  description = "Map of resource name to provider-assigned id."
  value       = { for k, v in zcc_zia_posture.this : v.name => v.id }
}
