# GENERATED by tools/gen_module.py from schemas/provider/zcc.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zcc_zia_posture instances, keyed by a stable identifier."
  type = map(object({
    name     = string
    platform = string
    high_trust_criteria = optional(object({
      cs = optional(list(object({
        cn = optional(list(object({
          id   = optional(string)
          name = optional(string)
          udid = optional(string)
        })))
      })))
    }))
    low_trust_criteria = optional(object({
      cs = optional(list(object({
        cn = optional(list(object({
          id   = optional(string)
          name = optional(string)
          udid = optional(string)
        })))
      })))
    }))
    medium_trust_criteria = optional(object({
      cs = optional(list(object({
        cn = optional(list(object({
          id   = optional(string)
          name = optional(string)
          udid = optional(string)
        })))
      })))
    }))
  }))
}
