# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_email_profile" "this" {
  for_each = var.items

  name        = each.value.name
  description = each.value.description
  emails      = each.value.emails
}
