# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_email_profile instances, keyed by a stable identifier."
  type = map(object({
    name        = string
    description = optional(string)
    emails      = optional(set(string))
  }))
}
