# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_forwarding_control_zpa_gateway" "this" {
  for_each = var.items

  name        = each.value.name
  description = each.value.description
  type        = each.value.type

  dynamic "zpa_app_segments" {
    for_each = each.value.zpa_app_segments == null ? [] : each.value.zpa_app_segments
    content {
      external_id = zpa_app_segments.value.external_id
      name        = zpa_app_segments.value.name
    }
  }

  dynamic "zpa_server_group" {
    for_each = each.value.zpa_server_group == null ? [] : [each.value.zpa_server_group]
    content {
      external_id = zpa_server_group.value.external_id
      name        = zpa_server_group.value.name
    }
  }
}
