# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_forwarding_control_zpa_gateway instances, keyed by a stable identifier."
  type = map(object({
    name        = string
    description = optional(string)
    type        = optional(string)
    zpa_app_segments = optional(set(object({
      external_id = optional(string)
      name        = optional(string)
    })))
    zpa_server_group = optional(object({
      external_id = optional(string)
      name        = optional(string)
    }))
  }))
}
