# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_virtual_service_edge_node" "this" {
  for_each = var.items

  cluster_name                     = each.value.cluster_name
  default_gateway                  = each.value.default_gateway
  deployment_mode                  = each.value.deployment_mode
  establish_support_tunnel_enabled = each.value.establish_support_tunnel_enabled
  in_production                    = each.value.in_production
  ip_address                       = each.value.ip_address
  ip_sec_enabled                   = each.value.ip_sec_enabled
  load_balancer_ip_address         = each.value.load_balancer_ip_address
  name                             = each.value.name
  on_demand_support_tunnel_enabled = each.value.on_demand_support_tunnel_enabled
  status                           = each.value.status
  subnet_mask                      = each.value.subnet_mask
  type                             = each.value.type
  vzen_sku_type                    = each.value.vzen_sku_type
}
