# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_virtual_service_edge_node instances, keyed by a stable identifier."
  type = map(object({
    cluster_name                     = optional(string)
    default_gateway                  = optional(string)
    deployment_mode                  = optional(string)
    establish_support_tunnel_enabled = optional(bool)
    in_production                    = optional(bool)
    ip_address                       = optional(string)
    ip_sec_enabled                   = optional(bool)
    load_balancer_ip_address         = optional(string)
    name                             = optional(string)
    on_demand_support_tunnel_enabled = optional(bool)
    status                           = optional(string)
    subnet_mask                      = optional(string)
    type                             = optional(string)
    vzen_sku_type                    = optional(string)
  }))
}
