# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_nss_server" "this" {
  for_each = var.items

  name        = each.value.name
  icap_svr_id = each.value.icap_svr_id
  status      = each.value.status
  type        = each.value.type
}
