# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_nss_server instances, keyed by a stable identifier."
  type = map(object({
    name        = string
    icap_svr_id = optional(number)
    status      = optional(string)
    type        = optional(string)
  }))
}
