# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_zia_cloud_config" "this" {
  for_each = var.items

  zia_cloud_domain          = each.value.zia_cloud_domain
  zia_cloud_service_api_key = each.value.zia_cloud_service_api_key
  zia_password              = each.value.zia_password
  zia_sandbox_api_token     = each.value.zia_sandbox_api_token
  zia_username              = each.value.zia_username
}
