# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_zia_cloud_config instances, keyed by a stable identifier."
  type = map(object({
    zia_cloud_domain          = string
    zia_cloud_service_api_key = string
    zia_password              = string
    zia_sandbox_api_token     = string
    zia_username              = string
  }))
}
