# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_pra_credential_pool" "this" {
  for_each = var.items

  credential_type = each.value.credential_type
  microtenant_id  = each.value.microtenant_id
  name            = each.value.name

  dynamic "credentials" {
    for_each = each.value.credentials == null ? [] : each.value.credentials
    content {
      id = credentials.value.id
    }
  }
}
