# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

output "items" {
  description = "All managed zpa_pra_credential_pool resources, keyed as in var.items."
  value       = zpa_pra_credential_pool.this
}
