# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_pra_credential_pool instances, keyed by a stable identifier."
  type = map(object({
    credential_type = optional(string)
    microtenant_id  = optional(string)
    name            = optional(string)
    credentials = optional(set(object({
      id = optional(set(string))
    })))
  }))
}
