# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_browser_control_policy" "this" {
  for_each = var.items

  allow_all_browsers                 = each.value.allow_all_browsers
  blocked_chrome_versions            = each.value.blocked_chrome_versions
  blocked_firefox_versions           = each.value.blocked_firefox_versions
  blocked_internet_explorer_versions = each.value.blocked_internet_explorer_versions
  blocked_opera_versions             = each.value.blocked_opera_versions
  blocked_safari_versions            = each.value.blocked_safari_versions
  bypass_all_browsers                = each.value.bypass_all_browsers
  bypass_applications                = each.value.bypass_applications
  bypass_plugins                     = each.value.bypass_plugins
  enable_smart_browser_isolation     = each.value.enable_smart_browser_isolation
  enable_warnings                    = each.value.enable_warnings
  plugin_check_frequency             = each.value.plugin_check_frequency

  dynamic "smart_isolation_groups" {
    for_each = each.value.smart_isolation_groups == null ? [] : [each.value.smart_isolation_groups]
    content {
      id = smart_isolation_groups.value.id
    }
  }

  dynamic "smart_isolation_profile" {
    for_each = each.value.smart_isolation_profile == null ? [] : [each.value.smart_isolation_profile]
    content {
      id   = smart_isolation_profile.value.id
      name = smart_isolation_profile.value.name
      url  = smart_isolation_profile.value.url
    }
  }

  dynamic "smart_isolation_users" {
    for_each = each.value.smart_isolation_users == null ? [] : [each.value.smart_isolation_users]
    content {
      id = smart_isolation_users.value.id
    }
  }
}
