# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_browser_control_policy instances, keyed by a stable identifier."
  type = map(object({
    allow_all_browsers                 = optional(bool)
    blocked_chrome_versions            = optional(set(string))
    blocked_firefox_versions           = optional(set(string))
    blocked_internet_explorer_versions = optional(set(string))
    blocked_opera_versions             = optional(set(string))
    blocked_safari_versions            = optional(set(string))
    bypass_all_browsers                = optional(bool)
    bypass_applications                = optional(set(string))
    bypass_plugins                     = optional(set(string))
    enable_smart_browser_isolation     = optional(bool)
    enable_warnings                    = optional(bool)
    plugin_check_frequency             = optional(string)
    smart_isolation_groups = optional(object({
      id = optional(set(number))
    }))
    smart_isolation_profile = optional(object({
      id   = optional(string)
      name = optional(string)
      url  = optional(string)
    }))
    smart_isolation_users = optional(object({
      id = optional(set(number))
    }))
  }))
}
