# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_forwarding_control_proxies" "this" {
  for_each = var.items

  address                  = each.value.address
  base64_encode_xau_header = each.value.base64_encode_xau_header
  description              = each.value.description
  insert_xau_header        = each.value.insert_xau_header
  name                     = each.value.name
  port                     = each.value.port
  type                     = each.value.type

  dynamic "cert" {
    for_each = each.value.cert == null ? [] : each.value.cert
    content {
      id = cert.value.id
    }
  }
}
