# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_forwarding_control_proxies instances, keyed by a stable identifier."
  type = map(object({
    address                  = optional(string)
    base64_encode_xau_header = optional(bool)
    description              = optional(string)
    insert_xau_header        = optional(bool)
    name                     = optional(string)
    port                     = optional(number)
    type                     = optional(string)
    cert = optional(set(object({
      id = optional(number)
    })))
  }))
}
