# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_inspection_profile" "this" {
  for_each = var.items

  api_profile                           = each.value.api_profile
  associate_all_controls                = each.value.associate_all_controls
  common_global_override_actions_config = each.value.common_global_override_actions_config
  description                           = each.value.description
  global_control_actions                = each.value.global_control_actions
  name                                  = each.value.name
  override_action                       = each.value.override_action
  paranoia_level                        = each.value.paranoia_level
  predefined_controls_version           = each.value.predefined_controls_version
  zs_defined_control_choice             = each.value.zs_defined_control_choice

  dynamic "controls_info" {
    for_each = each.value.controls_info == null ? [] : each.value.controls_info
    content {
      control_type = controls_info.value.control_type
    }
  }

  dynamic "custom_controls" {
    for_each = each.value.custom_controls == null ? [] : each.value.custom_controls
    content {
      id           = custom_controls.value.id
      action       = custom_controls.value.action
      action_value = custom_controls.value.action_value
    }
  }

  dynamic "predefined_api_controls" {
    for_each = each.value.predefined_api_controls == null ? [] : each.value.predefined_api_controls
    content {
      action       = predefined_api_controls.value.action
      action_value = predefined_api_controls.value.action_value
      id           = predefined_api_controls.value.id
    }
  }

  dynamic "predefined_controls" {
    for_each = each.value.predefined_controls == null ? [] : each.value.predefined_controls
    content {
      action       = predefined_controls.value.action
      action_value = predefined_controls.value.action_value
      id           = predefined_controls.value.id
    }
  }

  dynamic "threat_labz_controls" {
    for_each = each.value.threat_labz_controls == null ? [] : each.value.threat_labz_controls
    content {
      action       = threat_labz_controls.value.action
      action_value = threat_labz_controls.value.action_value
      id           = threat_labz_controls.value.id
    }
  }

  dynamic "websocket_controls" {
    for_each = each.value.websocket_controls == null ? [] : each.value.websocket_controls
    content {
      action       = websocket_controls.value.action
      action_value = websocket_controls.value.action_value
      id           = websocket_controls.value.id
    }
  }
}
