# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_inspection_profile instances, keyed by a stable identifier."
  type = map(object({
    api_profile                           = optional(bool)
    associate_all_controls                = optional(bool)
    common_global_override_actions_config = optional(map(string))
    description                           = optional(string)
    global_control_actions                = optional(set(string))
    name                                  = optional(string)
    override_action                       = optional(string)
    paranoia_level                        = optional(string)
    predefined_controls_version           = optional(string)
    zs_defined_control_choice             = optional(string)
    controls_info = optional(set(object({
      control_type = optional(string)
    })))
    custom_controls = optional(set(object({
      id           = optional(string)
      action       = optional(string)
      action_value = optional(string)
    })))
    predefined_api_controls = optional(set(object({
      action       = optional(string)
      action_value = optional(string)
      id           = optional(string)
    })))
    predefined_controls = optional(set(object({
      action       = optional(string)
      action_value = optional(string)
      id           = optional(string)
    })))
    threat_labz_controls = optional(list(object({
      action       = optional(string)
      action_value = optional(string)
      id           = optional(string)
    })))
    websocket_controls = optional(list(object({
      action       = optional(string)
      action_value = optional(string)
      id           = optional(string)
    })))
  }))
}
