# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_advanced_settings" "this" {
  for_each = var.items

  api_session_timeout                                            = each.value.api_session_timeout
  auth_bypass_apps                                               = each.value.auth_bypass_apps
  auth_bypass_url_categories                                     = each.value.auth_bypass_url_categories
  auth_bypass_urls                                               = each.value.auth_bypass_urls
  basic_bypass_apps                                              = each.value.basic_bypass_apps
  basic_bypass_url_categories                                    = each.value.basic_bypass_url_categories
  block_connect_host_sni_mismatch                                = each.value.block_connect_host_sni_mismatch
  block_domain_fronting_apps                                     = each.value.block_domain_fronting_apps
  block_domain_fronting_on_host_header                           = each.value.block_domain_fronting_on_host_header
  block_http_tunnel_on_non_http_ports                            = each.value.block_http_tunnel_on_non_http_ports
  block_non_compliant_http_request_on_http_ports                 = each.value.block_non_compliant_http_request_on_http_ports
  block_non_http_on_http_port_enabled                            = each.value.block_non_http_on_http_port_enabled
  cascade_url_filtering                                          = each.value.cascade_url_filtering
  digest_auth_bypass_apps                                        = each.value.digest_auth_bypass_apps
  digest_auth_bypass_url_categories                              = each.value.digest_auth_bypass_url_categories
  digest_auth_bypass_urls                                        = each.value.digest_auth_bypass_urls
  dns_resolution_on_transparent_proxy_apps                       = each.value.dns_resolution_on_transparent_proxy_apps
  dns_resolution_on_transparent_proxy_exempt_apps                = each.value.dns_resolution_on_transparent_proxy_exempt_apps
  dns_resolution_on_transparent_proxy_exempt_url_categories      = each.value.dns_resolution_on_transparent_proxy_exempt_url_categories
  dns_resolution_on_transparent_proxy_exempt_urls                = each.value.dns_resolution_on_transparent_proxy_exempt_urls
  dns_resolution_on_transparent_proxy_ipv6_apps                  = each.value.dns_resolution_on_transparent_proxy_ipv6_apps
  dns_resolution_on_transparent_proxy_ipv6_exempt_apps           = each.value.dns_resolution_on_transparent_proxy_ipv6_exempt_apps
  dns_resolution_on_transparent_proxy_ipv6_exempt_url_categories = each.value.dns_resolution_on_transparent_proxy_ipv6_exempt_url_categories
  dns_resolution_on_transparent_proxy_ipv6_url_categories        = each.value.dns_resolution_on_transparent_proxy_ipv6_url_categories
  dns_resolution_on_transparent_proxy_url_categories             = each.value.dns_resolution_on_transparent_proxy_url_categories
  dns_resolution_on_transparent_proxy_urls                       = each.value.dns_resolution_on_transparent_proxy_urls
  domain_fronting_bypass_url_categories                          = each.value.domain_fronting_bypass_url_categories
  dynamic_user_risk_enabled                                      = each.value.dynamic_user_risk_enabled
  ecs_for_all_enabled                                            = each.value.ecs_for_all_enabled
  enable_admin_rank_access                                       = each.value.enable_admin_rank_access
  enable_dns_resolution_on_transparent_proxy                     = each.value.enable_dns_resolution_on_transparent_proxy
  enable_evaluate_policy_on_global_ssl_bypass                    = each.value.enable_evaluate_policy_on_global_ssl_bypass
  enable_ipv6_dns_optimization_on_all_transparent_proxy          = each.value.enable_ipv6_dns_optimization_on_all_transparent_proxy
  enable_ipv6_dns_resolution_on_transparent_proxy                = each.value.enable_ipv6_dns_resolution_on_transparent_proxy
  enable_office365                                               = each.value.enable_office365
  enable_policy_for_unauthenticated_traffic                      = each.value.enable_policy_for_unauthenticated_traffic
  enforce_surrogate_ip_for_windows_app                           = each.value.enforce_surrogate_ip_for_windows_app
  http2_nonbrowser_traffic_enabled                               = each.value.http2_nonbrowser_traffic_enabled
  http_range_header_remove_url_categories                        = each.value.http_range_header_remove_url_categories
  kerberos_bypass_apps                                           = each.value.kerberos_bypass_apps
  kerberos_bypass_url_categories                                 = each.value.kerberos_bypass_url_categories
  kerberos_bypass_urls                                           = each.value.kerberos_bypass_urls
  log_internal_ip                                                = each.value.log_internal_ip
  prefer_sni_over_conn_host                                      = each.value.prefer_sni_over_conn_host
  prefer_sni_over_conn_host_apps                                 = each.value.prefer_sni_over_conn_host_apps
  sipa_xff_header_enabled                                        = each.value.sipa_xff_header_enabled
  sni_dns_optimization_bypass_url_categories                     = each.value.sni_dns_optimization_bypass_url_categories
  track_http_tunnel_on_http_ports                                = each.value.track_http_tunnel_on_http_ports
  ui_session_timeout                                             = each.value.ui_session_timeout
  zscaler_client_connector_1_and_pac_road_warrior_in_firewall    = each.value.zscaler_client_connector_1_and_pac_road_warrior_in_firewall
}
