# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

output "items" {
  description = "All managed zpa_service_edge_assistant_schedule resources, keyed as in var.items."
  value       = zpa_service_edge_assistant_schedule.this
}
