# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_service_edge_assistant_schedule instances, keyed by a stable identifier."
  type = map(object({
    customer_id        = optional(string)
    delete_disabled    = optional(bool)
    enabled            = optional(bool)
    frequency          = optional(string)
    frequency_interval = optional(string)
  }))
}
