# GENERATED by tools/gen_env.py for tenant 'demo' — do not edit.
# Regenerate: make gen-env TENANT=demo

terraform {
  required_version = ">= 1.5"
  required_providers {
    zpa = {
      source = "zscaler/zpa"
    }
  }
  # local state — opt into remote state with
  # make gen-env TENANT=demo BACKEND=azurerm
}

provider "zpa" {
  # credentials via env (ZSCALER_*/ZIA_*/ZPA_*); see tools/FETCH.md
}

variable "items" {
  # opaque at the root; the module enforces the strict type.
  type = any
}

module "zpa_server_group" {
  source = "../../../modules/zpa_server_group"
  items  = var.items
}
