# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_bandwidth_classes_file_size" "this" {
  for_each = var.items

  file_size = each.value.file_size
  name      = each.value.name
  type      = each.value.type
}
