# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_bandwidth_control_rule" "this" {
  for_each = var.items

  order         = each.value.order
  protocols     = each.value.protocols
  description   = each.value.description
  max_bandwidth = each.value.max_bandwidth
  min_bandwidth = each.value.min_bandwidth
  name          = each.value.name
  rank          = each.value.rank
  state         = each.value.state

  dynamic "bandwidth_classes" {
    for_each = each.value.bandwidth_classes == null ? [] : [each.value.bandwidth_classes]
    content {
      id = bandwidth_classes.value.id
    }
  }

  dynamic "labels" {
    for_each = each.value.labels == null ? [] : [each.value.labels]
    content {
      id = labels.value.id
    }
  }

  dynamic "location_groups" {
    for_each = each.value.location_groups == null ? [] : [each.value.location_groups]
    content {
      id = location_groups.value.id
    }
  }

  dynamic "locations" {
    for_each = each.value.locations == null ? [] : [each.value.locations]
    content {
      id = locations.value.id
    }
  }

  dynamic "time_windows" {
    for_each = each.value.time_windows == null ? [] : [each.value.time_windows]
    content {
      id = time_windows.value.id
    }
  }
}
