# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_bandwidth_control_rule instances, keyed by a stable identifier."
  type = map(object({
    order         = number
    protocols     = set(string)
    description   = optional(string)
    max_bandwidth = optional(number)
    min_bandwidth = optional(number)
    name          = optional(string)
    rank          = optional(number)
    state         = optional(string)
    bandwidth_classes = optional(object({
      id = optional(set(number))
    }))
    labels = optional(object({
      id = optional(set(number))
    }))
    location_groups = optional(object({
      id = optional(set(number))
    }))
    locations = optional(object({
      id = optional(set(number))
    }))
    time_windows = optional(object({
      id = optional(set(number))
    }))
  }))
}
