# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_firewall_dns_rule" "this" {
  for_each = var.items

  name                       = each.value.name
  order                      = each.value.order
  action                     = each.value.action
  applications               = each.value.applications
  block_response_code        = each.value.block_response_code
  capture_pcap               = each.value.capture_pcap
  default_dns_rule_name_used = each.value.default_dns_rule_name_used
  default_rule               = each.value.default_rule
  description                = each.value.description
  dest_addresses             = each.value.dest_addresses
  dest_countries             = each.value.dest_countries
  dest_ip_categories         = each.value.dest_ip_categories
  dns_rule_request_types     = each.value.dns_rule_request_types
  is_web_eun_enabled         = each.value.is_web_eun_enabled
  predefined                 = each.value.predefined
  protocols                  = each.value.protocols
  rank                       = each.value.rank
  redirect_ip                = each.value.redirect_ip
  res_categories             = each.value.res_categories
  source_countries           = each.value.source_countries
  src_ips                    = each.value.src_ips
  state                      = each.value.state

  dynamic "application_groups" {
    for_each = each.value.application_groups == null ? [] : [each.value.application_groups]
    content {
      id = application_groups.value.id
    }
  }

  dynamic "departments" {
    for_each = each.value.departments == null ? [] : [each.value.departments]
    content {
      id = departments.value.id
    }
  }

  dynamic "dest_ip_groups" {
    for_each = each.value.dest_ip_groups == null ? [] : [each.value.dest_ip_groups]
    content {
      id = dest_ip_groups.value.id
    }
  }

  dynamic "dest_ipv6_groups" {
    for_each = each.value.dest_ipv6_groups == null ? [] : [each.value.dest_ipv6_groups]
    content {
      id = dest_ipv6_groups.value.id
    }
  }

  dynamic "device_groups" {
    for_each = each.value.device_groups == null ? [] : [each.value.device_groups]
    content {
      id = device_groups.value.id
    }
  }

  dynamic "devices" {
    for_each = each.value.devices == null ? [] : [each.value.devices]
    content {
      id = devices.value.id
    }
  }

  dynamic "dns_gateway" {
    for_each = each.value.dns_gateway == null ? [] : [each.value.dns_gateway]
    content {
      id   = dns_gateway.value.id
      name = dns_gateway.value.name
    }
  }

  dynamic "edns_ecs_object" {
    for_each = each.value.edns_ecs_object == null ? [] : [each.value.edns_ecs_object]
    content {
      id   = edns_ecs_object.value.id
      name = edns_ecs_object.value.name
    }
  }

  dynamic "groups" {
    for_each = each.value.groups == null ? [] : [each.value.groups]
    content {
      id = groups.value.id
    }
  }

  dynamic "labels" {
    for_each = each.value.labels == null ? [] : [each.value.labels]
    content {
      id = labels.value.id
    }
  }

  dynamic "location_groups" {
    for_each = each.value.location_groups == null ? [] : [each.value.location_groups]
    content {
      id = location_groups.value.id
    }
  }

  dynamic "locations" {
    for_each = each.value.locations == null ? [] : [each.value.locations]
    content {
      id = locations.value.id
    }
  }

  dynamic "src_ip_groups" {
    for_each = each.value.src_ip_groups == null ? [] : [each.value.src_ip_groups]
    content {
      id = src_ip_groups.value.id
    }
  }

  dynamic "src_ipv6_groups" {
    for_each = each.value.src_ipv6_groups == null ? [] : [each.value.src_ipv6_groups]
    content {
      id = src_ipv6_groups.value.id
    }
  }

  dynamic "time_windows" {
    for_each = each.value.time_windows == null ? [] : [each.value.time_windows]
    content {
      id = time_windows.value.id
    }
  }

  dynamic "timeouts" {
    for_each = each.value.timeouts == null ? [] : [each.value.timeouts]
    content {
      create = timeouts.value.create
      update = timeouts.value.update
    }
  }

  dynamic "users" {
    for_each = each.value.users == null ? [] : [each.value.users]
    content {
      id = users.value.id
    }
  }

  dynamic "zpa_ip_group" {
    for_each = each.value.zpa_ip_group == null ? [] : [each.value.zpa_ip_group]
    content {
      id   = zpa_ip_group.value.id
      name = zpa_ip_group.value.name
    }
  }
}
