# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_firewall_dns_rule instances, keyed by a stable identifier."
  type = map(object({
    name                       = string
    order                      = number
    action                     = optional(string)
    applications               = optional(set(string))
    block_response_code        = optional(string)
    capture_pcap               = optional(bool)
    default_dns_rule_name_used = optional(bool)
    default_rule               = optional(bool)
    description                = optional(string)
    dest_addresses             = optional(set(string))
    dest_countries             = optional(set(string))
    dest_ip_categories         = optional(set(string))
    dns_rule_request_types     = optional(set(string))
    is_web_eun_enabled         = optional(bool)
    predefined                 = optional(bool)
    protocols                  = optional(set(string))
    rank                       = optional(number)
    redirect_ip                = optional(string)
    res_categories             = optional(set(string))
    source_countries           = optional(set(string))
    src_ips                    = optional(set(string))
    state                      = optional(string)
    application_groups = optional(object({
      id = optional(set(number))
    }))
    departments = optional(object({
      id = optional(set(number))
    }))
    dest_ip_groups = optional(object({
      id = optional(set(number))
    }))
    dest_ipv6_groups = optional(object({
      id = optional(set(number))
    }))
    device_groups = optional(object({
      id = optional(set(number))
    }))
    devices = optional(object({
      id = optional(set(number))
    }))
    dns_gateway = optional(object({
      id   = optional(number)
      name = optional(string)
    }))
    edns_ecs_object = optional(object({
      id   = optional(number)
      name = optional(string)
    }))
    groups = optional(object({
      id = optional(set(number))
    }))
    labels = optional(object({
      id = optional(set(number))
    }))
    location_groups = optional(object({
      id = optional(set(number))
    }))
    locations = optional(object({
      id = optional(set(number))
    }))
    src_ip_groups = optional(object({
      id = optional(set(number))
    }))
    src_ipv6_groups = optional(object({
      id = optional(set(number))
    }))
    time_windows = optional(object({
      id = optional(set(number))
    }))
    timeouts = optional(object({
      create = optional(string)
      update = optional(string)
    }))
    users = optional(object({
      id = optional(set(number))
    }))
    zpa_ip_group = optional(object({
      id   = optional(number)
      name = optional(string)
    }))
  }))
}
