# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_activation_status" "this" {
  for_each = var.items

  status = each.value.status

  dynamic "timeouts" {
    for_each = each.value.timeouts == null ? [] : [each.value.timeouts]
    content {
      create = timeouts.value.create
    }
  }
}
