# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_activation_status instances, keyed by a stable identifier."
  type = map(object({
    status = string
    timeouts = optional(object({
      create = optional(string)
    }))
  }))
}
