# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_nat_control_rules" "this" {
  for_each = var.items

  name                = each.value.name
  order               = each.value.order
  default_rule        = each.value.default_rule
  description         = each.value.description
  dest_addresses      = each.value.dest_addresses
  dest_countries      = each.value.dest_countries
  dest_ip_categories  = each.value.dest_ip_categories
  enable_full_logging = each.value.enable_full_logging
  predefined          = each.value.predefined
  rank                = each.value.rank
  redirect_fqdn       = each.value.redirect_fqdn
  redirect_ip         = each.value.redirect_ip
  redirect_port       = each.value.redirect_port
  res_categories      = each.value.res_categories
  src_ips             = each.value.src_ips
  state               = each.value.state

  dynamic "departments" {
    for_each = each.value.departments == null ? [] : [each.value.departments]
    content {
      id = departments.value.id
    }
  }

  dynamic "dest_ip_groups" {
    for_each = each.value.dest_ip_groups == null ? [] : [each.value.dest_ip_groups]
    content {
      id = dest_ip_groups.value.id
    }
  }

  dynamic "dest_ipv6_groups" {
    for_each = each.value.dest_ipv6_groups == null ? [] : [each.value.dest_ipv6_groups]
    content {
      id = dest_ipv6_groups.value.id
    }
  }

  dynamic "device_groups" {
    for_each = each.value.device_groups == null ? [] : [each.value.device_groups]
    content {
      id = device_groups.value.id
    }
  }

  dynamic "devices" {
    for_each = each.value.devices == null ? [] : [each.value.devices]
    content {
      id = devices.value.id
    }
  }

  dynamic "groups" {
    for_each = each.value.groups == null ? [] : [each.value.groups]
    content {
      id = groups.value.id
    }
  }

  dynamic "labels" {
    for_each = each.value.labels == null ? [] : [each.value.labels]
    content {
      id = labels.value.id
    }
  }

  dynamic "location_groups" {
    for_each = each.value.location_groups == null ? [] : [each.value.location_groups]
    content {
      id = location_groups.value.id
    }
  }

  dynamic "locations" {
    for_each = each.value.locations == null ? [] : [each.value.locations]
    content {
      id = locations.value.id
    }
  }

  dynamic "nw_service_groups" {
    for_each = each.value.nw_service_groups == null ? [] : [each.value.nw_service_groups]
    content {
      id = nw_service_groups.value.id
    }
  }

  dynamic "nw_services" {
    for_each = each.value.nw_services == null ? [] : [each.value.nw_services]
    content {
      id = nw_services.value.id
    }
  }

  dynamic "src_ip_groups" {
    for_each = each.value.src_ip_groups == null ? [] : [each.value.src_ip_groups]
    content {
      id = src_ip_groups.value.id
    }
  }

  dynamic "src_ipv6_groups" {
    for_each = each.value.src_ipv6_groups == null ? [] : [each.value.src_ipv6_groups]
    content {
      id = src_ipv6_groups.value.id
    }
  }

  dynamic "time_windows" {
    for_each = each.value.time_windows == null ? [] : [each.value.time_windows]
    content {
      id = time_windows.value.id
    }
  }

  dynamic "timeouts" {
    for_each = each.value.timeouts == null ? [] : [each.value.timeouts]
    content {
      create = timeouts.value.create
      update = timeouts.value.update
    }
  }

  dynamic "users" {
    for_each = each.value.users == null ? [] : [each.value.users]
    content {
      id = users.value.id
    }
  }
}
