# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_application_segment_inspection" "this" {
  for_each = var.items

  domain_names                  = each.value.domain_names
  name                          = each.value.name
  segment_group_id              = each.value.segment_group_id
  adp_enabled                   = each.value.adp_enabled
  auto_app_protect_enabled      = each.value.auto_app_protect_enabled
  bypass_on_reauth              = each.value.bypass_on_reauth
  bypass_type                   = each.value.bypass_type
  config_space                  = each.value.config_space
  description                   = each.value.description
  double_encrypt                = each.value.double_encrypt
  enabled                       = each.value.enabled
  fqdn_dns_check                = each.value.fqdn_dns_check
  health_check_type             = each.value.health_check_type
  health_reporting              = each.value.health_reporting
  icmp_access_type              = each.value.icmp_access_type
  ip_anchored                   = each.value.ip_anchored
  is_cname_enabled              = each.value.is_cname_enabled
  is_incomplete_dr_config       = each.value.is_incomplete_dr_config
  passive_health_enabled        = each.value.passive_health_enabled
  policy_style                  = each.value.policy_style
  select_connector_close_to_app = each.value.select_connector_close_to_app
  tcp_keep_alive                = each.value.tcp_keep_alive
  tcp_port_range                = each.value.tcp_port_range
  tcp_port_ranges               = each.value.tcp_port_ranges
  tcp_protocols                 = each.value.tcp_protocols
  udp_port_range                = each.value.udp_port_range
  udp_port_ranges               = each.value.udp_port_ranges
  udp_protocols                 = each.value.udp_protocols
  use_in_dr_mode                = each.value.use_in_dr_mode

  dynamic "common_apps_dto" {
    for_each = each.value.common_apps_dto == null ? [] : each.value.common_apps_dto
    content {

      dynamic "apps_config" {
        for_each = common_apps_dto.value.apps_config == null ? [] : common_apps_dto.value.apps_config
        content {
          app_types            = apps_config.value.app_types
          application_port     = apps_config.value.application_port
          application_protocol = apps_config.value.application_protocol
          certificate_id       = apps_config.value.certificate_id
          domain               = apps_config.value.domain
          trust_untrusted_cert = apps_config.value.trust_untrusted_cert
        }
      }
    }
  }

  dynamic "server_groups" {
    for_each = each.value.server_groups == null ? [] : each.value.server_groups
    content {
      id = server_groups.value.id
    }
  }
}
