# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_virtual_service_edge_cluster" "this" {
  for_each = var.items

  default_gateway = each.value.default_gateway
  ip_address      = each.value.ip_address
  ip_sec_enabled  = each.value.ip_sec_enabled
  name            = each.value.name
  status          = each.value.status
  subnet_mask     = each.value.subnet_mask
  type            = each.value.type

  dynamic "virtual_zen_nodes" {
    for_each = each.value.virtual_zen_nodes == null ? [] : [each.value.virtual_zen_nodes]
    content {
      id = virtual_zen_nodes.value.id
    }
  }
}
