# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

output "items" {
  description = "All managed zia_virtual_service_edge_cluster resources, keyed as in var.items."
  value       = zia_virtual_service_edge_cluster.this
}
