# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_virtual_service_edge_cluster instances, keyed by a stable identifier."
  type = map(object({
    default_gateway = optional(string)
    ip_address      = optional(string)
    ip_sec_enabled  = optional(bool)
    name            = optional(string)
    status          = optional(string)
    subnet_mask     = optional(string)
    type            = optional(string)
    virtual_zen_nodes = optional(object({
      id = optional(list(number))
    }))
  }))
}
