# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_custom_file_types" "this" {
  for_each = var.items

  description = each.value.description
  extension   = each.value.extension
  name        = each.value.name
}
