# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_custom_file_types instances, keyed by a stable identifier."
  type = map(object({
    description = optional(string)
    extension   = optional(string)
    name        = optional(string)
  }))
}
