# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_bandwidth_classes" "this" {
  for_each = var.items

  name             = each.value.name
  url_categories   = each.value.url_categories
  urls             = each.value.urls
  web_applications = each.value.web_applications
}
