# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_bandwidth_classes instances, keyed by a stable identifier."
  type = map(object({
    name             = optional(string)
    url_categories   = optional(set(string))
    urls             = optional(set(string))
    web_applications = optional(set(string))
  }))
}
