# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_tag_group" "this" {
  for_each = var.items

  name           = each.value.name
  description    = each.value.description
  microtenant_id = each.value.microtenant_id
  tags           = each.value.tags
}
