# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_application_segment_pra instances, keyed by a stable identifier."
  type = map(object({
    domain_names                  = set(string)
    name                          = string
    segment_group_id              = string
    bypass_on_reauth              = optional(bool)
    bypass_type                   = optional(string)
    config_space                  = optional(string)
    description                   = optional(string)
    double_encrypt                = optional(bool)
    enabled                       = optional(bool)
    fqdn_dns_check                = optional(bool)
    health_check_type             = optional(string)
    health_reporting              = optional(string)
    icmp_access_type              = optional(string)
    ip_anchored                   = optional(bool)
    is_cname_enabled              = optional(bool)
    is_incomplete_dr_config       = optional(bool)
    microtenant_id                = optional(string)
    passive_health_enabled        = optional(bool)
    select_connector_close_to_app = optional(bool)
    tcp_keep_alive                = optional(string)
    tcp_port_range = optional(list(object({
      from = optional(string)
      to   = optional(string)
    })))
    tcp_port_ranges = optional(list(string))
    udp_port_range = optional(list(object({
      from = optional(string)
      to   = optional(string)
    })))
    udp_port_ranges = optional(list(string))
    use_in_dr_mode  = optional(bool)
    common_apps_dto = optional(list(object({
      apps_config = optional(list(object({
        app_types            = optional(set(string))
        application_port     = optional(string)
        application_protocol = optional(string)
        connection_security  = optional(string)
        domain               = optional(string)
        name                 = optional(string)
      })))
    })))
    server_groups = optional(list(object({
      id = optional(set(string))
    })))
    zpn_er_id = optional(list(object({
      id = optional(set(string))
    })))
  }))
}
