# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_provisioning_key" "this" {
  for_each = var.items

  association_type       = each.value.association_type
  enrollment_cert_id     = each.value.enrollment_cert_id
  max_usage              = each.value.max_usage
  name                   = each.value.name
  zcomponent_id          = each.value.zcomponent_id
  app_connector_group_id = each.value.app_connector_group_id
  enabled                = each.value.enabled
  ip_acl                 = each.value.ip_acl
  microtenant_id         = each.value.microtenant_id
  ui_config              = each.value.ui_config
  usage_count            = each.value.usage_count
  zcomponent_name        = each.value.zcomponent_name
}
