# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

output "items" {
  description = "All managed zpa_provisioning_key resources, keyed as in var.items."
  sensitive   = true
  value       = zpa_provisioning_key.this
}

output "name_to_id" {
  description = "Map of resource name to provider-assigned id."
  value       = { for k, v in zpa_provisioning_key.this : v.name => v.id }
}
