# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_provisioning_key instances, keyed by a stable identifier."
  type = map(object({
    association_type       = string
    enrollment_cert_id     = string
    max_usage              = string
    name                   = string
    zcomponent_id          = string
    app_connector_group_id = optional(string)
    enabled                = optional(bool)
    ip_acl                 = optional(set(string))
    microtenant_id         = optional(string)
    ui_config              = optional(string)
    usage_count            = optional(string)
    zcomponent_name        = optional(string)
  }))
}
