# GENERATED by tools/gen_module.py from schemas/provider/zcc.json — do not edit.
# Regenerate: make generate

output "items" {
  description = "All managed zcc_trusted_network resources, keyed as in var.items."
  value       = zcc_trusted_network.this
}
