# GENERATED by tools/gen_env.py for tenant 'demo' — do not edit.
# Regenerate: make gen-env TENANT=demo

terraform {
  required_version = ">= 1.5"
  required_providers {
    zpa = {
      source = "zscaler/zpa"
    }
  }
  # backend configured per environment (Plan 5 / operator)
}

provider "zpa" {
  # credentials via env (ZSCALER_*/ZIA_*/ZPA_*); see tools/FETCH.md
}

variable "items" {
  # opaque at the root; the module enforces the strict type.
  type = any
}

module "zpa_policy_access_rule" {
  source = "../../../modules/zpa_policy_access_rule"
  items  = var.items
}
