# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_extranet" "this" {
  for_each = var.items

  name        = each.value.name
  description = each.value.description

  dynamic "extranet_dns_list" {
    for_each = each.value.extranet_dns_list == null ? [] : each.value.extranet_dns_list
    content {
      name                 = extranet_dns_list.value.name
      primary_dns_server   = extranet_dns_list.value.primary_dns_server
      secondary_dns_server = extranet_dns_list.value.secondary_dns_server
      use_as_default       = extranet_dns_list.value.use_as_default
    }
  }

  dynamic "extranet_ip_pool_list" {
    for_each = each.value.extranet_ip_pool_list == null ? [] : each.value.extranet_ip_pool_list
    content {
      ip_end         = extranet_ip_pool_list.value.ip_end
      ip_start       = extranet_ip_pool_list.value.ip_start
      name           = extranet_ip_pool_list.value.name
      use_as_default = extranet_ip_pool_list.value.use_as_default
    }
  }
}
