# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

output "items" {
  description = "All managed zia_extranet resources, keyed as in var.items."
  value       = zia_extranet.this
}

output "name_to_id" {
  description = "Map of resource name to provider-assigned id."
  value       = { for k, v in zia_extranet.this : v.name => v.id }
}
