# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_extranet instances, keyed by a stable identifier."
  type = map(object({
    name        = string
    description = optional(string)
    extranet_dns_list = optional(list(object({
      name                 = optional(string)
      primary_dns_server   = optional(string)
      secondary_dns_server = optional(string)
      use_as_default       = optional(bool)
    })))
    extranet_ip_pool_list = optional(list(object({
      ip_end         = optional(string)
      ip_start       = optional(string)
      name           = optional(string)
      use_as_default = optional(bool)
    })))
  }))
}
