# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_subscription_alert" "this" {
  for_each = var.items

  comply_severities = each.value.comply_severities
  description       = each.value.description
  email             = each.value.email
  manage_severities = each.value.manage_severities
  pt0_severities    = each.value.pt0_severities
  secure_severities = each.value.secure_severities
  system_severities = each.value.system_severities
}
