# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_subscription_alert instances, keyed by a stable identifier."
  type = map(object({
    comply_severities = optional(set(string))
    description       = optional(string)
    email             = optional(string)
    manage_severities = optional(set(string))
    pt0_severities    = optional(set(string))
    secure_severities = optional(set(string))
    system_severities = optional(set(string))
  }))
}
