# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

output "items" {
  description = "All managed zpa_policy_access_rule_reorder resources, keyed as in var.items."
  value       = zpa_policy_access_rule_reorder.this
}
