# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_policy_access_rule_reorder instances, keyed by a stable identifier."
  type = map(object({
    policy_type = string
    rules = optional(set(object({
      id    = optional(string)
      order = optional(string)
    })))
  }))
}
