# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_server_group instances, keyed by a stable identifier."
  type = map(object({
    name              = string
    config_space      = optional(string)
    description       = optional(string)
    dynamic_discovery = optional(bool)
    enabled           = optional(bool)
    extranet_enabled  = optional(bool)
    ip_anchored       = optional(bool)
    microtenant_id    = optional(string)
    app_connector_groups = optional(list(object({
      id = optional(set(string))
    })))
    applications = optional(set(object({
      id = optional(list(string))
    })))
    extranet_dto = optional(list(object({
      zpn_er_id = optional(string)
      location_dto = optional(list(object({
        id = optional(string)
      })))
      location_group_dto = optional(list(object({
        id = optional(string)
      })))
    })))
    servers = optional(list(object({
      id = optional(set(string))
    })))
  }))
}
