# GENERATED by tools/gen_env.py for tenant 'zs2' — do not edit.
# Regenerate: make gen-env TENANT=zs2

terraform {
  required_version = ">= 1.5"
  required_providers {
    zia = {
      source = "zscaler/zia"
    }
  }
  # local state — opt into remote state with
  # make gen-env TENANT=zs2 BACKEND=azurerm
}

provider "zia" {
  # credentials via env (ZSCALER_*/ZIA_*/ZPA_*); see tools/FETCH.md
}

variable "items" {
  # opaque at the root; the module enforces the strict type.
  type = any
}

module "zia_url_categories" {
  source = "../../../modules/zia_url_categories"
  items  = var.items
}
