# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_url_filtering_rules" "this" {
  for_each = var.items

  name                      = each.value.name
  order                     = each.value.order
  protocols                 = each.value.protocols
  action                    = each.value.action
  block_override            = each.value.block_override
  browser_eun_template_id   = each.value.browser_eun_template_id
  ciparule                  = each.value.ciparule
  description               = each.value.description
  device_trust_levels       = each.value.device_trust_levels
  end_user_notification_url = each.value.end_user_notification_url
  enforce_time_validity     = each.value.enforce_time_validity
  rank                      = each.value.rank
  request_methods           = each.value.request_methods
  size_quota                = each.value.size_quota
  source_countries          = each.value.source_countries
  state                     = each.value.state
  time_quota                = each.value.time_quota
  url_categories            = each.value.url_categories
  user_agent_types          = each.value.user_agent_types
  user_risk_score_levels    = each.value.user_risk_score_levels
  validity_end_time         = each.value.validity_end_time
  validity_start_time       = each.value.validity_start_time
  validity_time_zone_id     = each.value.validity_time_zone_id

  dynamic "cbi_profile" {
    for_each = each.value.cbi_profile == null ? [] : each.value.cbi_profile
    content {
      id          = cbi_profile.value.id
      name        = cbi_profile.value.name
      profile_seq = cbi_profile.value.profile_seq
      url         = cbi_profile.value.url
    }
  }

  dynamic "departments" {
    for_each = each.value.departments == null ? [] : [each.value.departments]
    content {
      id = departments.value.id
    }
  }

  dynamic "device_groups" {
    for_each = each.value.device_groups == null ? [] : [each.value.device_groups]
    content {
      id = device_groups.value.id
    }
  }

  dynamic "devices" {
    for_each = each.value.devices == null ? [] : [each.value.devices]
    content {
      id = devices.value.id
    }
  }

  dynamic "groups" {
    for_each = each.value.groups == null ? [] : [each.value.groups]
    content {
      id = groups.value.id
    }
  }

  dynamic "labels" {
    for_each = each.value.labels == null ? [] : [each.value.labels]
    content {
      id = labels.value.id
    }
  }

  dynamic "location_groups" {
    for_each = each.value.location_groups == null ? [] : [each.value.location_groups]
    content {
      id = location_groups.value.id
    }
  }

  dynamic "locations" {
    for_each = each.value.locations == null ? [] : [each.value.locations]
    content {
      id = locations.value.id
    }
  }

  dynamic "override_groups" {
    for_each = each.value.override_groups == null ? [] : [each.value.override_groups]
    content {
      id = override_groups.value.id
    }
  }

  dynamic "override_users" {
    for_each = each.value.override_users == null ? [] : [each.value.override_users]
    content {
      id = override_users.value.id
    }
  }

  dynamic "source_ip_groups" {
    for_each = each.value.source_ip_groups == null ? [] : [each.value.source_ip_groups]
    content {
      id = source_ip_groups.value.id
    }
  }

  dynamic "time_windows" {
    for_each = each.value.time_windows == null ? [] : [each.value.time_windows]
    content {
      id = time_windows.value.id
    }
  }

  dynamic "timeouts" {
    for_each = each.value.timeouts == null ? [] : [each.value.timeouts]
    content {
      create = timeouts.value.create
      update = timeouts.value.update
    }
  }

  dynamic "users" {
    for_each = each.value.users == null ? [] : [each.value.users]
    content {
      id = users.value.id
    }
  }

  dynamic "workload_groups" {
    for_each = each.value.workload_groups == null ? [] : each.value.workload_groups
    content {
      id   = workload_groups.value.id
      name = workload_groups.value.name
    }
  }
}
