# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_url_filtering_rules instances, keyed by a stable identifier."
  type = map(object({
    name                      = string
    order                     = number
    protocols                 = set(string)
    action                    = optional(string)
    block_override            = optional(bool)
    browser_eun_template_id   = optional(number)
    ciparule                  = optional(bool)
    description               = optional(string)
    device_trust_levels       = optional(set(string))
    end_user_notification_url = optional(string)
    enforce_time_validity     = optional(bool)
    rank                      = optional(number)
    request_methods           = optional(set(string))
    size_quota                = optional(number)
    source_countries          = optional(set(string))
    state                     = optional(string)
    time_quota                = optional(number)
    url_categories            = optional(set(string))
    user_agent_types          = optional(set(string))
    user_risk_score_levels    = optional(set(string))
    validity_end_time         = optional(string)
    validity_start_time       = optional(string)
    validity_time_zone_id     = optional(string)
    cbi_profile = optional(list(object({
      id          = optional(string)
      name        = optional(string)
      profile_seq = optional(number)
      url         = optional(string)
    })))
    departments = optional(object({
      id = optional(set(number))
    }))
    device_groups = optional(object({
      id = optional(set(number))
    }))
    devices = optional(object({
      id = optional(set(number))
    }))
    groups = optional(object({
      id = optional(set(number))
    }))
    labels = optional(object({
      id = optional(set(number))
    }))
    location_groups = optional(object({
      id = optional(set(number))
    }))
    locations = optional(object({
      id = optional(set(number))
    }))
    override_groups = optional(object({
      id = optional(set(number))
    }))
    override_users = optional(object({
      id = optional(set(number))
    }))
    source_ip_groups = optional(object({
      id = optional(set(number))
    }))
    time_windows = optional(object({
      id = optional(set(number))
    }))
    timeouts = optional(object({
      create = optional(string)
      update = optional(string)
    }))
    users = optional(object({
      id = optional(set(number))
    }))
    workload_groups = optional(set(object({
      id   = optional(number)
      name = optional(string)
    })))
  }))
}
