# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_policy_capabilities_rule" "this" {
  for_each = var.items

  name           = each.value.name
  action         = each.value.action
  description    = each.value.description
  microtenant_id = each.value.microtenant_id

  dynamic "conditions" {
    for_each = each.value.conditions == null ? [] : each.value.conditions
    content {
      operator = conditions.value.operator

      dynamic "operands" {
        for_each = conditions.value.operands == null ? [] : conditions.value.operands
        content {
          object_type = operands.value.object_type
          values      = operands.value.values

          dynamic "entry_values" {
            for_each = operands.value.entry_values == null ? [] : operands.value.entry_values
            content {
              lhs = entry_values.value.lhs
              rhs = entry_values.value.rhs
            }
          }
        }
      }
    }
  }

  dynamic "privileged_capabilities" {
    for_each = each.value.privileged_capabilities == null ? [] : [each.value.privileged_capabilities]
    content {
      clipboard_copy        = privileged_capabilities.value.clipboard_copy
      clipboard_paste       = privileged_capabilities.value.clipboard_paste
      file_download         = privileged_capabilities.value.file_download
      file_upload           = privileged_capabilities.value.file_upload
      inspect_file_download = privileged_capabilities.value.inspect_file_download
      inspect_file_upload   = privileged_capabilities.value.inspect_file_upload
      monitor_session       = privileged_capabilities.value.monitor_session
      record_session        = privileged_capabilities.value.record_session
      share_session         = privileged_capabilities.value.share_session
    }
  }
}
