# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_policy_capabilities_rule instances, keyed by a stable identifier."
  type = map(object({
    name           = string
    action         = optional(string)
    description    = optional(string)
    microtenant_id = optional(string)
    conditions = optional(set(object({
      operator = optional(string)
      operands = optional(set(object({
        object_type = optional(string)
        values      = optional(set(string))
        entry_values = optional(set(object({
          lhs = optional(string)
          rhs = optional(string)
        })))
      })))
    })))
    privileged_capabilities = optional(object({
      clipboard_copy        = optional(bool)
      clipboard_paste       = optional(bool)
      file_download         = optional(bool)
      file_upload           = optional(bool)
      inspect_file_download = optional(bool)
      inspect_file_upload   = optional(bool)
      monitor_session       = optional(bool)
      record_session        = optional(bool)
      share_session         = optional(bool)
    }))
  }))
}
