# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_inspection_custom_controls" "this" {
  for_each = var.items

  name                 = each.value.name
  severity             = each.value.severity
  type                 = each.value.type
  control_type         = each.value.control_type
  default_action       = each.value.default_action
  default_action_value = each.value.default_action_value
  description          = each.value.description
  paranoia_level       = each.value.paranoia_level
  protocol_type        = each.value.protocol_type
  version              = each.value.version

  dynamic "rules" {
    for_each = each.value.rules == null ? [] : each.value.rules
    content {
      names = rules.value.names
      type  = rules.value.type

      dynamic "conditions" {
        for_each = rules.value.conditions == null ? [] : rules.value.conditions
        content {
          lhs = conditions.value.lhs
          op  = conditions.value.op
          rhs = conditions.value.rhs
        }
      }
    }
  }
}
