# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_inspection_custom_controls instances, keyed by a stable identifier."
  type = map(object({
    name                 = string
    severity             = string
    type                 = string
    control_type         = optional(string)
    default_action       = optional(string)
    default_action_value = optional(string)
    description          = optional(string)
    paranoia_level       = optional(string)
    protocol_type        = optional(string)
    version              = optional(string)
    rules = optional(list(object({
      names = optional(set(string))
      type  = optional(string)
      conditions = optional(list(object({
        lhs = optional(string)
        op  = optional(string)
        rhs = optional(string)
      })))
    })))
  }))
}
