# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_ba_certificate" "this" {
  for_each = var.items

  name           = each.value.name
  cert_blob      = each.value.cert_blob
  description    = each.value.description
  microtenant_id = each.value.microtenant_id
}
