# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_ba_certificate instances, keyed by a stable identifier."
  type = map(object({
    name           = string
    cert_blob      = optional(string)
    description    = optional(string)
    microtenant_id = optional(string)
  }))
}
