# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_sub_cloud" "this" {
  for_each = var.items

  cloud_id = each.value.cloud_id
  name     = each.value.name

  dynamic "exclusions" {
    for_each = each.value.exclusions == null ? [] : each.value.exclusions
    content {
      country      = exclusions.value.country
      end_time     = exclusions.value.end_time
      end_time_utc = exclusions.value.end_time_utc

      dynamic "datacenter" {
        for_each = exclusions.value.datacenter == null ? [] : [exclusions.value.datacenter]
        content {
          id      = datacenter.value.id
          country = datacenter.value.country
          name    = datacenter.value.name
        }
      }
    }
  }
}
