# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_sub_cloud instances, keyed by a stable identifier."
  type = map(object({
    cloud_id = number
    name     = optional(string)
    exclusions = optional(set(object({
      country      = optional(string)
      end_time     = optional(number)
      end_time_utc = optional(string)
      datacenter = optional(object({
        id      = optional(number)
        country = optional(string)
        name    = optional(string)
      }))
    })))
  }))
}
