# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_application_segment_browser_access" "this" {
  for_each = var.items

  domain_names                  = each.value.domain_names
  name                          = each.value.name
  segment_group_id              = each.value.segment_group_id
  bypass_type                   = each.value.bypass_type
  config_space                  = each.value.config_space
  description                   = each.value.description
  double_encrypt                = each.value.double_encrypt
  enabled                       = each.value.enabled
  fqdn_dns_check                = each.value.fqdn_dns_check
  health_check_type             = each.value.health_check_type
  health_reporting              = each.value.health_reporting
  icmp_access_type              = each.value.icmp_access_type
  ip_anchored                   = each.value.ip_anchored
  is_cname_enabled              = each.value.is_cname_enabled
  is_incomplete_dr_config       = each.value.is_incomplete_dr_config
  microtenant_id                = each.value.microtenant_id
  passive_health_enabled        = each.value.passive_health_enabled
  segment_group_name            = each.value.segment_group_name
  select_connector_close_to_app = each.value.select_connector_close_to_app
  tcp_keep_alive                = each.value.tcp_keep_alive
  tcp_port_range                = each.value.tcp_port_range
  tcp_port_ranges               = each.value.tcp_port_ranges
  udp_port_range                = each.value.udp_port_range
  udp_port_ranges               = each.value.udp_port_ranges
  use_in_dr_mode                = each.value.use_in_dr_mode

  dynamic "clientless_apps" {
    for_each = each.value.clientless_apps == null ? [] : each.value.clientless_apps
    content {
      application_port     = clientless_apps.value.application_port
      application_protocol = clientless_apps.value.application_protocol
      name                 = clientless_apps.value.name
      allow_options        = clientless_apps.value.allow_options
      certificate_id       = clientless_apps.value.certificate_id
      description          = clientless_apps.value.description
      domain               = clientless_apps.value.domain
      enabled              = clientless_apps.value.enabled
      ext_domain           = clientless_apps.value.ext_domain
      ext_label            = clientless_apps.value.ext_label
      microtenant_id       = clientless_apps.value.microtenant_id
      trust_untrusted_cert = clientless_apps.value.trust_untrusted_cert
    }
  }

  dynamic "server_groups" {
    for_each = each.value.server_groups == null ? [] : each.value.server_groups
    content {
      id = server_groups.value.id
    }
  }

  dynamic "zpn_er_id" {
    for_each = each.value.zpn_er_id == null ? [] : each.value.zpn_er_id
    content {
      id = zpn_er_id.value.id
    }
  }
}
