# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_policy_access_rule_v2" "this" {
  for_each = var.items

  name             = each.value.name
  action           = each.value.action
  custom_msg       = each.value.custom_msg
  description      = each.value.description
  extranet_enabled = each.value.extranet_enabled
  operator         = each.value.operator

  dynamic "app_connector_groups" {
    for_each = each.value.app_connector_groups == null ? [] : each.value.app_connector_groups
    content {
      id = app_connector_groups.value.id
    }
  }

  dynamic "app_server_groups" {
    for_each = each.value.app_server_groups == null ? [] : each.value.app_server_groups
    content {
      id = app_server_groups.value.id
    }
  }

  dynamic "conditions" {
    for_each = each.value.conditions == null ? [] : each.value.conditions
    content {
      operator = conditions.value.operator

      dynamic "operands" {
        for_each = conditions.value.operands == null ? [] : conditions.value.operands
        content {
          object_type = operands.value.object_type
          values      = operands.value.values

          dynamic "entry_values" {
            for_each = operands.value.entry_values == null ? [] : operands.value.entry_values
            content {
              lhs = entry_values.value.lhs
              rhs = entry_values.value.rhs
            }
          }
        }
      }
    }
  }

  dynamic "extranet_dto" {
    for_each = each.value.extranet_dto == null ? [] : each.value.extranet_dto
    content {
      zpn_er_id = extranet_dto.value.zpn_er_id

      dynamic "location_dto" {
        for_each = extranet_dto.value.location_dto == null ? [] : extranet_dto.value.location_dto
        content {
          id = location_dto.value.id
        }
      }

      dynamic "location_group_dto" {
        for_each = extranet_dto.value.location_group_dto == null ? [] : extranet_dto.value.location_group_dto
        content {
          id = location_group_dto.value.id
        }
      }
    }
  }
}
