# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_policy_access_rule_v2 instances, keyed by a stable identifier."
  type = map(object({
    name             = string
    action           = optional(string)
    custom_msg       = optional(string)
    description      = optional(string)
    extranet_enabled = optional(bool)
    operator         = optional(string)
    app_connector_groups = optional(list(object({
      id = optional(set(string))
    })))
    app_server_groups = optional(list(object({
      id = optional(set(string))
    })))
    conditions = optional(set(object({
      operator = optional(string)
      operands = optional(set(object({
        object_type = optional(string)
        values      = optional(set(string))
        entry_values = optional(set(object({
          lhs = optional(string)
          rhs = optional(string)
        })))
      })))
    })))
    extranet_dto = optional(list(object({
      zpn_er_id = optional(string)
      location_dto = optional(list(object({
        id = optional(string)
      })))
      location_group_dto = optional(list(object({
        id = optional(string)
      })))
    })))
  }))
}
