"""Generate Terraform modules from the committed provider schema dumps.

Authoring-side tool: runs here via `make generate`, output is committed.
Consuming environments never run it. Stdlib-only, Python 3.6-floor syntax
— see AGENTS.md rules 5-7.
"""
import json
import os
import re
import subprocess
import sys
from tools.registry import generated_types
from tools.tfschema import block_is_single, classify_attributes, hcl_type, load_resource


def _header(resource_type, provider):
    return (
        "# GENERATED by tools/gen_module.py from schemas/provider/%s.json"
        " — do not edit.\n# Regenerate: make generate\n\n" % provider
    )


_PROVIDER_SOURCES = {
    "zia": "zscaler/zia",
    "zpa": "zscaler/zpa",
    "zcc": "zscaler/zcc",
}

# The provider pins are owned by tools/schema-extract/main.tf — the same file
# that produces the committed schema dumps. Generated modules MUST carry the
# version that the dumps (and thus variables.tf types) were built from, or a
# deploy-time `terraform init` can resolve a newer provider whose retyped/
# renamed attributes break plan or silently diverge from what was validated.
# zia/zpa are pre-1.0 (churn expected) and zcc is a beta whose pre-release
# version the registry never advertises as "latest" — so all three need an
# explicit constraint. Reading the pins from one place keeps a version bump a
# one-line edit there + `make schemas` + `make generate`, never a second pin to
# forget. See README provider-bump workflow.
_SCHEMA_EXTRACT_MAIN_TF = os.path.join("tools", "schema-extract", "main.tf")


def _load_provider_pins(path=_SCHEMA_EXTRACT_MAIN_TF):
    """Parse {provider: version} from a required_providers main.tf.

    Matches the `xxx = { source = "...", version = "..." }` blocks in
    tools/schema-extract/main.tf so the modules pin exactly the versions the
    schema dumps were extracted under. Fails loudly if the file is missing or
    advertises no versioned provider — a silent {} would regenerate modules
    with no constraint, reintroducing the unpinned-deploy bug.
    """
    if not os.path.exists(path):
        raise ValueError(
            "provider pins not found: %s is missing — generation reads the "
            "pins from there (the file the schema dumps are extracted under). "
            "Restore it or pass an explicit path." % path
        )
    with open(path) as f:
        text = f.read()
    pins = {}
    block_re = re.compile(
        r'(\w+)\s*=\s*\{[^}]*?version\s*=\s*"([^"]+)"', re.DOTALL
    )
    for name, version in block_re.findall(text):
        pins[name] = version
    if not pins:
        raise ValueError(
            "no versioned providers found in %s — every required_providers "
            "entry needs a version line so generated modules can pin it. Add "
            "version = \"x.y.z\" beside each source." % path
        )
    return pins


_PROVIDER_VERSION_CONSTRAINTS = _load_provider_pins()


def _provider_of(resource_type):
    return resource_type.split("_", 1)[0]


def _check_block_has_inputs(name, block):
    """Fail loudly on blocks with no settable inputs anywhere.

    An all-computed leaf block would render an empty content {} that
    terraform rejects. None exist in the scoped resources today; when one
    arrives, decide deliberately (exclude it like computed-only attrs, or
    add an override) instead of generating broken HCL.
    """
    cls = classify_attributes(block)
    if cls["required"] or cls["optional"]:
        return
    if block.get("block_types"):
        for child_name, bt in sorted(block["block_types"].items()):
            _check_block_has_inputs(child_name, bt["block"])
        return
    raise ValueError(
        "block %r has only computed attributes; the generator would emit "
        "an empty content {} — exclude it via an override or extend the "
        "generator deliberately" % name
    )


def _block_object_type(block, indent):
    """HCL object({...}) type for a nested block's input shape."""
    cls = classify_attributes(block)
    pad = " " * (indent + 2)
    lines = []
    for name in cls["required"] + cls["optional"]:
        attr_t = hcl_type(block["attributes"][name]["type"], indent + 2)
        lines.append("%s%s = optional(%s)" % (pad, name, attr_t))
    for name, bt in sorted((block.get("block_types") or {}).items()):
        lines.append(
            "%s%s = optional(%s)" % (pad, name, _block_input_type(bt, indent + 2, name))
        )
    return "object({\n%s\n%s})" % ("\n".join(lines), " " * indent)


def _block_input_type(block_type, indent, name="<unknown>"):
    _check_block_has_inputs(name, block_type["block"])
    inner = _block_object_type(block_type["block"], indent)
    mode = block_type["nesting_mode"]
    if block_is_single(block_type):
        # One instance max (nesting "single" or max_items=1): typed as a
        # bare object; main.tf wraps [x] in the dynamic block's for_each.
        return inner
    if mode in ("list", "set"):
        return "%s(%s)" % (mode, inner)
    raise ValueError("unsupported nesting_mode %r" % mode)


def _render_block_body(block, ref, indent):
    """Body lines for a resource or dynamic-content block.

    ref: expression prefix for reading values (e.g. "each.value" or
    "applications.value"). Computed-only attributes are never assigned.
    """
    pad = " " * indent
    cls = classify_attributes(block)
    lines = []
    for name in cls["required"] + cls["optional"]:
        lines.append("%s%s = %s.%s" % (pad, name, ref, name))
    for name, bt in sorted((block.get("block_types") or {}).items()):
        _check_block_has_inputs(name, bt["block"])
        source = "%s.%s" % (ref, name)
        if block_is_single(bt):
            iterable = "%s == null ? [] : [%s]" % (source, source)
        else:
            iterable = "%s == null ? [] : %s" % (source, source)
        lines.append("")
        lines.append('%sdynamic "%s" {' % (pad, name))
        lines.append("%s  for_each = %s" % (pad, iterable))
        lines.append("%s  content {" % pad)
        lines.extend(_render_block_body(bt["block"], "%s.value" % name, indent + 4))
        lines.append("%s  }" % pad)
        lines.append("%s}" % pad)
    return lines


def render_main(resource_type, resource_schema):
    body = _render_block_body(resource_schema["block"], "each.value", 2)
    return (
        _header(resource_type, _provider_of(resource_type))
        + 'resource "%s" "this" {\n' % resource_type
        + "  for_each = var.items\n\n"
        + "\n".join(body)
        + "\n}\n"
    )


def render_variables(resource_type, resource_schema):
    block = resource_schema["block"]
    cls = classify_attributes(block)
    lines = []
    for name in cls["required"]:
        lines.append("    %s = %s" % (name, hcl_type(block["attributes"][name]["type"])))
    for name in cls["optional"]:
        lines.append(
            "    %s = optional(%s)" % (name, hcl_type(block["attributes"][name]["type"]))
        )
    for name, bt in sorted((block.get("block_types") or {}).items()):
        lines.append("    %s = optional(%s)" % (name, _block_input_type(bt, 4, name)))
    return (
        _header(resource_type, _provider_of(resource_type))
        + 'variable "items" {\n'
        + '  description = "%s instances, keyed by a stable identifier."\n'
        % resource_type
        + "  type = map(object({\n%s\n  }))\n}\n" % "\n".join(lines)
    )


_SAMPLE_VALUES = {"string": "example", "bool": True, "number": 1}


def render_outputs(resource_type, resource_schema):
    attrs = resource_schema["block"].get("attributes") or {}
    out = (
        _header(resource_type, _provider_of(resource_type))
        + 'output "items" {\n'
        + '  description = "All managed %s resources, keyed as in var.items."\n'
        % resource_type
        + "  value = %s.this\n}\n" % resource_type
    )
    if attrs.get("name", {}).get("required") and "id" in attrs:
        out += (
            '\noutput "name_to_id" {\n'
            + '  description = "Map of resource name to provider-assigned id."\n'
            + "  value = { for k, v in %s.this : v.name => v.id }\n}\n" % resource_type
        )
    return out


def render_readme(resource_type, resource_schema):
    return (
        "# %s (generated module)\n\n"
        "Manages `%s` via a typed `items` map. GENERATED — do not edit by\n"
        "hand (AGENTS.md rule 6). Regenerate: `make generate`. Test:\n"
        "`terraform -chdir=modules/%s test`.\n"
        % (resource_type, resource_type, resource_type)
    )


def render_versions(resource_type, resource_schema):
    provider = _provider_of(resource_type)
    source = _PROVIDER_SOURCES[provider]
    version_line = ""
    if provider in _PROVIDER_VERSION_CONSTRAINTS:
        version_line = '      version = "%s"\n' % _PROVIDER_VERSION_CONSTRAINTS[provider]
    return (
        _header(resource_type, provider)
        + "terraform {\n"
        + "  required_providers {\n"
        + '    %s = {\n' % provider
        + '      source = "%s"\n' % source
        + version_line
        + "    }\n"
        + "  }\n"
        + "}\n"
    )


def _sample_value(enc):
    """Return a minimal sample value for a required attribute type encoding."""
    if isinstance(enc, str):
        return _SAMPLE_VALUES.get(enc, "example")
    # complex type: ["set"/"list"/"map", inner]
    if isinstance(enc, list) and len(enc) == 2:
        kind, inner = enc
        if kind in ("set", "list"):
            return [_sample_value(inner)]
        if kind == "map":
            return {"example": _sample_value(inner)}
    return []


def render_sample(resource_type, resource_schema, sample_override=None):
    cls = classify_attributes(resource_schema["block"])
    item = {}
    for name in cls["required"]:
        enc = resource_schema["block"]["attributes"][name]["type"]
        item[name] = _sample_value(enc)
    if sample_override:
        item.update(sample_override)
    return json.dumps({"items": {"example": item}}, indent=2, sort_keys=True) + "\n"


def render_test(resource_type, resource_schema):
    provider = _provider_of(resource_type)
    return (
        "# GENERATED smoke test — plan against a mocked provider; no credentials.\n"
        'mock_provider "%s" {}\n\n'
        "run \"defaults_plan\" {\n"
        "  command = plan\n\n"
        "  assert {\n"
        "    condition     = length(var.items) == 1\n"
        '    error_message = "sample fixture must contain exactly one item"\n'
        "  }\n"
        "}\n" % provider
    )


OVERRIDES_ROOT = os.path.join("tools", "overrides")
MODULES_ROOT = "modules"


def _fmt(text):
    """Pipe rendered HCL through terraform fmt for canonical formatting.

    Generation is authoring-side only (AGENTS.md / README), so requiring
    terraform here is fine; fail loudly rather than committing unformatted
    output that `make validate` would reject.
    """
    proc = subprocess.run(
        ["terraform", "fmt", "-"], input=text.encode(), stdout=subprocess.PIPE, check=True
    )
    return proc.stdout.decode()


def _load_json_override(resource_type, overrides_root):
    """Load tools/overrides/<resource_type>.json if it exists, else {}."""
    path = os.path.join(overrides_root, resource_type + ".json")
    if not os.path.exists(path):
        return {}
    with open(path) as f:
        return json.load(f)


def generate_module(resource_type, out_root=MODULES_ROOT, overrides_root=OVERRIDES_ROOT, fmt=True):
    rs = load_resource(resource_type)
    base = os.path.join(out_root, resource_type)
    os.makedirs(os.path.join(base, "tests"), exist_ok=True)
    json_override = _load_json_override(resource_type, overrides_root)
    override_main = os.path.join(overrides_root, resource_type, "main.tf")
    if os.path.exists(override_main):
        with open(override_main) as f:
            main_text = f.read()
    else:
        main_text = render_main(resource_type, rs)
    files = {
        "variables.tf": render_variables(resource_type, rs),
        "versions.tf": render_versions(resource_type, rs),
        "main.tf": main_text,
        "outputs.tf": render_outputs(resource_type, rs),
        "README.md": render_readme(resource_type, rs),
        os.path.join("tests", "defaults.tftest.hcl"): render_test(resource_type, rs),
        os.path.join("tests", "sample.auto.tfvars.json"): render_sample(
            resource_type, rs, sample_override=json_override.get("sample")
        ),
    }
    for rel, text in sorted(files.items()):
        if fmt and (rel.endswith(".tf") or rel.endswith(".tftest.hcl")):
            text = _fmt(text)
        with open(os.path.join(base, rel), "w") as f:
            f.write(text)
        sys.stderr.write("wrote %s\n" % os.path.join(base, rel))


def main():
    for resource_type in generated_types():
        generate_module(resource_type)


if __name__ == "__main__":
    main()
