"""Generate Terraform modules from the committed provider schema dumps.

Authoring-side tool: runs here via `make generate`, output is committed.
Consuming environments never run it. Stdlib-only, Python 3.6-floor syntax
— see AGENTS.md rules 5-7.
"""
import json
from tools.tfschema import classify_attributes, hcl_type, load_resource


def _header(resource_type, provider):
    return (
        "# GENERATED by tools/gen_module.py from schemas/provider/%s.json"
        " — do not edit.\n# Regenerate: make generate\n\n" % provider
    )


def _provider_of(resource_type):
    return resource_type.split("_", 1)[0]


def _block_object_type(block, indent):
    """HCL object({...}) type for a nested block's input shape."""
    cls = classify_attributes(block)
    pad = " " * (indent + 2)
    lines = []
    for name in cls["required"] + cls["optional"]:
        attr_t = hcl_type(block["attributes"][name]["type"], indent + 2)
        lines.append("%s%s = optional(%s)" % (pad, name, attr_t))
    for name, bt in sorted((block.get("block_types") or {}).items()):
        lines.append(
            "%s%s = optional(%s)" % (pad, name, _block_input_type(bt, indent + 2))
        )
    return "object({\n%s\n%s})" % ("\n".join(lines), " " * indent)


def _block_input_type(block_type, indent):
    inner = _block_object_type(block_type["block"], indent)
    mode = block_type["nesting_mode"]
    if mode == "single":
        return inner
    if mode in ("list", "set"):
        return "%s(%s)" % (mode, inner)
    raise ValueError("unsupported nesting_mode %r" % mode)


def _render_block_body(block, ref, indent):
    """Body lines for a resource or dynamic-content block.

    ref: expression prefix for reading values (e.g. "each.value" or
    "applications.value"). Computed-only attributes are never assigned.
    """
    pad = " " * indent
    cls = classify_attributes(block)
    lines = []
    for name in cls["required"] + cls["optional"]:
        lines.append("%s%s = %s.%s" % (pad, name, ref, name))
    for name, bt in sorted((block.get("block_types") or {}).items()):
        source = "%s.%s" % (ref, name)
        if bt["nesting_mode"] == "single":
            iterable = "%s == null ? [] : [%s]" % (source, source)
        else:
            iterable = "%s == null ? [] : %s" % (source, source)
        lines.append("")
        lines.append('%sdynamic "%s" {' % (pad, name))
        lines.append("%s  for_each = %s" % (pad, iterable))
        lines.append("%s  content {" % pad)
        lines.extend(_render_block_body(bt["block"], "%s.value" % name, indent + 4))
        lines.append("%s  }" % pad)
        lines.append("%s}" % pad)
    return lines


def render_main(resource_type, resource_schema):
    body = _render_block_body(resource_schema["block"], "each.value", 2)
    return (
        _header(resource_type, _provider_of(resource_type))
        + 'resource "%s" "this" {\n' % resource_type
        + "  for_each = var.items\n\n"
        + "\n".join(body)
        + "\n}\n"
    )


def render_variables(resource_type, resource_schema):
    block = resource_schema["block"]
    cls = classify_attributes(block)
    lines = []
    for name in cls["required"]:
        lines.append("    %s = %s" % (name, hcl_type(block["attributes"][name]["type"])))
    for name in cls["optional"]:
        lines.append(
            "    %s = optional(%s)" % (name, hcl_type(block["attributes"][name]["type"]))
        )
    for name, bt in sorted((block.get("block_types") or {}).items()):
        lines.append("    %s = optional(%s)" % (name, _block_input_type(bt, 4)))
    return (
        _header(resource_type, _provider_of(resource_type))
        + 'variable "items" {\n'
        + '  description = "%s instances, keyed by a stable identifier."\n'
        % resource_type
        + "  type = map(object({\n%s\n  }))\n}\n" % "\n".join(lines)
    )


_SAMPLE_VALUES = {"string": "example", "bool": True, "number": 1}


def render_outputs(resource_type, resource_schema):
    attrs = resource_schema["block"].get("attributes") or {}
    out = (
        _header(resource_type, _provider_of(resource_type))
        + 'output "items" {\n'
        + '  description = "All managed %s resources, keyed as in var.items."\n'
        % resource_type
        + "  value = %s.this\n}\n" % resource_type
    )
    if "name" in attrs and "id" in attrs:
        out += (
            '\noutput "name_to_id" {\n'
            + '  description = "Map of resource name to provider-assigned id."\n'
            + "  value = { for k, v in %s.this : v.name => v.id }\n}\n" % resource_type
        )
    return out


def render_readme(resource_type, resource_schema):
    return (
        "# %s (generated module)\n\n"
        "Manages `%s` via a typed `items` map. GENERATED — do not edit by\n"
        "hand (AGENTS.md rule 6). Regenerate: `make generate`. Test:\n"
        "`terraform -chdir=modules/%s test`.\n"
        % (resource_type, resource_type, resource_type)
    )


def render_sample(resource_type, resource_schema):
    cls = classify_attributes(resource_schema["block"])
    item = {}
    for name in cls["required"]:
        enc = resource_schema["block"]["attributes"][name]["type"]
        item[name] = _SAMPLE_VALUES.get(enc, "example") if isinstance(enc, str) else []
    return json.dumps({"items": {"example": item}}, indent=2, sort_keys=True) + "\n"


def render_test(resource_type, resource_schema):
    provider = _provider_of(resource_type)
    return (
        "# GENERATED smoke test — plan against a mocked provider; no credentials.\n"
        'mock_provider "%s" {}\n\n'
        "run \"defaults_plan\" {\n"
        "  command = plan\n\n"
        "  assert {\n"
        "    condition     = length(var.items) == 1\n"
        '    error_message = "sample fixture must contain exactly one item"\n'
        "  }\n"
        "}\n" % provider
    )
