"""Generate isolated per-resource Terraform env roots from the registry.

One root per (tenant, resource): envs/<tenant>/<resource>/. Each calls a
single module, keeping state blast-radius per resource (user's choice). The
tenant label is opaque (any string); API targeting comes from env vars at
plan time, never from the label. Authoring-side; output committed; never
hand-edited. Stdlib-only, Python 3.6-floor — see AGENTS.md rules 5-7.
"""
import os
import subprocess
import sys

from tools.registry import generated_types

ENVS_ROOT = "envs"


def _provider_of(resource_type):
    return resource_type.split("_", 1)[0]


def render_env_main(resource_type, tenant):
    provider = _provider_of(resource_type)
    return (
        "# GENERATED by tools/gen_env.py for tenant %r — do not edit.\n"
        "# Regenerate: make gen-env TENANT=%s\n\n"
        "terraform {\n"
        '  required_version = ">= 1.5"\n'
        "  required_providers {\n"
        "    %s = {\n"
        '      source = "zscaler/%s"\n'
        "    }\n"
        "  }\n"
        "  # backend configured per environment (Plan 5 / operator)\n"
        "}\n\n"
        'provider "%s" {\n'
        "  # credentials via env (ZSCALER_*/ZIA_*/ZPA_*); see tools/FETCH.md\n"
        "}\n\n"
        'variable "items" {\n'
        "  # opaque at the root; the module enforces the strict type.\n"
        "  type = any\n"
        "}\n\n"
        'module "%s" {\n'
        '  source = "../../../modules/%s"\n'
        "  items = var.items\n"
        "}\n"
        % (
            tenant, tenant, provider, provider, provider,
            resource_type, resource_type,
        )
    )


def render_env_readme(resource_type, tenant):
    return (
        "# %s / %s (generated env root)\n\n"
        "Isolated Terraform root for `%s` on tenant `%s`. GENERATED — do not\n"
        "edit (AGENTS.md rule 6); regenerate with `make gen-env TENANT=%s`.\n"
        "Config is loaded from `config/%s/%s.auto.tfvars.json` at plan time.\n"
        % (tenant, resource_type, resource_type, tenant, tenant, tenant, resource_type)
    )


def render_env_test(resource_type, tenant):
    provider = _provider_of(resource_type)
    return (
        "# GENERATED smoke test — the root composes and plans against a\n"
        "# mocked provider; no credentials. Regenerate: make gen-env TENANT=%s\n"
        'mock_provider "%s" {}\n\n'
        'run "empty_plan" {\n'
        "  command = plan\n\n"
        "  variables {\n"
        "    items = {}\n"
        "  }\n"
        "}\n" % (tenant, provider)
    )


def _fmt(text):
    proc = subprocess.run(
        ["terraform", "fmt", "-"], input=text.encode(), stdout=subprocess.PIPE, check=True
    )
    return proc.stdout.decode()


def generate_env(tenant, out_root=ENVS_ROOT, fmt=True):
    for resource_type in generated_types():
        base = os.path.join(out_root, tenant, resource_type)
        os.makedirs(base, exist_ok=True)
        main_text = render_env_main(resource_type, tenant)
        if fmt:
            main_text = _fmt(main_text)
        with open(os.path.join(base, "main.tf"), "w") as f:
            f.write(main_text)
        sys.stderr.write("wrote %s\n" % os.path.join(base, "main.tf"))
        with open(os.path.join(base, "README.md"), "w") as f:
            f.write(render_env_readme(resource_type, tenant))
        tests_dir = os.path.join(base, "tests")
        os.makedirs(tests_dir, exist_ok=True)
        test_text = render_env_test(resource_type, tenant)
        if fmt:
            test_text = _fmt(test_text)
        with open(os.path.join(tests_dir, "smoke.tftest.hcl"), "w") as f:
            f.write(test_text)
        sys.stderr.write("wrote %s\n" % os.path.join(tests_dir, "smoke.tftest.hcl"))


def main(argv=None):
    argv = argv if argv is not None else sys.argv[1:]
    if len(argv) != 1:
        sys.stderr.write("usage: python -m tools.gen_env <tenant>\n")
        return 2
    generate_env(argv[0])
    return 0


if __name__ == "__main__":
    sys.exit(main())
