# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_pra_approval_controller" "this" {
  for_each = var.items

  email_ids      = each.value.email_ids
  end_time       = each.value.end_time
  microtenant_id = each.value.microtenant_id
  start_time     = each.value.start_time
  status         = each.value.status

  dynamic "applications" {
    for_each = each.value.applications == null ? [] : each.value.applications
    content {
      id = applications.value.id
    }
  }

  dynamic "working_hours" {
    for_each = each.value.working_hours == null ? [] : each.value.working_hours
    content {
      days            = working_hours.value.days
      end_time        = working_hours.value.end_time
      end_time_cron   = working_hours.value.end_time_cron
      start_time      = working_hours.value.start_time
      start_time_cron = working_hours.value.start_time_cron
      timezone        = working_hours.value.timezone
    }
  }
}
