# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_pra_approval_controller instances, keyed by a stable identifier."
  type = map(object({
    email_ids      = optional(set(string))
    end_time       = optional(string)
    microtenant_id = optional(string)
    start_time     = optional(string)
    status         = optional(string)
    applications = optional(set(object({
      id = optional(list(string))
    })))
    working_hours = optional(set(object({
      days            = optional(set(string))
      end_time        = optional(string)
      end_time_cron   = optional(string)
      start_time      = optional(string)
      start_time_cron = optional(string)
      timezone        = optional(string)
    })))
  }))
}
