# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_sandbox_behavioral_analysis" "this" {
  for_each = var.items

  file_hashes_to_be_blocked = each.value.file_hashes_to_be_blocked
}
