# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

output "items" {
  description = "All managed zia_sandbox_behavioral_analysis resources, keyed as in var.items."
  value       = zia_sandbox_behavioral_analysis.this
}
