# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_sandbox_behavioral_analysis instances, keyed by a stable identifier."
  type = map(object({
    file_hashes_to_be_blocked = optional(set(string))
  }))
}
