# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_traffic_forwarding_gre_tunnel" "this" {
  for_each = var.items

  source_ip         = each.value.source_ip
  comment           = each.value.comment
  country_code      = each.value.country_code
  internal_ip_range = each.value.internal_ip_range
  ip_unnumbered     = each.value.ip_unnumbered
  within_country    = each.value.within_country

  dynamic "primary_dest_vip" {
    for_each = each.value.primary_dest_vip == null ? [] : each.value.primary_dest_vip
    content {
      datacenter = primary_dest_vip.value.datacenter
      id         = primary_dest_vip.value.id
      virtual_ip = primary_dest_vip.value.virtual_ip
    }
  }

  dynamic "secondary_dest_vip" {
    for_each = each.value.secondary_dest_vip == null ? [] : each.value.secondary_dest_vip
    content {
      datacenter = secondary_dest_vip.value.datacenter
      id         = secondary_dest_vip.value.id
      virtual_ip = secondary_dest_vip.value.virtual_ip
    }
  }
}
