# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_traffic_forwarding_gre_tunnel instances, keyed by a stable identifier."
  type = map(object({
    source_ip         = string
    comment           = optional(string)
    country_code      = optional(string)
    internal_ip_range = optional(string)
    ip_unnumbered     = optional(bool)
    within_country    = optional(bool)
    primary_dest_vip = optional(set(object({
      datacenter = optional(string)
      id         = optional(number)
      virtual_ip = optional(string)
    })))
    secondary_dest_vip = optional(set(object({
      datacenter = optional(string)
      id         = optional(number)
      virtual_ip = optional(string)
    })))
  }))
}
