# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_url_categories" "this" {
  for_each = var.items

  configured_name                           = each.value.configured_name
  custom_category                           = each.value.custom_category
  custom_ip_ranges_count                    = each.value.custom_ip_ranges_count
  custom_urls_count                         = each.value.custom_urls_count
  db_categorized_urls                       = each.value.db_categorized_urls
  description                               = each.value.description
  editable                                  = each.value.editable
  ip_ranges                                 = each.value.ip_ranges
  ip_ranges_retaining_parent_category       = each.value.ip_ranges_retaining_parent_category
  ip_ranges_retaining_parent_category_count = each.value.ip_ranges_retaining_parent_category_count
  keywords                                  = each.value.keywords
  keywords_retaining_parent_category        = each.value.keywords_retaining_parent_category
  regex_patterns                            = each.value.regex_patterns
  regex_patterns_retaining_parent_category  = each.value.regex_patterns_retaining_parent_category
  super_category                            = each.value.super_category
  type                                      = each.value.type
  url_type                                  = each.value.url_type
  urls                                      = each.value.urls
  urls_retaining_parent_category_count      = each.value.urls_retaining_parent_category_count

  dynamic "scopes" {
    for_each = each.value.scopes == null ? [] : each.value.scopes
    content {
      type = scopes.value.type

      dynamic "scope_entities" {
        for_each = scopes.value.scope_entities == null ? [] : [scopes.value.scope_entities]
        content {
          id = scope_entities.value.id
        }
      }

      dynamic "scope_group_member_entities" {
        for_each = scopes.value.scope_group_member_entities == null ? [] : [scopes.value.scope_group_member_entities]
        content {
          id = scope_group_member_entities.value.id
        }
      }
    }
  }

  dynamic "url_keyword_counts" {
    for_each = each.value.url_keyword_counts == null ? [] : [each.value.url_keyword_counts]
    content {
      retain_parent_keyword_count = url_keyword_counts.value.retain_parent_keyword_count
      retain_parent_url_count     = url_keyword_counts.value.retain_parent_url_count
      total_keyword_count         = url_keyword_counts.value.total_keyword_count
      total_url_count             = url_keyword_counts.value.total_url_count
    }
  }
}
