# GENERATED by tools/gen_module.py from schemas/provider/zcc.json — do not edit.
# Regenerate: make generate

resource "zcc_failopen_policy" "this" {
  for_each = var.items

  active                                  = each.value.active
  captive_portal_web_sec_disable_minutes  = each.value.captive_portal_web_sec_disable_minutes
  enable_captive_portal_detection         = each.value.enable_captive_portal_detection
  enable_fail_open                        = each.value.enable_fail_open
  enable_strict_enforcement_prompt        = each.value.enable_strict_enforcement_prompt
  enable_web_sec_on_proxy_unreachable     = each.value.enable_web_sec_on_proxy_unreachable
  enable_web_sec_on_tunnel_failure        = each.value.enable_web_sec_on_tunnel_failure
  strict_enforcement_prompt_delay_minutes = each.value.strict_enforcement_prompt_delay_minutes
  strict_enforcement_prompt_message       = each.value.strict_enforcement_prompt_message
  tunnel_failure_retry_count              = each.value.tunnel_failure_retry_count
}
