# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_ftp_control_policy" "this" {
  for_each = var.items

  ftp_enabled           = each.value.ftp_enabled
  ftp_over_http_enabled = each.value.ftp_over_http_enabled
  url_categories        = each.value.url_categories
  urls                  = each.value.urls
}
