# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_ftp_control_policy instances, keyed by a stable identifier."
  type = map(object({
    ftp_enabled           = optional(bool)
    ftp_over_http_enabled = optional(bool)
    url_categories        = optional(set(string))
    urls                  = optional(set(string))
  }))
}
