# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_end_user_notification" "this" {
  for_each = var.items

  aup_custom_frequency                     = each.value.aup_custom_frequency
  aup_day_offset                           = each.value.aup_day_offset
  aup_frequency                            = each.value.aup_frequency
  aup_message                              = each.value.aup_message
  caution_again_after                      = each.value.caution_again_after
  caution_custom_text                      = each.value.caution_custom_text
  caution_per_domain                       = each.value.caution_per_domain
  custom_text                              = each.value.custom_text
  display_company_logo                     = each.value.display_company_logo
  display_company_name                     = each.value.display_company_name
  display_reason                           = each.value.display_reason
  idp_proxy_notification_text              = each.value.idp_proxy_notification_text
  notification_type                        = each.value.notification_type
  org_policy_link                          = each.value.org_policy_link
  quarantine_custom_notification_text      = each.value.quarantine_custom_notification_text
  redirect_url                             = each.value.redirect_url
  security_review_custom_location          = each.value.security_review_custom_location
  security_review_enabled                  = each.value.security_review_enabled
  security_review_submit_to_security_cloud = each.value.security_review_submit_to_security_cloud
  security_review_text                     = each.value.security_review_text
  support_email                            = each.value.support_email
  support_phone                            = each.value.support_phone
  url_cat_review_custom_location           = each.value.url_cat_review_custom_location
  url_cat_review_enabled                   = each.value.url_cat_review_enabled
  url_cat_review_submit_to_security_cloud  = each.value.url_cat_review_submit_to_security_cloud
  url_cat_review_text                      = each.value.url_cat_review_text
  web_dlp_review_custom_location           = each.value.web_dlp_review_custom_location
  web_dlp_review_enabled                   = each.value.web_dlp_review_enabled
  web_dlp_review_submit_to_security_cloud  = each.value.web_dlp_review_submit_to_security_cloud
  web_dlp_review_text                      = each.value.web_dlp_review_text
}
