# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_end_user_notification instances, keyed by a stable identifier."
  type = map(object({
    aup_custom_frequency                     = optional(number)
    aup_day_offset                           = optional(number)
    aup_frequency                            = optional(string)
    aup_message                              = optional(string)
    caution_again_after                      = optional(number)
    caution_custom_text                      = optional(string)
    caution_per_domain                       = optional(bool)
    custom_text                              = optional(string)
    display_company_logo                     = optional(bool)
    display_company_name                     = optional(bool)
    display_reason                           = optional(bool)
    idp_proxy_notification_text              = optional(string)
    notification_type                        = optional(string)
    org_policy_link                          = optional(string)
    quarantine_custom_notification_text      = optional(string)
    redirect_url                             = optional(string)
    security_review_custom_location          = optional(string)
    security_review_enabled                  = optional(bool)
    security_review_submit_to_security_cloud = optional(bool)
    security_review_text                     = optional(string)
    support_email                            = optional(string)
    support_phone                            = optional(string)
    url_cat_review_custom_location           = optional(string)
    url_cat_review_enabled                   = optional(bool)
    url_cat_review_submit_to_security_cloud  = optional(bool)
    url_cat_review_text                      = optional(string)
    web_dlp_review_custom_location           = optional(string)
    web_dlp_review_enabled                   = optional(bool)
    web_dlp_review_submit_to_security_cloud  = optional(bool)
    web_dlp_review_text                      = optional(string)
  }))
}
