# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_admin_roles" "this" {
  for_each = var.items

  admin_acct_access       = each.value.admin_acct_access
  alerting_access         = each.value.alerting_access
  analysis_access         = each.value.analysis_access
  dashboard_access        = each.value.dashboard_access
  device_info_access      = each.value.device_info_access
  ext_feature_permissions = each.value.ext_feature_permissions
  feature_permissions     = each.value.feature_permissions
  is_auditor              = each.value.is_auditor
  is_non_editable         = each.value.is_non_editable
  logs_limit              = each.value.logs_limit
  name                    = each.value.name
  permissions             = each.value.permissions
  policy_access           = each.value.policy_access
  rank                    = each.value.rank
  report_access           = each.value.report_access
  report_time_duration    = each.value.report_time_duration
  role_type               = each.value.role_type
  username_access         = each.value.username_access
}
