# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_admin_roles instances, keyed by a stable identifier."
  type = map(object({
    admin_acct_access       = optional(string)
    alerting_access         = optional(string)
    analysis_access         = optional(string)
    dashboard_access        = optional(string)
    device_info_access      = optional(string)
    ext_feature_permissions = optional(map(string))
    feature_permissions     = optional(map(string))
    is_auditor              = optional(bool)
    is_non_editable         = optional(bool)
    logs_limit              = optional(string)
    name                    = optional(string)
    permissions             = optional(set(string))
    policy_access           = optional(string)
    rank                    = optional(number)
    report_access           = optional(string)
    report_time_duration    = optional(number)
    role_type               = optional(string)
    username_access         = optional(string)
  }))
}
