# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_user_management" "this" {
  for_each = var.items

  email           = each.value.email
  name            = each.value.name
  password        = each.value.password
  auth_methods    = each.value.auth_methods
  comments        = each.value.comments
  temp_auth_email = each.value.temp_auth_email

  dynamic "department" {
    for_each = each.value.department == null ? [] : [each.value.department]
    content {
      comments = department.value.comments
      deleted  = department.value.deleted
      id       = department.value.id
      idp_id   = department.value.idp_id
      name     = department.value.name
    }
  }

  dynamic "groups" {
    for_each = each.value.groups == null ? [] : [each.value.groups]
    content {
      id = groups.value.id
    }
  }
}
