# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zia_user_management instances, keyed by a stable identifier."
  type = map(object({
    email           = string
    name            = string
    password        = string
    auth_methods    = optional(set(string))
    comments        = optional(string)
    temp_auth_email = optional(string)
    department = optional(object({
      comments = optional(string)
      deleted  = optional(bool)
      id       = optional(number)
      idp_id   = optional(number)
      name     = optional(string)
    }))
    groups = optional(object({
      id = optional(set(number))
    }))
  }))
}
