# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

resource "zpa_user_portal_aup" "this" {
  for_each = var.items

  aup            = each.value.aup
  description    = each.value.description
  email          = each.value.email
  enabled        = each.value.enabled
  microtenant_id = each.value.microtenant_id
  name           = each.value.name
  phone_num      = each.value.phone_num
}
