# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

output "items" {
  description = "All managed zpa_user_portal_aup resources, keyed as in var.items."
  value       = zpa_user_portal_aup.this
}
