# GENERATED by tools/gen_module.py from schemas/provider/zpa.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "zpa_user_portal_aup instances, keyed by a stable identifier."
  type = map(object({
    aup            = optional(string)
    description    = optional(string)
    email          = optional(string)
    enabled        = optional(bool)
    microtenant_id = optional(string)
    name           = optional(string)
    phone_num      = optional(string)
  }))
}
