# GENERATED by tools/gen_module.py from schemas/provider/zia.json — do not edit.
# Regenerate: make generate

resource "zia_rule_labels" "this" {
  for_each = var.items

  description = each.value.description
  name        = each.value.name
}
